domain_path: /home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/sw/video-pipe-sw-v1/kv260-video/export/kv260-video/sw/standalone_psu_cortexa53_0
app_src_dir: /home/alen/AMD-Xilinx/2025.2/Vitis/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
