# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.srcs/sources_1/bd/broncho_video/ip/broncho_video_ila_0_3/broncho_video_ila_0_3.xci
# IP: The module: 'broncho_video_ila_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_ila_0_3/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'broncho_video_ila_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_ila_0_3/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'broncho_video_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_ila_0_3/broncho_video_ila_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'broncho_video_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.srcs/sources_1/bd/broncho_video/ip/broncho_video_ila_0_3/broncho_video_ila_0_3.xci
# IP: The module: 'broncho_video_ila_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_ila_0_3/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'broncho_video_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_ila_0_3/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'broncho_video_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_ila_0_3/broncho_video_ila_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'broncho_video_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
