// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ISPPipeline_accel_g_kernel_ap_uint_10_5_s (
        ap_clk,
        ap_rst,
        imgblock_0_2_val,
        imgblock_1_2_val,
        imgblock_2_0_val,
        imgblock_2_1_val,
        imgblock_2_2_val,
        imgblock_2_3_val,
        imgblock_2_4_val,
        imgblock_3_2_val,
        imgblock_4_2_val,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [9:0] imgblock_0_2_val;
input  [9:0] imgblock_1_2_val;
input  [9:0] imgblock_2_0_val;
input  [9:0] imgblock_2_1_val;
input  [9:0] imgblock_2_2_val;
input  [9:0] imgblock_2_3_val;
input  [9:0] imgblock_2_4_val;
input  [9:0] imgblock_3_2_val;
input  [9:0] imgblock_4_2_val;
output  [12:0] ap_return;
input   ap_ce;

reg[12:0] ap_return;

wire   [12:0] sub_ln69_fu_146_p2;
reg   [12:0] sub_ln69_reg_317;
wire    ap_block_pp0_stage0_11001;
wire   [13:0] add_ln69_3_fu_218_p2;
reg   [13:0] add_ln69_3_reg_322;
reg   [0:0] tmp_reg_327;
reg   [11:0] trunc_ln72_1_reg_332;
reg   [11:0] trunc_ln72_2_reg_337;
wire    ap_block_pp0_stage0;
wire   [10:0] zext_ln69_1_fu_104_p1;
wire   [10:0] zext_ln69_fu_100_p1;
wire   [10:0] add_ln69_fu_108_p2;
wire   [10:0] zext_ln69_3_fu_118_p1;
wire   [10:0] zext_ln69_4_fu_122_p1;
wire   [10:0] add_ln69_1_fu_126_p2;
wire   [11:0] zext_ln69_6_fu_132_p1;
wire   [11:0] zext_ln69_2_fu_114_p1;
wire   [11:0] add_ln69_2_fu_136_p2;
wire   [12:0] zext_ln69_5_fu_142_p1;
wire   [10:0] zext_ln70_1_fu_156_p1;
wire   [10:0] zext_ln70_fu_152_p1;
wire   [10:0] add_ln70_fu_160_p2;
wire   [10:0] zext_ln70_3_fu_170_p1;
wire   [10:0] zext_ln70_4_fu_174_p1;
wire   [10:0] add_ln70_1_fu_178_p2;
wire   [11:0] zext_ln70_5_fu_184_p1;
wire   [11:0] zext_ln70_2_fu_166_p1;
wire   [11:0] add_ln70_2_fu_188_p2;
wire   [12:0] shl_ln_fu_194_p3;
wire   [11:0] shl_ln69_1_fu_206_p3;
wire   [13:0] zext_ln69_7_fu_202_p1;
wire   [13:0] zext_ln69_8_fu_214_p1;
wire   [14:0] zext_ln72_fu_227_p1;
wire  signed [14:0] sext_ln69_fu_224_p1;
wire   [14:0] add_ln72_fu_230_p2;
wire   [14:0] sub_ln72_fu_244_p2;
wire  signed [12:0] sext_ln72_fu_270_p1;
wire   [13:0] zext_ln72_1_fu_273_p1;
wire  signed [12:0] sext_ln72_1_fu_283_p1;
wire   [13:0] sub_ln72_1_fu_277_p2;
wire   [13:0] zext_ln72_2_fu_286_p1;
wire   [13:0] res_fu_290_p3;
wire   [0:0] tmp_37_fu_301_p3;
wire   [12:0] trunc_ln69_fu_297_p1;
wire   [12:0] select_ln73_fu_309_p3;
reg    ap_ce_reg;
reg   [9:0] imgblock_0_2_val_int_reg;
reg   [9:0] imgblock_1_2_val_int_reg;
reg   [9:0] imgblock_2_0_val_int_reg;
reg   [9:0] imgblock_2_1_val_int_reg;
reg   [9:0] imgblock_2_2_val_int_reg;
reg   [9:0] imgblock_2_3_val_int_reg;
reg   [9:0] imgblock_2_4_val_int_reg;
reg   [9:0] imgblock_3_2_val_int_reg;
reg   [9:0] imgblock_4_2_val_int_reg;
reg   [12:0] ap_return_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        add_ln69_3_reg_322[13 : 1] <= add_ln69_3_fu_218_p2[13 : 1];
        sub_ln69_reg_317 <= sub_ln69_fu_146_p2;
        tmp_reg_327 <= add_ln72_fu_230_p2[32'd14];
        trunc_ln72_1_reg_332 <= {{sub_ln72_fu_244_p2[14:3]}};
        trunc_ln72_2_reg_337 <= {{add_ln72_fu_230_p2[14:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= select_ln73_fu_309_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        imgblock_0_2_val_int_reg <= imgblock_0_2_val;
        imgblock_1_2_val_int_reg <= imgblock_1_2_val;
        imgblock_2_0_val_int_reg <= imgblock_2_0_val;
        imgblock_2_1_val_int_reg <= imgblock_2_1_val;
        imgblock_2_2_val_int_reg <= imgblock_2_2_val;
        imgblock_2_3_val_int_reg <= imgblock_2_3_val;
        imgblock_2_4_val_int_reg <= imgblock_2_4_val;
        imgblock_3_2_val_int_reg <= imgblock_3_2_val;
        imgblock_4_2_val_int_reg <= imgblock_4_2_val;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = select_ln73_fu_309_p3;
    end else begin
        ap_return = 'bx;
    end
end

assign add_ln69_1_fu_126_p2 = (zext_ln69_3_fu_118_p1 + zext_ln69_4_fu_122_p1);

assign add_ln69_2_fu_136_p2 = (zext_ln69_6_fu_132_p1 + zext_ln69_2_fu_114_p1);

assign add_ln69_3_fu_218_p2 = (zext_ln69_7_fu_202_p1 + zext_ln69_8_fu_214_p1);

assign add_ln69_fu_108_p2 = (zext_ln69_1_fu_104_p1 + zext_ln69_fu_100_p1);

assign add_ln70_1_fu_178_p2 = (zext_ln70_3_fu_170_p1 + zext_ln70_4_fu_174_p1);

assign add_ln70_2_fu_188_p2 = (zext_ln70_5_fu_184_p1 + zext_ln70_2_fu_166_p1);

assign add_ln70_fu_160_p2 = (zext_ln70_1_fu_156_p1 + zext_ln70_fu_152_p1);

assign add_ln72_fu_230_p2 = ($signed(zext_ln72_fu_227_p1) + $signed(sext_ln69_fu_224_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign res_fu_290_p3 = ((tmp_reg_327[0:0] == 1'b1) ? sub_ln72_1_fu_277_p2 : zext_ln72_2_fu_286_p1);

assign select_ln73_fu_309_p3 = ((tmp_37_fu_301_p3[0:0] == 1'b1) ? 13'd0 : trunc_ln69_fu_297_p1);

assign sext_ln69_fu_224_p1 = $signed(sub_ln69_reg_317);

assign sext_ln72_1_fu_283_p1 = $signed(trunc_ln72_2_reg_337);

assign sext_ln72_fu_270_p1 = $signed(trunc_ln72_1_reg_332);

assign shl_ln69_1_fu_206_p3 = {{imgblock_2_2_val_int_reg}, {2'd0}};

assign shl_ln_fu_194_p3 = {{add_ln70_2_fu_188_p2}, {1'd0}};

assign sub_ln69_fu_146_p2 = (13'd0 - zext_ln69_5_fu_142_p1);

assign sub_ln72_1_fu_277_p2 = (14'd0 - zext_ln72_1_fu_273_p1);

assign sub_ln72_fu_244_p2 = (15'd0 - add_ln72_fu_230_p2);

assign tmp_37_fu_301_p3 = res_fu_290_p3[32'd13];

assign trunc_ln69_fu_297_p1 = res_fu_290_p3[12:0];

assign zext_ln69_1_fu_104_p1 = imgblock_2_0_val_int_reg;

assign zext_ln69_2_fu_114_p1 = add_ln69_fu_108_p2;

assign zext_ln69_3_fu_118_p1 = imgblock_2_4_val_int_reg;

assign zext_ln69_4_fu_122_p1 = imgblock_4_2_val_int_reg;

assign zext_ln69_5_fu_142_p1 = add_ln69_2_fu_136_p2;

assign zext_ln69_6_fu_132_p1 = add_ln69_1_fu_126_p2;

assign zext_ln69_7_fu_202_p1 = shl_ln_fu_194_p3;

assign zext_ln69_8_fu_214_p1 = shl_ln69_1_fu_206_p3;

assign zext_ln69_fu_100_p1 = imgblock_0_2_val_int_reg;

assign zext_ln70_1_fu_156_p1 = imgblock_2_1_val_int_reg;

assign zext_ln70_2_fu_166_p1 = add_ln70_fu_160_p2;

assign zext_ln70_3_fu_170_p1 = imgblock_2_3_val_int_reg;

assign zext_ln70_4_fu_174_p1 = imgblock_3_2_val_int_reg;

assign zext_ln70_5_fu_184_p1 = add_ln70_1_fu_178_p2;

assign zext_ln70_fu_152_p1 = imgblock_1_2_val_int_reg;

assign zext_ln72_1_fu_273_p1 = $unsigned(sext_ln72_fu_270_p1);

assign zext_ln72_2_fu_286_p1 = $unsigned(sext_ln72_1_fu_283_p1);

assign zext_ln72_fu_227_p1 = add_ln69_3_reg_322;

always @ (posedge ap_clk) begin
    add_ln69_3_reg_322[0] <= 1'b0;
end

endmodule //ISPPipeline_accel_g_kernel_ap_uint_10_5_s
