// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ISPPipeline_accel_xfccmkernel_20_1080_1920_22_1_2_2_13_13_1920_Pipeline_colLoop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ltm_in_data_dout,
        ltm_in_data_num_data_valid,
        ltm_in_data_fifo_cap,
        ltm_in_data_empty_n,
        ltm_in_data_read,
        lsc_out_data_din,
        lsc_out_data_num_data_valid,
        lsc_out_data_fifo_cap,
        lsc_out_data_full_n,
        lsc_out_data_write,
        width
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [29:0] ltm_in_data_dout;
input  [2:0] ltm_in_data_num_data_valid;
input  [2:0] ltm_in_data_fifo_cap;
input   ltm_in_data_empty_n;
output   ltm_in_data_read;
output  [29:0] lsc_out_data_din;
input  [2:0] lsc_out_data_num_data_valid;
input  [2:0] lsc_out_data_fifo_cap;
input   lsc_out_data_full_n;
output   lsc_out_data_write;
input  [10:0] width;

reg ap_idle;
reg ltm_in_data_read;
reg lsc_out_data_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state9_pp0_stage0_iter8;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln246_fu_177_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ltm_in_data_blk_n;
wire    ap_block_pp0_stage0;
reg    lsc_out_data_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [9:0] r_fu_194_p1;
reg   [9:0] r_reg_775;
reg   [9:0] r_reg_775_pp0_iter2_reg;
reg   [9:0] r_reg_775_pp0_iter3_reg;
reg   [9:0] g_reg_782;
reg   [9:0] g_reg_782_pp0_iter2_reg;
reg   [9:0] g_reg_782_pp0_iter3_reg;
reg   [9:0] b_reg_788;
reg   [9:0] b_reg_788_pp0_iter2_reg;
reg   [9:0] b_reg_788_pp0_iter3_reg;
wire   [38:0] zext_ln265_1_fu_252_p1;
reg   [13:0] trunc_ln4_reg_836;
reg   [15:0] trunc_ln5_reg_841;
reg   [18:0] trunc_ln_reg_846;
reg   [15:0] trunc_ln1_reg_851;
reg   [15:0] trunc_ln2_reg_856;
reg   [12:0] trunc_ln3_reg_861;
reg   [18:0] tmp_7_reg_866;
reg   [18:0] tmp_9_reg_871;
wire   [16:0] add_ln278_fu_362_p2;
reg   [16:0] add_ln278_reg_876;
reg   [18:0] tmp_s_reg_881;
wire   [13:0] value_r_fu_453_p3;
reg   [13:0] value_r_reg_886;
wire   [12:0] value_g_fu_536_p3;
reg   [12:0] value_g_reg_891;
wire   [12:0] value_b_fu_610_p3;
reg   [12:0] value_b_reg_896;
reg   [3:0] tmp_11_reg_901;
reg   [2:0] tmp_13_reg_906;
reg   [2:0] tmp_15_reg_911;
wire   [9:0] select_ln99_fu_676_p3;
reg   [9:0] select_ln99_reg_916;
wire   [9:0] select_ln99_1_fu_712_p3;
reg   [9:0] select_ln99_1_reg_921;
wire   [9:0] select_ln99_2_fu_748_p3;
reg   [9:0] select_ln99_2_reg_926;
reg   [10:0] j_fu_126;
wire   [10:0] j_2_fu_183_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_j_1;
reg    ap_block_pp0_stage0_01001;
wire   [9:0] grp_fu_149_p0;
wire   [29:0] grp_fu_149_p1;
wire   [9:0] grp_fu_154_p0;
wire   [29:0] grp_fu_154_p1;
wire   [9:0] grp_fu_159_p0;
wire   [29:0] grp_fu_159_p1;
wire   [9:0] grp_fu_164_p0;
wire  signed [28:0] grp_fu_164_p1;
wire   [9:0] grp_fu_224_p0;
wire  signed [22:0] grp_fu_224_p1;
wire   [9:0] grp_fu_230_p0;
wire  signed [23:0] grp_fu_230_p1;
wire   [9:0] grp_fu_239_p0;
wire  signed [25:0] grp_fu_239_p1;
wire   [9:0] grp_fu_264_p0;
wire  signed [25:0] grp_fu_264_p1;
wire   [9:0] grp_fu_270_p0;
wire  signed [25:0] grp_fu_270_p1;
wire   [33:0] grp_fu_230_p2;
wire   [35:0] grp_fu_239_p2;
wire   [38:0] grp_fu_164_p2;
wire   [35:0] grp_fu_264_p2;
wire   [35:0] grp_fu_270_p2;
wire   [32:0] grp_fu_224_p2;
wire   [38:0] grp_fu_149_p2;
wire   [38:0] grp_fu_154_p2;
wire  signed [16:0] sext_ln278_1_fu_359_p1;
wire  signed [16:0] sext_ln278_fu_356_p1;
wire   [38:0] grp_fu_159_p2;
wire   [20:0] zext_ln276_fu_378_p1;
wire  signed [20:0] sext_ln276_fu_381_p1;
wire   [20:0] add_ln276_fu_384_p2;
wire  signed [20:0] sext_ln276_1_fu_390_p1;
wire   [20:0] add_ln276_1_fu_393_p2;
wire   [12:0] tmp_2_fu_399_p4;
wire   [7:0] trunc_ln276_fu_421_p1;
wire   [27:0] tmp_1_fu_425_p3;
wire  signed [13:0] sext_ln276_2_fu_409_p1;
wire   [0:0] icmp_ln276_fu_433_p2;
wire   [13:0] add_ln276_2_fu_439_p2;
wire   [0:0] tmp_fu_413_p3;
wire   [13:0] select_ln276_fu_445_p3;
wire   [19:0] zext_ln277_fu_464_p1;
wire  signed [19:0] sext_ln277_fu_461_p1;
wire   [19:0] add_ln277_fu_467_p2;
wire  signed [19:0] sext_ln277_1_fu_473_p1;
wire   [19:0] add_ln277_1_fu_476_p2;
wire   [11:0] tmp_4_fu_482_p4;
wire   [7:0] trunc_ln277_fu_504_p1;
wire   [27:0] tmp_3_fu_508_p3;
wire  signed [12:0] sext_ln277_2_fu_492_p1;
wire   [0:0] icmp_ln277_fu_516_p2;
wire   [12:0] add_ln277_2_fu_522_p2;
wire   [0:0] tmp_8_fu_496_p3;
wire   [12:0] select_ln277_fu_528_p3;
wire   [19:0] zext_ln278_fu_547_p1;
wire  signed [19:0] sext_ln278_2_fu_544_p1;
wire   [19:0] add_ln278_1_fu_550_p2;
wire   [11:0] tmp_6_fu_556_p4;
wire   [7:0] trunc_ln278_fu_578_p1;
wire   [27:0] tmp_5_fu_582_p3;
wire  signed [12:0] sext_ln278_3_fu_566_p1;
wire   [0:0] icmp_ln278_fu_590_p2;
wire   [12:0] add_ln278_2_fu_596_p2;
wire   [0:0] tmp_10_fu_570_p3;
wire   [12:0] select_ln278_fu_602_p3;
wire   [0:0] icmp_ln97_fu_648_p2;
wire  signed [13:0] select_ln97_fu_653_p3;
wire  signed [15:0] sext_ln96_fu_660_p1;
wire   [0:0] tmp_12_fu_664_p3;
wire   [9:0] trunc_ln99_fu_672_p1;
wire   [0:0] icmp_ln97_1_fu_684_p2;
wire  signed [12:0] select_ln97_1_fu_689_p3;
wire  signed [15:0] sext_ln96_1_fu_696_p1;
wire   [0:0] tmp_14_fu_700_p3;
wire   [9:0] trunc_ln99_1_fu_708_p1;
wire   [0:0] icmp_ln97_2_fu_720_p2;
wire  signed [12:0] select_ln97_2_fu_725_p3;
wire  signed [15:0] sext_ln96_2_fu_732_p1;
wire   [0:0] tmp_16_fu_736_p3;
wire   [9:0] trunc_ln99_2_fu_744_p1;
reg    grp_fu_149_ce;
reg    grp_fu_154_ce;
reg    grp_fu_159_ce;
reg    grp_fu_164_ce;
reg    grp_fu_224_ce;
reg    grp_fu_230_ce;
reg    grp_fu_239_ce;
reg    grp_fu_264_ce;
reg    grp_fu_270_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [38:0] grp_fu_149_p00;
wire   [38:0] grp_fu_159_p00;
wire   [32:0] grp_fu_224_p00;
wire   [33:0] grp_fu_230_p00;
wire   [35:0] grp_fu_239_p00;
wire   [35:0] grp_fu_264_p00;
wire   [35:0] grp_fu_270_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 j_fu_126 = 11'd0;
#0 ap_done_reg = 1'b0;
end

ISPPipeline_accel_mul_10ns_30ns_39_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 39 ))
mul_10ns_30ns_39_2_1_U351(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_149_p0),
    .din1(grp_fu_149_p1),
    .ce(grp_fu_149_ce),
    .dout(grp_fu_149_p2)
);

ISPPipeline_accel_mul_10ns_30ns_39_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 39 ))
mul_10ns_30ns_39_2_1_U352(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_154_p0),
    .din1(grp_fu_154_p1),
    .ce(grp_fu_154_ce),
    .dout(grp_fu_154_p2)
);

ISPPipeline_accel_mul_10ns_30ns_39_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 39 ))
mul_10ns_30ns_39_2_1_U353(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_159_p0),
    .din1(grp_fu_159_p1),
    .ce(grp_fu_159_ce),
    .dout(grp_fu_159_p2)
);

ISPPipeline_accel_mul_10ns_29s_39_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 29 ),
    .dout_WIDTH( 39 ))
mul_10ns_29s_39_2_1_U354(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_164_p0),
    .din1(grp_fu_164_p1),
    .ce(grp_fu_164_ce),
    .dout(grp_fu_164_p2)
);

ISPPipeline_accel_mul_10ns_23s_33_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 33 ))
mul_10ns_23s_33_4_1_U355(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_224_p0),
    .din1(grp_fu_224_p1),
    .ce(grp_fu_224_ce),
    .dout(grp_fu_224_p2)
);

ISPPipeline_accel_mul_10ns_24s_34_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 34 ))
mul_10ns_24s_34_3_1_U356(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_230_p0),
    .din1(grp_fu_230_p1),
    .ce(grp_fu_230_ce),
    .dout(grp_fu_230_p2)
);

ISPPipeline_accel_mul_10ns_26s_36_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 36 ))
mul_10ns_26s_36_2_1_U357(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_239_p0),
    .din1(grp_fu_239_p1),
    .ce(grp_fu_239_ce),
    .dout(grp_fu_239_p2)
);

ISPPipeline_accel_mul_10ns_26s_36_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 36 ))
mul_10ns_26s_36_2_1_U358(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_264_p0),
    .din1(grp_fu_264_p1),
    .ce(grp_fu_264_ce),
    .dout(grp_fu_264_p2)
);

ISPPipeline_accel_mul_10ns_26s_36_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 36 ))
mul_10ns_26s_36_2_1_U359(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_270_p0),
    .din1(grp_fu_270_p1),
    .ce(grp_fu_270_ce),
    .dout(grp_fu_270_p2)
);

ISPPipeline_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln246_fu_177_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_126 <= j_2_fu_183_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_126 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln278_reg_876 <= add_ln278_fu_362_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        b_reg_788_pp0_iter2_reg <= b_reg_788;
        b_reg_788_pp0_iter3_reg <= b_reg_788_pp0_iter2_reg;
        g_reg_782_pp0_iter2_reg <= g_reg_782;
        g_reg_782_pp0_iter3_reg <= g_reg_782_pp0_iter2_reg;
        r_reg_775_pp0_iter2_reg <= r_reg_775;
        r_reg_775_pp0_iter3_reg <= r_reg_775_pp0_iter2_reg;
        select_ln99_1_reg_921 <= select_ln99_1_fu_712_p3;
        select_ln99_2_reg_926 <= select_ln99_2_fu_748_p3;
        select_ln99_reg_916 <= select_ln99_fu_676_p3;
        tmp_11_reg_901 <= {{value_r_fu_453_p3[13:10]}};
        tmp_13_reg_906 <= {{value_g_fu_536_p3[12:10]}};
        tmp_15_reg_911 <= {{value_b_fu_610_p3[12:10]}};
        tmp_7_reg_866 <= {{grp_fu_149_p2[38:20]}};
        tmp_9_reg_871 <= {{grp_fu_154_p2[38:20]}};
        tmp_s_reg_881 <= {{grp_fu_159_p2[38:20]}};
        trunc_ln1_reg_851 <= {{grp_fu_264_p2[35:20]}};
        trunc_ln2_reg_856 <= {{grp_fu_270_p2[35:20]}};
        trunc_ln3_reg_861 <= {{grp_fu_224_p2[32:20]}};
        trunc_ln4_reg_836 <= {{grp_fu_230_p2[33:20]}};
        trunc_ln5_reg_841 <= {{grp_fu_239_p2[35:20]}};
        trunc_ln_reg_846 <= {{grp_fu_164_p2[38:20]}};
        value_b_reg_896 <= value_b_fu_610_p3;
        value_g_reg_891 <= value_g_fu_536_p3;
        value_r_reg_886 <= value_r_fu_453_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        b_reg_788 <= {{ltm_in_data_dout[29:20]}};
        g_reg_782 <= {{ltm_in_data_dout[19:10]}};
        r_reg_775 <= r_fu_194_p1;
    end
end

always @ (*) begin
    if (((icmp_ln246_fu_177_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_126;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_149_ce = 1'b1;
    end else begin
        grp_fu_149_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_154_ce = 1'b1;
    end else begin
        grp_fu_154_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_159_ce = 1'b1;
    end else begin
        grp_fu_159_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_164_ce = 1'b1;
    end else begin
        grp_fu_164_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_224_ce = 1'b1;
    end else begin
        grp_fu_224_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_230_ce = 1'b1;
    end else begin
        grp_fu_230_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_239_ce = 1'b1;
    end else begin
        grp_fu_239_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_264_ce = 1'b1;
    end else begin
        grp_fu_264_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_270_ce = 1'b1;
    end else begin
        grp_fu_270_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        lsc_out_data_blk_n = lsc_out_data_full_n;
    end else begin
        lsc_out_data_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        lsc_out_data_write = 1'b1;
    end else begin
        lsc_out_data_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ltm_in_data_blk_n = ltm_in_data_empty_n;
    end else begin
        ltm_in_data_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ltm_in_data_read = 1'b1;
    end else begin
        ltm_in_data_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln276_1_fu_393_p2 = ($signed(add_ln276_fu_384_p2) + $signed(sext_ln276_1_fu_390_p1));

assign add_ln276_2_fu_439_p2 = ($signed(sext_ln276_2_fu_409_p1) + $signed(14'd1));

assign add_ln276_fu_384_p2 = ($signed(zext_ln276_fu_378_p1) + $signed(sext_ln276_fu_381_p1));

assign add_ln277_1_fu_476_p2 = ($signed(add_ln277_fu_467_p2) + $signed(sext_ln277_1_fu_473_p1));

assign add_ln277_2_fu_522_p2 = ($signed(sext_ln277_2_fu_492_p1) + $signed(13'd1));

assign add_ln277_fu_467_p2 = ($signed(zext_ln277_fu_464_p1) + $signed(sext_ln277_fu_461_p1));

assign add_ln278_1_fu_550_p2 = ($signed(zext_ln278_fu_547_p1) + $signed(sext_ln278_2_fu_544_p1));

assign add_ln278_2_fu_596_p2 = ($signed(sext_ln278_3_fu_566_p1) + $signed(13'd1));

assign add_ln278_fu_362_p2 = ($signed(sext_ln278_1_fu_359_p1) + $signed(sext_ln278_fu_356_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (ltm_in_data_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter8 = (lsc_out_data_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_149_p0 = grp_fu_149_p00;

assign grp_fu_149_p00 = r_reg_775_pp0_iter3_reg;

assign grp_fu_149_p1 = 39'd445737074;

assign grp_fu_154_p0 = zext_ln265_1_fu_252_p1;

assign grp_fu_154_p1 = 39'd304110528;

assign grp_fu_159_p0 = grp_fu_159_p00;

assign grp_fu_159_p00 = b_reg_788_pp0_iter3_reg;

assign grp_fu_159_p1 = 39'd300298744;

assign grp_fu_164_p0 = zext_ln265_1_fu_252_p1;

assign grp_fu_164_p1 = 39'd549598081214;

assign grp_fu_224_p0 = grp_fu_224_p00;

assign grp_fu_224_p00 = b_reg_788;

assign grp_fu_224_p1 = 33'd8587706577;

assign grp_fu_230_p0 = grp_fu_230_p00;

assign grp_fu_230_p00 = r_reg_775;

assign grp_fu_230_p1 = 34'd17174983658;

assign grp_fu_239_p0 = grp_fu_239_p00;

assign grp_fu_239_p00 = g_reg_782_pp0_iter2_reg;

assign grp_fu_239_p1 = 36'd68692472129;

assign grp_fu_264_p0 = grp_fu_264_p00;

assign grp_fu_264_p00 = b_reg_788_pp0_iter3_reg;

assign grp_fu_264_p1 = 36'd68699934634;

assign grp_fu_270_p0 = grp_fu_270_p00;

assign grp_fu_270_p00 = r_reg_775_pp0_iter3_reg;

assign grp_fu_270_p1 = 36'd68686029678;

assign icmp_ln246_fu_177_p2 = ((ap_sig_allocacmp_j_1 == width) ? 1'b1 : 1'b0);

assign icmp_ln276_fu_433_p2 = ((tmp_1_fu_425_p3 == 28'd0) ? 1'b1 : 1'b0);

assign icmp_ln277_fu_516_p2 = ((tmp_3_fu_508_p3 == 28'd0) ? 1'b1 : 1'b0);

assign icmp_ln278_fu_590_p2 = ((tmp_5_fu_582_p3 == 28'd0) ? 1'b1 : 1'b0);

assign icmp_ln97_1_fu_684_p2 = (($signed(tmp_13_reg_906) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln97_2_fu_720_p2 = (($signed(tmp_15_reg_911) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_648_p2 = (($signed(tmp_11_reg_901) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign j_2_fu_183_p2 = (ap_sig_allocacmp_j_1 + 11'd1);

assign lsc_out_data_din = {{{select_ln99_2_reg_926}, {select_ln99_1_reg_921}}, {select_ln99_reg_916}};

assign r_fu_194_p1 = ltm_in_data_dout[9:0];

assign select_ln276_fu_445_p3 = ((icmp_ln276_fu_433_p2[0:0] == 1'b1) ? sext_ln276_2_fu_409_p1 : add_ln276_2_fu_439_p2);

assign select_ln277_fu_528_p3 = ((icmp_ln277_fu_516_p2[0:0] == 1'b1) ? sext_ln277_2_fu_492_p1 : add_ln277_2_fu_522_p2);

assign select_ln278_fu_602_p3 = ((icmp_ln278_fu_590_p2[0:0] == 1'b1) ? sext_ln278_3_fu_566_p1 : add_ln278_2_fu_596_p2);

assign select_ln97_1_fu_689_p3 = ((icmp_ln97_1_fu_684_p2[0:0] == 1'b1) ? 13'd1023 : value_g_reg_891);

assign select_ln97_2_fu_725_p3 = ((icmp_ln97_2_fu_720_p2[0:0] == 1'b1) ? 13'd1023 : value_b_reg_896);

assign select_ln97_fu_653_p3 = ((icmp_ln97_fu_648_p2[0:0] == 1'b1) ? 14'd1023 : value_r_reg_886);

assign select_ln99_1_fu_712_p3 = ((tmp_14_fu_700_p3[0:0] == 1'b1) ? 10'd0 : trunc_ln99_1_fu_708_p1);

assign select_ln99_2_fu_748_p3 = ((tmp_16_fu_736_p3[0:0] == 1'b1) ? 10'd0 : trunc_ln99_2_fu_744_p1);

assign select_ln99_fu_676_p3 = ((tmp_12_fu_664_p3[0:0] == 1'b1) ? 10'd0 : trunc_ln99_fu_672_p1);

assign sext_ln276_1_fu_390_p1 = $signed(trunc_ln1_reg_851);

assign sext_ln276_2_fu_409_p1 = $signed(tmp_2_fu_399_p4);

assign sext_ln276_fu_381_p1 = $signed(trunc_ln_reg_846);

assign sext_ln277_1_fu_473_p1 = $signed(trunc_ln3_reg_861);

assign sext_ln277_2_fu_492_p1 = $signed(tmp_4_fu_482_p4);

assign sext_ln277_fu_461_p1 = $signed(trunc_ln2_reg_856);

assign sext_ln278_1_fu_359_p1 = $signed(trunc_ln5_reg_841);

assign sext_ln278_2_fu_544_p1 = $signed(add_ln278_reg_876);

assign sext_ln278_3_fu_566_p1 = $signed(tmp_6_fu_556_p4);

assign sext_ln278_fu_356_p1 = $signed(trunc_ln4_reg_836);

assign sext_ln96_1_fu_696_p1 = select_ln97_1_fu_689_p3;

assign sext_ln96_2_fu_732_p1 = select_ln97_2_fu_725_p3;

assign sext_ln96_fu_660_p1 = select_ln97_fu_653_p3;

assign tmp_10_fu_570_p3 = add_ln278_1_fu_550_p2[32'd19];

assign tmp_12_fu_664_p3 = sext_ln96_fu_660_p1[32'd15];

assign tmp_14_fu_700_p3 = sext_ln96_1_fu_696_p1[32'd15];

assign tmp_16_fu_736_p3 = sext_ln96_2_fu_732_p1[32'd15];

assign tmp_1_fu_425_p3 = {{trunc_ln276_fu_421_p1}, {20'd0}};

assign tmp_2_fu_399_p4 = {{add_ln276_1_fu_393_p2[20:8]}};

assign tmp_3_fu_508_p3 = {{trunc_ln277_fu_504_p1}, {20'd0}};

assign tmp_4_fu_482_p4 = {{add_ln277_1_fu_476_p2[19:8]}};

assign tmp_5_fu_582_p3 = {{trunc_ln278_fu_578_p1}, {20'd0}};

assign tmp_6_fu_556_p4 = {{add_ln278_1_fu_550_p2[19:8]}};

assign tmp_8_fu_496_p3 = add_ln277_1_fu_476_p2[32'd19];

assign tmp_fu_413_p3 = add_ln276_1_fu_393_p2[32'd20];

assign trunc_ln276_fu_421_p1 = add_ln276_1_fu_393_p2[7:0];

assign trunc_ln277_fu_504_p1 = add_ln277_1_fu_476_p2[7:0];

assign trunc_ln278_fu_578_p1 = add_ln278_1_fu_550_p2[7:0];

assign trunc_ln99_1_fu_708_p1 = select_ln97_1_fu_689_p3[9:0];

assign trunc_ln99_2_fu_744_p1 = select_ln97_2_fu_725_p3[9:0];

assign trunc_ln99_fu_672_p1 = select_ln97_fu_653_p3[9:0];

assign value_b_fu_610_p3 = ((tmp_10_fu_570_p3[0:0] == 1'b1) ? select_ln278_fu_602_p3 : sext_ln278_3_fu_566_p1);

assign value_g_fu_536_p3 = ((tmp_8_fu_496_p3[0:0] == 1'b1) ? select_ln277_fu_528_p3 : sext_ln277_2_fu_492_p1);

assign value_r_fu_453_p3 = ((tmp_fu_413_p3[0:0] == 1'b1) ? select_ln276_fu_445_p3 : sext_ln276_2_fu_409_p1);

assign zext_ln265_1_fu_252_p1 = g_reg_782_pp0_iter3_reg;

assign zext_ln276_fu_378_p1 = tmp_7_reg_866;

assign zext_ln277_fu_464_p1 = tmp_9_reg_871;

assign zext_ln278_fu_547_p1 = tmp_s_reg_881;

endmodule //ISPPipeline_accel_xfccmkernel_20_1080_1920_22_1_2_2_13_13_1920_Pipeline_colLoop
