// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ISPPipeline_accel_xf_QuatizationDithering_20_16_1080_1920_256_1024_1_0_2_2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        lsc_out_data_dout,
        lsc_out_data_num_data_valid,
        lsc_out_data_fifo_cap,
        lsc_out_data_empty_n,
        lsc_out_data_read,
        aecin_data_din,
        aecin_data_num_data_valid,
        aecin_data_fifo_cap,
        aecin_data_full_n,
        aecin_data_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [29:0] lsc_out_data_dout;
input  [2:0] lsc_out_data_num_data_valid;
input  [2:0] lsc_out_data_fifo_cap;
input   lsc_out_data_empty_n;
output   lsc_out_data_read;
output  [23:0] aecin_data_din;
input  [2:0] aecin_data_num_data_valid;
input  [2:0] aecin_data_fifo_cap;
input   aecin_data_full_n;
output   aecin_data_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg lsc_out_data_read;
reg aecin_data_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1;
wire    ap_CS_fsm_state3;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_done;
wire  signed [15:0] in_col_loop_bound_fu_105_p2;
reg   [15:0] in_col_loop_bound_reg_145;
wire   [16:0] sub146_fu_113_p2;
reg   [16:0] sub146_reg_152;
wire    ap_CS_fsm_state4;
wire   [31:0] bound_fu_126_p2;
reg   [31:0] bound_reg_157;
reg    offset_buffer_ce0;
wire   [8:0] offset_buffer_q0;
reg   [9:0] offset_buffer_address1;
reg    offset_buffer_ce1;
reg    offset_buffer_we1;
reg   [8:0] offset_buffer_d1;
reg    offset_buffer_1_ce0;
wire   [8:0] offset_buffer_1_q0;
reg   [9:0] offset_buffer_1_address1;
reg    offset_buffer_1_ce1;
reg    offset_buffer_1_we1;
reg   [8:0] offset_buffer_1_d1;
reg    offset_buffer_2_ce0;
wire   [8:0] offset_buffer_2_q0;
reg   [9:0] offset_buffer_2_address1;
reg    offset_buffer_2_ce1;
reg    offset_buffer_2_we1;
reg   [8:0] offset_buffer_2_d1;
reg    offset_buffer_3_ce0;
wire   [8:0] offset_buffer_3_q0;
reg   [9:0] offset_buffer_3_address1;
reg    offset_buffer_3_ce1;
reg    offset_buffer_3_we1;
reg   [8:0] offset_buffer_3_d1;
reg    offset_buffer_4_ce0;
wire   [8:0] offset_buffer_4_q0;
reg   [9:0] offset_buffer_4_address1;
reg    offset_buffer_4_ce1;
reg    offset_buffer_4_we1;
reg   [8:0] offset_buffer_4_d1;
reg    offset_buffer_5_ce0;
wire   [8:0] offset_buffer_5_q0;
reg   [9:0] offset_buffer_5_address1;
reg    offset_buffer_5_ce1;
reg    offset_buffer_5_we1;
reg   [8:0] offset_buffer_5_d1;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_start;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_idle;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_ready;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_5_address1;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_5_ce1;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_5_we1;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_5_d1;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_4_address1;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_4_ce1;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_4_we1;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_4_d1;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_3_address1;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_3_ce1;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_3_we1;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_3_d1;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_2_address1;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_2_ce1;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_2_we1;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_2_d1;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_1_address1;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_1_ce1;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_1_we1;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_1_d1;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_address1;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_ce1;
wire    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_we1;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_d1;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_start;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_done;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_idle;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_ready;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_lsc_out_data_read;
wire   [23:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_aecin_data_din;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_aecin_data_write;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_address0;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_ce0;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_address1;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_ce1;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_we1;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_d1;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_address0;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_ce0;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_address1;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_ce1;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_we1;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_d1;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_address0;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_ce0;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_address1;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_ce1;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_we1;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_d1;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_address0;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_ce0;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_address1;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_ce1;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_we1;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_d1;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_address0;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_ce0;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_address1;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_ce1;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_we1;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_d1;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_address0;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_ce0;
wire   [9:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_address1;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_ce1;
wire    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_we1;
wire   [8:0] grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_d1;
reg    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_start_reg;
wire    ap_CS_fsm_state5;
wire  signed [16:0] in_col_loop_bound_cast_fu_110_p1;
wire   [15:0] bound_fu_126_p0;
wire   [15:0] bound_fu_126_p1;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire   [31:0] bound_fu_126_p00;
wire   [31:0] bound_fu_126_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_start_reg = 1'b0;
#0 grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_start_reg = 1'b0;
end

ISPPipeline_accel_xf_QuatizationDithering_20_16_1080_1920_256_1024_1_0_2_2_s_offset_buffer_RAM_eOg #(
    .DataWidth( 9 ),
    .AddressRange( 960 ),
    .AddressWidth( 10 ))
offset_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_address0),
    .ce0(offset_buffer_ce0),
    .q0(offset_buffer_q0),
    .address1(offset_buffer_address1),
    .ce1(offset_buffer_ce1),
    .we1(offset_buffer_we1),
    .d1(offset_buffer_d1)
);

ISPPipeline_accel_xf_QuatizationDithering_20_16_1080_1920_256_1024_1_0_2_2_s_offset_buffer_RAM_eOg #(
    .DataWidth( 9 ),
    .AddressRange( 960 ),
    .AddressWidth( 10 ))
offset_buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_address0),
    .ce0(offset_buffer_1_ce0),
    .q0(offset_buffer_1_q0),
    .address1(offset_buffer_1_address1),
    .ce1(offset_buffer_1_ce1),
    .we1(offset_buffer_1_we1),
    .d1(offset_buffer_1_d1)
);

ISPPipeline_accel_xf_QuatizationDithering_20_16_1080_1920_256_1024_1_0_2_2_s_offset_buffer_RAM_eOg #(
    .DataWidth( 9 ),
    .AddressRange( 960 ),
    .AddressWidth( 10 ))
offset_buffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_address0),
    .ce0(offset_buffer_2_ce0),
    .q0(offset_buffer_2_q0),
    .address1(offset_buffer_2_address1),
    .ce1(offset_buffer_2_ce1),
    .we1(offset_buffer_2_we1),
    .d1(offset_buffer_2_d1)
);

ISPPipeline_accel_xf_QuatizationDithering_20_16_1080_1920_256_1024_1_0_2_2_s_offset_buffer_RAM_eOg #(
    .DataWidth( 9 ),
    .AddressRange( 960 ),
    .AddressWidth( 10 ))
offset_buffer_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_address0),
    .ce0(offset_buffer_3_ce0),
    .q0(offset_buffer_3_q0),
    .address1(offset_buffer_3_address1),
    .ce1(offset_buffer_3_ce1),
    .we1(offset_buffer_3_we1),
    .d1(offset_buffer_3_d1)
);

ISPPipeline_accel_xf_QuatizationDithering_20_16_1080_1920_256_1024_1_0_2_2_s_offset_buffer_RAM_eOg #(
    .DataWidth( 9 ),
    .AddressRange( 960 ),
    .AddressWidth( 10 ))
offset_buffer_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_address0),
    .ce0(offset_buffer_4_ce0),
    .q0(offset_buffer_4_q0),
    .address1(offset_buffer_4_address1),
    .ce1(offset_buffer_4_ce1),
    .we1(offset_buffer_4_we1),
    .d1(offset_buffer_4_d1)
);

ISPPipeline_accel_xf_QuatizationDithering_20_16_1080_1920_256_1024_1_0_2_2_s_offset_buffer_RAM_eOg #(
    .DataWidth( 9 ),
    .AddressRange( 960 ),
    .AddressWidth( 10 ))
offset_buffer_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_address0),
    .ce0(offset_buffer_5_ce0),
    .q0(offset_buffer_5_q0),
    .address1(offset_buffer_5_address1),
    .ce1(offset_buffer_5_ce1),
    .we1(offset_buffer_5_we1),
    .d1(offset_buffer_5_d1)
);

ISPPipeline_accel_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1 grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_start),
    .ap_done(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_done),
    .ap_idle(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_idle),
    .ap_ready(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_ready),
    .p_read1(p_read1),
    .offset_buffer_5_address1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_5_address1),
    .offset_buffer_5_ce1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_5_ce1),
    .offset_buffer_5_we1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_5_we1),
    .offset_buffer_5_d1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_5_d1),
    .offset_buffer_4_address1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_4_address1),
    .offset_buffer_4_ce1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_4_ce1),
    .offset_buffer_4_we1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_4_we1),
    .offset_buffer_4_d1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_4_d1),
    .offset_buffer_3_address1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_3_address1),
    .offset_buffer_3_ce1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_3_ce1),
    .offset_buffer_3_we1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_3_we1),
    .offset_buffer_3_d1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_3_d1),
    .offset_buffer_2_address1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_2_address1),
    .offset_buffer_2_ce1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_2_ce1),
    .offset_buffer_2_we1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_2_we1),
    .offset_buffer_2_d1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_2_d1),
    .offset_buffer_1_address1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_1_address1),
    .offset_buffer_1_ce1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_1_ce1),
    .offset_buffer_1_we1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_1_we1),
    .offset_buffer_1_d1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_1_d1),
    .offset_buffer_address1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_address1),
    .offset_buffer_ce1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_ce1),
    .offset_buffer_we1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_we1),
    .offset_buffer_d1(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_d1)
);

ISPPipeline_accel_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_start),
    .ap_done(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_done),
    .ap_idle(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_idle),
    .ap_ready(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_ready),
    .lsc_out_data_dout(lsc_out_data_dout),
    .lsc_out_data_num_data_valid(3'd0),
    .lsc_out_data_fifo_cap(3'd0),
    .lsc_out_data_empty_n(lsc_out_data_empty_n),
    .lsc_out_data_read(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_lsc_out_data_read),
    .aecin_data_din(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_aecin_data_din),
    .aecin_data_num_data_valid(3'd0),
    .aecin_data_fifo_cap(3'd0),
    .aecin_data_full_n(aecin_data_full_n),
    .aecin_data_write(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_aecin_data_write),
    .in_col_loop_bound(in_col_loop_bound_reg_145),
    .bound(bound_reg_157),
    .sub146(sub146_reg_152),
    .offset_buffer_address0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_address0),
    .offset_buffer_ce0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_ce0),
    .offset_buffer_q0(offset_buffer_q0),
    .offset_buffer_address1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_address1),
    .offset_buffer_ce1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_ce1),
    .offset_buffer_we1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_we1),
    .offset_buffer_d1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_d1),
    .offset_buffer_1_address0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_address0),
    .offset_buffer_1_ce0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_ce0),
    .offset_buffer_1_q0(offset_buffer_1_q0),
    .offset_buffer_1_address1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_address1),
    .offset_buffer_1_ce1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_ce1),
    .offset_buffer_1_we1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_we1),
    .offset_buffer_1_d1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_d1),
    .offset_buffer_2_address0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_address0),
    .offset_buffer_2_ce0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_ce0),
    .offset_buffer_2_q0(offset_buffer_2_q0),
    .offset_buffer_2_address1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_address1),
    .offset_buffer_2_ce1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_ce1),
    .offset_buffer_2_we1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_we1),
    .offset_buffer_2_d1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_d1),
    .offset_buffer_3_address0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_address0),
    .offset_buffer_3_ce0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_ce0),
    .offset_buffer_3_q0(offset_buffer_3_q0),
    .offset_buffer_3_address1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_address1),
    .offset_buffer_3_ce1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_ce1),
    .offset_buffer_3_we1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_we1),
    .offset_buffer_3_d1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_d1),
    .offset_buffer_4_address0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_address0),
    .offset_buffer_4_ce0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_ce0),
    .offset_buffer_4_q0(offset_buffer_4_q0),
    .offset_buffer_4_address1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_address1),
    .offset_buffer_4_ce1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_ce1),
    .offset_buffer_4_we1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_we1),
    .offset_buffer_4_d1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_d1),
    .offset_buffer_5_address0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_address0),
    .offset_buffer_5_ce0(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_ce0),
    .offset_buffer_5_q0(offset_buffer_5_q0),
    .offset_buffer_5_address1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_address1),
    .offset_buffer_5_ce1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_ce1),
    .offset_buffer_5_we1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_we1),
    .offset_buffer_5_d1(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_d1),
    .p_read1(p_read1)
);

ISPPipeline_accel_mul_16ns_16ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16ns_16ns_32_1_1_U395(
    .din0(bound_fu_126_p0),
    .din1(bound_fu_126_p1),
    .dout(bound_fu_126_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_start_reg <= 1'b1;
        end else if ((grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_ready == 1'b1)) begin
            grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_start_reg <= 1'b1;
        end else if ((grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_ready == 1'b1)) begin
            grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bound_reg_157 <= bound_fu_126_p2;
        sub146_reg_152 <= sub146_fu_113_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        in_col_loop_bound_reg_145 <= in_col_loop_bound_fu_105_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        aecin_data_write = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_aecin_data_write;
    end else begin
        aecin_data_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        lsc_out_data_read = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_lsc_out_data_read;
    end else begin
        lsc_out_data_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_1_address1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_1_address1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_1_address1;
    end else begin
        offset_buffer_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_1_ce0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_ce0;
    end else begin
        offset_buffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_1_ce1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_1_ce1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_1_ce1;
    end else begin
        offset_buffer_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_1_d1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_d1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_1_d1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_1_d1;
    end else begin
        offset_buffer_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_1_we1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_1_we1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_1_we1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_1_we1;
    end else begin
        offset_buffer_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_2_address1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_2_address1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_2_address1;
    end else begin
        offset_buffer_2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_2_ce0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_ce0;
    end else begin
        offset_buffer_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_2_ce1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_2_ce1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_2_ce1;
    end else begin
        offset_buffer_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_2_d1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_d1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_2_d1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_2_d1;
    end else begin
        offset_buffer_2_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_2_we1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_2_we1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_2_we1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_2_we1;
    end else begin
        offset_buffer_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_3_address1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_3_address1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_3_address1;
    end else begin
        offset_buffer_3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_3_ce0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_ce0;
    end else begin
        offset_buffer_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_3_ce1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_3_ce1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_3_ce1;
    end else begin
        offset_buffer_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_3_d1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_d1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_3_d1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_3_d1;
    end else begin
        offset_buffer_3_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_3_we1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_3_we1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_3_we1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_3_we1;
    end else begin
        offset_buffer_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_4_address1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_4_address1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_4_address1;
    end else begin
        offset_buffer_4_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_4_ce0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_ce0;
    end else begin
        offset_buffer_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_4_ce1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_4_ce1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_4_ce1;
    end else begin
        offset_buffer_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_4_d1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_d1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_4_d1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_4_d1;
    end else begin
        offset_buffer_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_4_we1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_4_we1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_4_we1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_4_we1;
    end else begin
        offset_buffer_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_5_address1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_5_address1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_5_address1;
    end else begin
        offset_buffer_5_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_5_ce0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_ce0;
    end else begin
        offset_buffer_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_5_ce1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_5_ce1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_5_ce1;
    end else begin
        offset_buffer_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_5_d1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_d1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_5_d1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_5_d1;
    end else begin
        offset_buffer_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_5_we1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_5_we1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_5_we1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_5_we1;
    end else begin
        offset_buffer_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_address1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_address1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_address1;
    end else begin
        offset_buffer_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_ce0 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_ce0;
    end else begin
        offset_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_ce1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_ce1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_ce1;
    end else begin
        offset_buffer_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_d1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_d1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_d1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_d1;
    end else begin
        offset_buffer_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        offset_buffer_we1 = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_offset_buffer_we1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        offset_buffer_we1 = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_offset_buffer_we1;
    end else begin
        offset_buffer_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign aecin_data_din = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_aecin_data_din;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign bound_fu_126_p0 = bound_fu_126_p00;

assign bound_fu_126_p00 = p_read;

assign bound_fu_126_p1 = bound_fu_126_p10;

assign bound_fu_126_p10 = in_col_loop_bound_reg_145;

assign grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_start = grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_87_ap_start_reg;

assign grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_start = grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_130_1_fu_76_ap_start_reg;

assign in_col_loop_bound_cast_fu_110_p1 = $signed(in_col_loop_bound_reg_145);

assign in_col_loop_bound_fu_105_p2 = (p_read1 + 16'd1);

assign sub146_fu_113_p2 = ($signed(in_col_loop_bound_cast_fu_110_p1) + $signed(17'd131071));

endmodule //ISPPipeline_accel_xf_QuatizationDithering_20_16_1080_1920_256_1024_1_0_2_2_s
