# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_4/bd_41e7_rst_axis_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_41e7_rst_axis_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_4/bd_41e7_rst_axis_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_41e7_rst_axis_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_4/bd_41e7_rst_axis_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_41e7_rst_axis_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_4/bd_41e7_rst_axis_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_41e7_rst_axis_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_4/bd_41e7_rst_axis_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_41e7_rst_axis_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_4/bd_41e7_rst_axis_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_41e7_rst_axis_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
