-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity clahe_accel_process_r is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    imgOutput_data_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    imgOutput_data_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    imgOutput_data_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    imgOutput_data_full_n : IN STD_LOGIC;
    imgOutput_data_write : OUT STD_LOGIC;
    imgInput_data_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    imgInput_data_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    imgInput_data_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    imgInput_data_empty_n : IN STD_LOGIC;
    imgInput_data_read : OUT STD_LOGIC;
    p_lutw_0_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    p_lutw_0_ce0 : OUT STD_LOGIC;
    p_lutw_0_we0 : OUT STD_LOGIC;
    p_lutw_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_lutw_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_lutw_0_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    p_lutw_0_ce1 : OUT STD_LOGIC;
    p_lutw_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_lutw_1_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    p_lutw_1_ce0 : OUT STD_LOGIC;
    p_lutw_1_we0 : OUT STD_LOGIC;
    p_lutw_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_lutw_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_lutw_1_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    p_lutw_1_ce1 : OUT STD_LOGIC;
    p_lutw_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_lutr_0_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    p_lutr_0_ce0 : OUT STD_LOGIC;
    p_lutr_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_lutr_0_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    p_lutr_0_ce1 : OUT STD_LOGIC;
    p_lutr_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_lutr_1_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    p_lutr_1_ce0 : OUT STD_LOGIC;
    p_lutr_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_lutr_1_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    p_lutr_1_ce1 : OUT STD_LOGIC;
    p_lutr_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    height : IN STD_LOGIC_VECTOR (10 downto 0);
    width : IN STD_LOGIC_VECTOR (10 downto 0);
    clip : IN STD_LOGIC_VECTOR (31 downto 0);
    tilesY : IN STD_LOGIC_VECTOR (31 downto 0);
    tilesX : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of clahe_accel_process_r is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (24 downto 0) := "0000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (24 downto 0) := "0000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (24 downto 0) := "0000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (24 downto 0) := "0000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (24 downto 0) := "0000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (24 downto 0) := "0000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (24 downto 0) := "0001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (24 downto 0) := "0010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (24 downto 0) := "0100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (24 downto 0) := "1000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv24_1 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000001";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv19_1 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000001";
    constant ap_const_lv19_7FFFF : STD_LOGIC_VECTOR (18 downto 0) := "1111111111111111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal width_cast_fu_125_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal width_cast_reg_270 : STD_LOGIC_VECTOR (31 downto 0);
    signal height_cast_fu_129_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal height_cast_reg_276 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_133_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal Tile_mTileHeight_reg_282 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal trunc_ln445_fu_145_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln445_reg_287 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_139_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal Tile_mTileWidth_reg_293 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln445_1_fu_149_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln445_1_reg_298 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_117_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln78_reg_304 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal grp_fu_121_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln80_reg_309 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal Tile_mTileHeight_1_fu_162_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal Tile_mTileHeight_1_reg_319 : STD_LOGIC_VECTOR (12 downto 0);
    signal Tile_mTileWidth_3_fu_178_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal Tile_mTileWidth_3_reg_325 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln85_fu_185_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln85_reg_331 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln86_fu_197_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln86_reg_336 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal grp_fu_113_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln86_1_reg_346 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal trunc_ln86_1_reg_351 : STD_LOGIC_VECTOR (23 downto 0);
    signal Tile_mClipValue_1_fu_239_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal Tile_mClipValue_1_reg_356 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal grp_process_i_fu_88_imgOutput_data_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_i_fu_88_imgOutput_data_write : STD_LOGIC;
    signal grp_process_i_fu_88_imgInput_data_read : STD_LOGIC;
    signal grp_process_i_fu_88_p_lutw_0_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_process_i_fu_88_p_lutw_0_ce0 : STD_LOGIC;
    signal grp_process_i_fu_88_p_lutw_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_process_i_fu_88_p_lutw_0_we0 : STD_LOGIC;
    signal grp_process_i_fu_88_p_lutw_0_address1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_process_i_fu_88_p_lutw_0_ce1 : STD_LOGIC;
    signal grp_process_i_fu_88_p_lutw_0_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_process_i_fu_88_p_lutw_0_we1 : STD_LOGIC;
    signal grp_process_i_fu_88_p_lutw_1_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_process_i_fu_88_p_lutw_1_ce0 : STD_LOGIC;
    signal grp_process_i_fu_88_p_lutw_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_process_i_fu_88_p_lutw_1_we0 : STD_LOGIC;
    signal grp_process_i_fu_88_p_lutw_1_address1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_process_i_fu_88_p_lutw_1_ce1 : STD_LOGIC;
    signal grp_process_i_fu_88_p_lutw_1_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_process_i_fu_88_p_lutw_1_we1 : STD_LOGIC;
    signal grp_process_i_fu_88_p_lutr_0_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_process_i_fu_88_p_lutr_0_ce0 : STD_LOGIC;
    signal grp_process_i_fu_88_p_lutr_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_process_i_fu_88_p_lutr_0_we0 : STD_LOGIC;
    signal grp_process_i_fu_88_p_lutr_0_address1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_process_i_fu_88_p_lutr_0_ce1 : STD_LOGIC;
    signal grp_process_i_fu_88_p_lutr_0_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_process_i_fu_88_p_lutr_0_we1 : STD_LOGIC;
    signal grp_process_i_fu_88_p_lutr_1_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_process_i_fu_88_p_lutr_1_ce0 : STD_LOGIC;
    signal grp_process_i_fu_88_p_lutr_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_process_i_fu_88_p_lutr_1_we0 : STD_LOGIC;
    signal grp_process_i_fu_88_p_lutr_1_address1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_process_i_fu_88_p_lutr_1_ce1 : STD_LOGIC;
    signal grp_process_i_fu_88_p_lutr_1_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_process_i_fu_88_p_lutr_1_we1 : STD_LOGIC;
    signal grp_process_i_fu_88_ap_start : STD_LOGIC;
    signal grp_process_i_fu_88_ap_done : STD_LOGIC;
    signal grp_process_i_fu_88_ap_ready : STD_LOGIC;
    signal grp_process_i_fu_88_ap_idle : STD_LOGIC;
    signal grp_process_i_fu_88_ap_continue : STD_LOGIC;
    signal grp_process_i_fu_88_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal ap_sync_grp_process_i_fu_88_ap_ready : STD_LOGIC;
    signal ap_sync_grp_process_i_fu_88_ap_done : STD_LOGIC;
    signal ap_block_state25_on_subcall_done : BOOLEAN;
    signal ap_sync_reg_grp_process_i_fu_88_ap_ready : STD_LOGIC := '0';
    signal ap_sync_reg_grp_process_i_fu_88_ap_done : STD_LOGIC := '0';
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal grp_fu_133_p0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_139_p0 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln78_fu_153_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln78_fu_157_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln80_fu_169_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Tile_mTileWidth_1_fu_173_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln85_fu_185_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln224_fu_217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1_fu_222_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal Tile_mClipValue_fu_231_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_133_ap_start : STD_LOGIC;
    signal grp_fu_133_ap_done : STD_LOGIC;
    signal grp_fu_133_ce : STD_LOGIC;
    signal grp_fu_139_ap_start : STD_LOGIC;
    signal grp_fu_139_ap_done : STD_LOGIC;
    signal grp_fu_139_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal grp_fu_133_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_139_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component clahe_accel_process_i IS
    port (
        imgOutput_data_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        imgOutput_data_full_n : IN STD_LOGIC;
        imgOutput_data_write : OUT STD_LOGIC;
        imgInput_data_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        imgInput_data_empty_n : IN STD_LOGIC;
        imgInput_data_read : OUT STD_LOGIC;
        Tile_0_val3 : IN STD_LOGIC_VECTOR (10 downto 0);
        Tile_2_val5 : IN STD_LOGIC_VECTOR (10 downto 0);
        Tile_3_val6 : IN STD_LOGIC_VECTOR (31 downto 0);
        Tile_4_val7 : IN STD_LOGIC_VECTOR (31 downto 0);
        Tile_5_val9 : IN STD_LOGIC_VECTOR (12 downto 0);
        Tile_6_val11 : IN STD_LOGIC_VECTOR (12 downto 0);
        Tile_8_val14 : IN STD_LOGIC_VECTOR (18 downto 0);
        p_lutw_0_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        p_lutw_0_ce0 : OUT STD_LOGIC;
        p_lutw_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_lutw_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_lutw_0_we0 : OUT STD_LOGIC;
        p_lutw_0_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
        p_lutw_0_ce1 : OUT STD_LOGIC;
        p_lutw_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_lutw_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_lutw_0_we1 : OUT STD_LOGIC;
        p_lutw_1_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        p_lutw_1_ce0 : OUT STD_LOGIC;
        p_lutw_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_lutw_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_lutw_1_we0 : OUT STD_LOGIC;
        p_lutw_1_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
        p_lutw_1_ce1 : OUT STD_LOGIC;
        p_lutw_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_lutw_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_lutw_1_we1 : OUT STD_LOGIC;
        p_lutr_0_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        p_lutr_0_ce0 : OUT STD_LOGIC;
        p_lutr_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_lutr_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_lutr_0_we0 : OUT STD_LOGIC;
        p_lutr_0_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
        p_lutr_0_ce1 : OUT STD_LOGIC;
        p_lutr_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_lutr_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_lutr_0_we1 : OUT STD_LOGIC;
        p_lutr_1_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        p_lutr_1_ce0 : OUT STD_LOGIC;
        p_lutr_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_lutr_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_lutr_1_we0 : OUT STD_LOGIC;
        p_lutr_1_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
        p_lutr_1_ce1 : OUT STD_LOGIC;
        p_lutr_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_lutr_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_lutr_1_we1 : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        Tile_0_val3_ap_vld : IN STD_LOGIC;
        Tile_2_val5_ap_vld : IN STD_LOGIC;
        Tile_5_val9_ap_vld : IN STD_LOGIC;
        Tile_6_val11_ap_vld : IN STD_LOGIC;
        Tile_8_val14_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        Tile_3_val6_ap_vld : IN STD_LOGIC;
        Tile_4_val7_ap_vld : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component clahe_accel_mul_26s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (25 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component clahe_accel_mul_32s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component clahe_accel_sdiv_12ns_32s_32_16_seq_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        start : IN STD_LOGIC;
        done : OUT STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (11 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component clahe_accel_mul_13s_13s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (12 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;



begin
    grp_process_i_fu_88 : component clahe_accel_process_i
    port map (
        imgOutput_data_din => grp_process_i_fu_88_imgOutput_data_din,
        imgOutput_data_full_n => imgOutput_data_full_n,
        imgOutput_data_write => grp_process_i_fu_88_imgOutput_data_write,
        imgInput_data_dout => imgInput_data_dout,
        imgInput_data_empty_n => imgInput_data_empty_n,
        imgInput_data_read => grp_process_i_fu_88_imgInput_data_read,
        Tile_0_val3 => height,
        Tile_2_val5 => width,
        Tile_3_val6 => tilesY,
        Tile_4_val7 => tilesX,
        Tile_5_val9 => Tile_mTileHeight_1_reg_319,
        Tile_6_val11 => Tile_mTileWidth_3_reg_325,
        Tile_8_val14 => Tile_mClipValue_1_reg_356,
        p_lutw_0_address0 => grp_process_i_fu_88_p_lutw_0_address0,
        p_lutw_0_ce0 => grp_process_i_fu_88_p_lutw_0_ce0,
        p_lutw_0_d0 => grp_process_i_fu_88_p_lutw_0_d0,
        p_lutw_0_q0 => p_lutw_0_q0,
        p_lutw_0_we0 => grp_process_i_fu_88_p_lutw_0_we0,
        p_lutw_0_address1 => grp_process_i_fu_88_p_lutw_0_address1,
        p_lutw_0_ce1 => grp_process_i_fu_88_p_lutw_0_ce1,
        p_lutw_0_d1 => grp_process_i_fu_88_p_lutw_0_d1,
        p_lutw_0_q1 => p_lutw_0_q1,
        p_lutw_0_we1 => grp_process_i_fu_88_p_lutw_0_we1,
        p_lutw_1_address0 => grp_process_i_fu_88_p_lutw_1_address0,
        p_lutw_1_ce0 => grp_process_i_fu_88_p_lutw_1_ce0,
        p_lutw_1_d0 => grp_process_i_fu_88_p_lutw_1_d0,
        p_lutw_1_q0 => p_lutw_1_q0,
        p_lutw_1_we0 => grp_process_i_fu_88_p_lutw_1_we0,
        p_lutw_1_address1 => grp_process_i_fu_88_p_lutw_1_address1,
        p_lutw_1_ce1 => grp_process_i_fu_88_p_lutw_1_ce1,
        p_lutw_1_d1 => grp_process_i_fu_88_p_lutw_1_d1,
        p_lutw_1_q1 => p_lutw_1_q1,
        p_lutw_1_we1 => grp_process_i_fu_88_p_lutw_1_we1,
        p_lutr_0_address0 => grp_process_i_fu_88_p_lutr_0_address0,
        p_lutr_0_ce0 => grp_process_i_fu_88_p_lutr_0_ce0,
        p_lutr_0_d0 => grp_process_i_fu_88_p_lutr_0_d0,
        p_lutr_0_q0 => p_lutr_0_q0,
        p_lutr_0_we0 => grp_process_i_fu_88_p_lutr_0_we0,
        p_lutr_0_address1 => grp_process_i_fu_88_p_lutr_0_address1,
        p_lutr_0_ce1 => grp_process_i_fu_88_p_lutr_0_ce1,
        p_lutr_0_d1 => grp_process_i_fu_88_p_lutr_0_d1,
        p_lutr_0_q1 => p_lutr_0_q1,
        p_lutr_0_we1 => grp_process_i_fu_88_p_lutr_0_we1,
        p_lutr_1_address0 => grp_process_i_fu_88_p_lutr_1_address0,
        p_lutr_1_ce0 => grp_process_i_fu_88_p_lutr_1_ce0,
        p_lutr_1_d0 => grp_process_i_fu_88_p_lutr_1_d0,
        p_lutr_1_q0 => p_lutr_1_q0,
        p_lutr_1_we0 => grp_process_i_fu_88_p_lutr_1_we0,
        p_lutr_1_address1 => grp_process_i_fu_88_p_lutr_1_address1,
        p_lutr_1_ce1 => grp_process_i_fu_88_p_lutr_1_ce1,
        p_lutr_1_d1 => grp_process_i_fu_88_p_lutr_1_d1,
        p_lutr_1_q1 => p_lutr_1_q1,
        p_lutr_1_we1 => grp_process_i_fu_88_p_lutr_1_we1,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        Tile_0_val3_ap_vld => ap_const_logic_1,
        Tile_2_val5_ap_vld => ap_const_logic_1,
        Tile_5_val9_ap_vld => ap_const_logic_1,
        Tile_6_val11_ap_vld => ap_const_logic_1,
        Tile_8_val14_ap_vld => ap_const_logic_1,
        ap_start => grp_process_i_fu_88_ap_start,
        ap_done => grp_process_i_fu_88_ap_done,
        Tile_3_val6_ap_vld => ap_const_logic_1,
        Tile_4_val7_ap_vld => ap_const_logic_1,
        ap_ready => grp_process_i_fu_88_ap_ready,
        ap_idle => grp_process_i_fu_88_ap_idle,
        ap_continue => grp_process_i_fu_88_ap_continue);

    mul_26s_32s_32_2_1_U176 : component clahe_accel_mul_26s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 26,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => mul_ln86_reg_336,
        din1 => clip,
        ce => ap_const_logic_1,
        dout => grp_fu_113_p2);

    mul_32s_32s_32_2_1_U177 : component clahe_accel_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => Tile_mTileHeight_reg_282,
        din1 => tilesY,
        ce => ap_const_logic_1,
        dout => grp_fu_117_p2);

    mul_32s_32s_32_2_1_U178 : component clahe_accel_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => Tile_mTileWidth_reg_293,
        din1 => tilesX,
        ce => ap_const_logic_1,
        dout => grp_fu_121_p2);

    sdiv_12ns_32s_32_16_seq_1_U179 : component clahe_accel_sdiv_12ns_32s_32_16_seq_1
    generic map (
        ID => 1,
        NUM_STAGE => 16,
        din0_WIDTH => 12,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        start => grp_fu_133_ap_start,
        done => grp_fu_133_ap_done,
        din0 => grp_fu_133_p0,
        din1 => tilesY,
        ce => grp_fu_133_ce,
        dout => grp_fu_133_p2);

    sdiv_12ns_32s_32_16_seq_1_U180 : component clahe_accel_sdiv_12ns_32s_32_16_seq_1
    generic map (
        ID => 1,
        NUM_STAGE => 16,
        din0_WIDTH => 12,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        start => grp_fu_139_ap_start,
        done => grp_fu_139_ap_done,
        din0 => grp_fu_139_p0,
        din1 => tilesX,
        ce => grp_fu_139_ce,
        dout => grp_fu_139_p2);

    mul_13s_13s_26_1_1_U181 : component clahe_accel_mul_13s_13s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 13,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => Tile_mTileHeight_1_reg_319,
        din1 => Tile_mTileWidth_3_reg_325,
        dout => mul_ln86_fu_197_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state25) and (ap_const_boolean_0 = ap_block_state25_on_subcall_done))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_process_i_fu_88_ap_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_process_i_fu_88_ap_done <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state25) and (ap_const_boolean_0 = ap_block_state25_on_subcall_done))) then 
                    ap_sync_reg_grp_process_i_fu_88_ap_done <= ap_const_logic_0;
                elsif ((grp_process_i_fu_88_ap_done = ap_const_logic_1)) then 
                    ap_sync_reg_grp_process_i_fu_88_ap_done <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_process_i_fu_88_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_process_i_fu_88_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state25) and (ap_const_boolean_0 = ap_block_state25_on_subcall_done))) then 
                    ap_sync_reg_grp_process_i_fu_88_ap_ready <= ap_const_logic_0;
                elsif ((grp_process_i_fu_88_ap_ready = ap_const_logic_1)) then 
                    ap_sync_reg_grp_process_i_fu_88_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_process_i_fu_88_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_process_i_fu_88_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state24) or ((ap_sync_grp_process_i_fu_88_ap_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state25)))) then 
                    grp_process_i_fu_88_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_process_i_fu_88_ap_ready = ap_const_logic_1)) then 
                    grp_process_i_fu_88_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state23)) then
                Tile_mClipValue_1_reg_356 <= Tile_mClipValue_1_fu_239_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then
                Tile_mTileHeight_1_reg_319 <= Tile_mTileHeight_1_fu_162_p3;
                Tile_mTileWidth_3_reg_325 <= Tile_mTileWidth_3_fu_178_p3;
                icmp_ln85_reg_331 <= icmp_ln85_fu_185_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                Tile_mTileHeight_reg_282 <= grp_fu_133_p2;
                Tile_mTileWidth_reg_293 <= grp_fu_139_p2;
                trunc_ln445_1_reg_298 <= trunc_ln445_1_fu_149_p1;
                trunc_ln445_reg_287 <= trunc_ln445_fu_145_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    height_cast_reg_276(10 downto 0) <= height_cast_fu_129_p1(10 downto 0);
                    width_cast_reg_270(10 downto 0) <= width_cast_fu_125_p1(10 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then
                mul_ln78_reg_304 <= grp_fu_117_p2;
                mul_ln80_reg_309 <= grp_fu_121_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state22)) then
                mul_ln86_1_reg_346 <= grp_fu_113_p2;
                trunc_ln86_1_reg_351 <= grp_fu_113_p2(31 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then
                mul_ln86_reg_336 <= mul_ln86_fu_197_p2;
            end if;
        end if;
    end process;
    width_cast_reg_270(31 downto 11) <= "000000000000000000000";
    height_cast_reg_276(31 downto 11) <= "000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state25, ap_block_state25_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state25) and (ap_const_boolean_0 = ap_block_state25_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state25;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    Tile_mClipValue_1_fu_239_p3 <= 
        Tile_mClipValue_fu_231_p3 when (icmp_ln85_reg_331(0) = '1') else 
        ap_const_lv19_7FFFF;
    Tile_mClipValue_fu_231_p3 <= 
        ap_const_lv19_1 when (icmp_ln224_fu_217_p2(0) = '1') else 
        trunc_ln1_fu_222_p4;
    Tile_mTileHeight_1_fu_162_p3 <= 
        add_ln78_fu_157_p2 when (icmp_ln78_fu_153_p2(0) = '1') else 
        trunc_ln445_reg_287;
    Tile_mTileWidth_1_fu_173_p2 <= std_logic_vector(unsigned(trunc_ln445_1_reg_298) + unsigned(ap_const_lv13_1));
    Tile_mTileWidth_3_fu_178_p3 <= 
        Tile_mTileWidth_1_fu_173_p2 when (icmp_ln80_fu_169_p2(0) = '1') else 
        trunc_ln445_1_reg_298;
    add_ln78_fu_157_p2 <= std_logic_vector(unsigned(trunc_ln445_reg_287) + unsigned(ap_const_lv13_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;

    ap_ST_fsm_state25_blk_assign_proc : process(ap_block_state25_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state25_on_subcall_done)) then 
            ap_ST_fsm_state25_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state25_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state25_on_subcall_done_assign_proc : process(ap_sync_grp_process_i_fu_88_ap_ready, ap_sync_grp_process_i_fu_88_ap_done)
    begin
                ap_block_state25_on_subcall_done <= ((ap_sync_grp_process_i_fu_88_ap_ready and ap_sync_grp_process_i_fu_88_ap_done) = ap_const_logic_0);
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state25, ap_block_state25_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state25) and (ap_const_boolean_0 = ap_block_state25_on_subcall_done))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state25, ap_block_state25_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state25) and (ap_const_boolean_0 = ap_block_state25_on_subcall_done))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_sync_grp_process_i_fu_88_ap_done <= (grp_process_i_fu_88_ap_done or ap_sync_reg_grp_process_i_fu_88_ap_done);
    ap_sync_grp_process_i_fu_88_ap_ready <= (grp_process_i_fu_88_ap_ready or ap_sync_reg_grp_process_i_fu_88_ap_ready);

    grp_fu_133_ap_start_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            grp_fu_133_ap_start <= ap_const_logic_1;
        else 
            grp_fu_133_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_133_ce_assign_proc : process(ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state21, ap_CS_fsm_state22, ap_CS_fsm_state23, ap_CS_fsm_state24, ap_CS_fsm_state25, ap_CS_fsm_state17)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state25) or (ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state22) or (ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            grp_fu_133_ce <= ap_const_logic_0;
        else 
            grp_fu_133_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_133_p0 <= grp_fu_133_p00(12 - 1 downto 0);
    grp_fu_133_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height),32));

    grp_fu_139_ap_start_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            grp_fu_139_ap_start <= ap_const_logic_1;
        else 
            grp_fu_139_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_139_ce_assign_proc : process(ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state21, ap_CS_fsm_state22, ap_CS_fsm_state23, ap_CS_fsm_state24, ap_CS_fsm_state25, ap_CS_fsm_state17)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state25) or (ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state22) or (ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            grp_fu_139_ce <= ap_const_logic_0;
        else 
            grp_fu_139_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_139_p0 <= grp_fu_139_p00(12 - 1 downto 0);
    grp_fu_139_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width),32));

    grp_process_i_fu_88_ap_continue_assign_proc : process(ap_CS_fsm_state25, ap_block_state25_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state25) and (ap_const_boolean_0 = ap_block_state25_on_subcall_done))) then 
            grp_process_i_fu_88_ap_continue <= ap_const_logic_1;
        else 
            grp_process_i_fu_88_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    grp_process_i_fu_88_ap_start <= grp_process_i_fu_88_ap_start_reg;
    height_cast_fu_129_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height),32));
    icmp_ln224_fu_217_p2 <= "1" when (signed(trunc_ln86_1_reg_351) < signed(ap_const_lv24_1)) else "0";
    icmp_ln78_fu_153_p2 <= "1" when (signed(mul_ln78_reg_304) < signed(height_cast_reg_276)) else "0";
    icmp_ln80_fu_169_p2 <= "1" when (signed(mul_ln80_reg_309) < signed(width_cast_reg_270)) else "0";
    icmp_ln85_fu_185_p0 <= clip;
    icmp_ln85_fu_185_p2 <= "1" when (signed(icmp_ln85_fu_185_p0) > signed(ap_const_lv32_0)) else "0";

    imgInput_data_read_assign_proc : process(grp_process_i_fu_88_imgInput_data_read, ap_CS_fsm_state25)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            imgInput_data_read <= grp_process_i_fu_88_imgInput_data_read;
        else 
            imgInput_data_read <= ap_const_logic_0;
        end if; 
    end process;

    imgOutput_data_din <= grp_process_i_fu_88_imgOutput_data_din;

    imgOutput_data_write_assign_proc : process(grp_process_i_fu_88_imgOutput_data_write, ap_CS_fsm_state25)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            imgOutput_data_write <= grp_process_i_fu_88_imgOutput_data_write;
        else 
            imgOutput_data_write <= ap_const_logic_0;
        end if; 
    end process;

    p_lutr_0_address0 <= grp_process_i_fu_88_p_lutr_0_address0;
    p_lutr_0_address1 <= grp_process_i_fu_88_p_lutr_0_address1;
    p_lutr_0_ce0 <= grp_process_i_fu_88_p_lutr_0_ce0;
    p_lutr_0_ce1 <= grp_process_i_fu_88_p_lutr_0_ce1;
    p_lutr_1_address0 <= grp_process_i_fu_88_p_lutr_1_address0;
    p_lutr_1_address1 <= grp_process_i_fu_88_p_lutr_1_address1;
    p_lutr_1_ce0 <= grp_process_i_fu_88_p_lutr_1_ce0;
    p_lutr_1_ce1 <= grp_process_i_fu_88_p_lutr_1_ce1;
    p_lutw_0_address0 <= grp_process_i_fu_88_p_lutw_0_address0;
    p_lutw_0_address1 <= grp_process_i_fu_88_p_lutw_0_address1;
    p_lutw_0_ce0 <= grp_process_i_fu_88_p_lutw_0_ce0;
    p_lutw_0_ce1 <= grp_process_i_fu_88_p_lutw_0_ce1;
    p_lutw_0_d0 <= grp_process_i_fu_88_p_lutw_0_d0;
    p_lutw_0_we0 <= grp_process_i_fu_88_p_lutw_0_we0;
    p_lutw_1_address0 <= grp_process_i_fu_88_p_lutw_1_address0;
    p_lutw_1_address1 <= grp_process_i_fu_88_p_lutw_1_address1;
    p_lutw_1_ce0 <= grp_process_i_fu_88_p_lutw_1_ce0;
    p_lutw_1_ce1 <= grp_process_i_fu_88_p_lutw_1_ce1;
    p_lutw_1_d0 <= grp_process_i_fu_88_p_lutw_1_d0;
    p_lutw_1_we0 <= grp_process_i_fu_88_p_lutw_1_we0;
    trunc_ln1_fu_222_p4 <= mul_ln86_1_reg_346(26 downto 8);
    trunc_ln445_1_fu_149_p1 <= grp_fu_139_p2(13 - 1 downto 0);
    trunc_ln445_fu_145_p1 <= grp_fu_133_p2(13 - 1 downto 0);
    width_cast_fu_125_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width),32));
end behav;
