<AutoPilot:project xmlns:AutoPilot="com.autoesl.autopilot.project" projectType="C/C++" top="v_hscaler" name="prj">
    <solutions>
        <solution name="sol" status=""/>
    </solutions>
    <files>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls/hls_video_undistort.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls/hls_video_types.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls/hls_video_stereobm.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls/hls_video_mem.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls/hls_video_io.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls/hls_video_imgproc.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls/hls_video_imgbase.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls/hls_video_hough.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls/hls_video_histogram.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls/hls_video_harris.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls/hls_video_haar.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls/hls_video_fast.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls/hls_video_core.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls/hls_video_arithm.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls/hls_axi_io.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls_opencv.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls_video.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/v_hscaler.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/v_hscaler.cpp" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/v_hscaler_config.h" sc="0" tb="false" cflags="-I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src/hls -I/home/alen/repo/zynq-7020-video-pipe-3/hw/video-pipe-hw-v5/hw_011223.gen/sources_1/bd/broncho_video/ip/broncho_video_v_proc_ss_0_1/bd_0/ip/ip_2/src" csimflags="" blackbox="false"/>
    </files>
</AutoPilot:project>

