// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bd_8126_hsc_0_hscale_core_polyphase_Pipeline_loop_width (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stream_upsampled_dout,
        stream_upsampled_num_data_valid,
        stream_upsampled_fifo_cap,
        stream_upsampled_empty_n,
        stream_upsampled_read,
        stream_scaled_din,
        stream_scaled_num_data_valid,
        stream_scaled_fifo_cap,
        stream_scaled_full_n,
        stream_scaled_write,
        add_ln682,
        phasesH_address0,
        phasesH_ce0,
        phasesH_q0,
        FiltCoeff_address0,
        FiltCoeff_ce0,
        FiltCoeff_q0,
        FiltCoeff_1_address0,
        FiltCoeff_1_ce0,
        FiltCoeff_1_q0,
        FiltCoeff_2_address0,
        FiltCoeff_2_ce0,
        FiltCoeff_2_q0,
        FiltCoeff_3_address0,
        FiltCoeff_3_ce0,
        FiltCoeff_3_q0,
        FiltCoeff_4_address0,
        FiltCoeff_4_ce0,
        FiltCoeff_4_q0,
        FiltCoeff_5_address0,
        FiltCoeff_5_ce0,
        FiltCoeff_5_q0,
        LoopSize,
        zext_ln682,
        PixArray_47_out_i,
        PixArray_47_out_o,
        PixArray_47_out_o_ap_vld,
        PixArray_46_out_i,
        PixArray_46_out_o,
        PixArray_46_out_o_ap_vld,
        PixArray_45_out_i,
        PixArray_45_out_o,
        PixArray_45_out_o_ap_vld,
        PixArray_44_out_i,
        PixArray_44_out_o,
        PixArray_44_out_o_ap_vld,
        PixArray_43_out_i,
        PixArray_43_out_o,
        PixArray_43_out_o_ap_vld,
        PixArray_42_out_i,
        PixArray_42_out_o,
        PixArray_42_out_o_ap_vld,
        PixArray_41_out_i,
        PixArray_41_out_o,
        PixArray_41_out_o_ap_vld,
        PixArray_40_out_i,
        PixArray_40_out_o,
        PixArray_40_out_o_ap_vld,
        PixArray_39_out_i,
        PixArray_39_out_o,
        PixArray_39_out_o_ap_vld,
        PixArray_38_out_i,
        PixArray_38_out_o,
        PixArray_38_out_o_ap_vld,
        PixArray_37_out_i,
        PixArray_37_out_o,
        PixArray_37_out_o_ap_vld,
        PixArray_36_out_i,
        PixArray_36_out_o,
        PixArray_36_out_o_ap_vld,
        PixArray_35_out_i,
        PixArray_35_out_o,
        PixArray_35_out_o_ap_vld,
        PixArray_34_out_i,
        PixArray_34_out_o,
        PixArray_34_out_o_ap_vld,
        PixArray_33_out_i,
        PixArray_33_out_o,
        PixArray_33_out_o_ap_vld,
        PixArray_32_out_i,
        PixArray_32_out_o,
        PixArray_32_out_o_ap_vld,
        PixArray_31_out_i,
        PixArray_31_out_o,
        PixArray_31_out_o_ap_vld,
        PixArray_30_out_i,
        PixArray_30_out_o,
        PixArray_30_out_o_ap_vld,
        PixArray_29_out_i,
        PixArray_29_out_o,
        PixArray_29_out_o_ap_vld,
        PixArray_28_out_i,
        PixArray_28_out_o,
        PixArray_28_out_o_ap_vld,
        PixArray_27_out_i,
        PixArray_27_out_o,
        PixArray_27_out_o_ap_vld,
        PixArray_26_out_i,
        PixArray_26_out_o,
        PixArray_26_out_o_ap_vld,
        PixArray_25_out_i,
        PixArray_25_out_o,
        PixArray_25_out_o_ap_vld,
        PixArray_24_out_i,
        PixArray_24_out_o,
        PixArray_24_out_o_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [29:0] stream_upsampled_dout;
input  [4:0] stream_upsampled_num_data_valid;
input  [4:0] stream_upsampled_fifo_cap;
input   stream_upsampled_empty_n;
output   stream_upsampled_read;
output  [29:0] stream_scaled_din;
input  [4:0] stream_scaled_num_data_valid;
input  [4:0] stream_scaled_fifo_cap;
input   stream_scaled_full_n;
output   stream_scaled_write;
input  [10:0] add_ln682;
output  [10:0] phasesH_address0;
output   phasesH_ce0;
input  [8:0] phasesH_q0;
output  [5:0] FiltCoeff_address0;
output   FiltCoeff_ce0;
input  [15:0] FiltCoeff_q0;
output  [5:0] FiltCoeff_1_address0;
output   FiltCoeff_1_ce0;
input  [15:0] FiltCoeff_1_q0;
output  [5:0] FiltCoeff_2_address0;
output   FiltCoeff_2_ce0;
input  [15:0] FiltCoeff_2_q0;
output  [5:0] FiltCoeff_3_address0;
output   FiltCoeff_3_ce0;
input  [15:0] FiltCoeff_3_q0;
output  [5:0] FiltCoeff_4_address0;
output   FiltCoeff_4_ce0;
input  [15:0] FiltCoeff_4_q0;
output  [5:0] FiltCoeff_5_address0;
output   FiltCoeff_5_ce0;
input  [15:0] FiltCoeff_5_q0;
input  [10:0] LoopSize;
input  [15:0] zext_ln682;
input  [9:0] PixArray_47_out_i;
output  [9:0] PixArray_47_out_o;
output   PixArray_47_out_o_ap_vld;
input  [9:0] PixArray_46_out_i;
output  [9:0] PixArray_46_out_o;
output   PixArray_46_out_o_ap_vld;
input  [9:0] PixArray_45_out_i;
output  [9:0] PixArray_45_out_o;
output   PixArray_45_out_o_ap_vld;
input  [9:0] PixArray_44_out_i;
output  [9:0] PixArray_44_out_o;
output   PixArray_44_out_o_ap_vld;
input  [9:0] PixArray_43_out_i;
output  [9:0] PixArray_43_out_o;
output   PixArray_43_out_o_ap_vld;
input  [9:0] PixArray_42_out_i;
output  [9:0] PixArray_42_out_o;
output   PixArray_42_out_o_ap_vld;
input  [9:0] PixArray_41_out_i;
output  [9:0] PixArray_41_out_o;
output   PixArray_41_out_o_ap_vld;
input  [9:0] PixArray_40_out_i;
output  [9:0] PixArray_40_out_o;
output   PixArray_40_out_o_ap_vld;
input  [9:0] PixArray_39_out_i;
output  [9:0] PixArray_39_out_o;
output   PixArray_39_out_o_ap_vld;
input  [9:0] PixArray_38_out_i;
output  [9:0] PixArray_38_out_o;
output   PixArray_38_out_o_ap_vld;
input  [9:0] PixArray_37_out_i;
output  [9:0] PixArray_37_out_o;
output   PixArray_37_out_o_ap_vld;
input  [9:0] PixArray_36_out_i;
output  [9:0] PixArray_36_out_o;
output   PixArray_36_out_o_ap_vld;
input  [9:0] PixArray_35_out_i;
output  [9:0] PixArray_35_out_o;
output   PixArray_35_out_o_ap_vld;
input  [9:0] PixArray_34_out_i;
output  [9:0] PixArray_34_out_o;
output   PixArray_34_out_o_ap_vld;
input  [9:0] PixArray_33_out_i;
output  [9:0] PixArray_33_out_o;
output   PixArray_33_out_o_ap_vld;
input  [9:0] PixArray_32_out_i;
output  [9:0] PixArray_32_out_o;
output   PixArray_32_out_o_ap_vld;
input  [9:0] PixArray_31_out_i;
output  [9:0] PixArray_31_out_o;
output   PixArray_31_out_o_ap_vld;
input  [9:0] PixArray_30_out_i;
output  [9:0] PixArray_30_out_o;
output   PixArray_30_out_o_ap_vld;
input  [9:0] PixArray_29_out_i;
output  [9:0] PixArray_29_out_o;
output   PixArray_29_out_o_ap_vld;
input  [9:0] PixArray_28_out_i;
output  [9:0] PixArray_28_out_o;
output   PixArray_28_out_o_ap_vld;
input  [9:0] PixArray_27_out_i;
output  [9:0] PixArray_27_out_o;
output   PixArray_27_out_o_ap_vld;
input  [9:0] PixArray_26_out_i;
output  [9:0] PixArray_26_out_o;
output   PixArray_26_out_o_ap_vld;
input  [9:0] PixArray_25_out_i;
output  [9:0] PixArray_25_out_o;
output   PixArray_25_out_o_ap_vld;
input  [9:0] PixArray_24_out_i;
output  [9:0] PixArray_24_out_o;
output   PixArray_24_out_o_ap_vld;

reg ap_idle;
reg stream_upsampled_read;
reg stream_scaled_write;
reg phasesH_ce0;
reg[9:0] PixArray_47_out_o;
reg PixArray_47_out_o_ap_vld;
reg[9:0] PixArray_46_out_o;
reg PixArray_46_out_o_ap_vld;
reg[9:0] PixArray_45_out_o;
reg PixArray_45_out_o_ap_vld;
reg[9:0] PixArray_44_out_o;
reg PixArray_44_out_o_ap_vld;
reg[9:0] PixArray_43_out_o;
reg PixArray_43_out_o_ap_vld;
reg[9:0] PixArray_42_out_o;
reg PixArray_42_out_o_ap_vld;
reg[9:0] PixArray_41_out_o;
reg PixArray_41_out_o_ap_vld;
reg[9:0] PixArray_40_out_o;
reg PixArray_40_out_o_ap_vld;
reg[9:0] PixArray_39_out_o;
reg PixArray_39_out_o_ap_vld;
reg[9:0] PixArray_38_out_o;
reg PixArray_38_out_o_ap_vld;
reg[9:0] PixArray_37_out_o;
reg PixArray_37_out_o_ap_vld;
reg[9:0] PixArray_36_out_o;
reg PixArray_36_out_o_ap_vld;
reg[9:0] PixArray_35_out_o;
reg PixArray_35_out_o_ap_vld;
reg[9:0] PixArray_34_out_o;
reg PixArray_34_out_o_ap_vld;
reg[9:0] PixArray_33_out_o;
reg PixArray_33_out_o_ap_vld;
reg[9:0] PixArray_32_out_o;
reg PixArray_32_out_o_ap_vld;
reg[9:0] PixArray_31_out_o;
reg PixArray_31_out_o_ap_vld;
reg[9:0] PixArray_30_out_o;
reg PixArray_30_out_o_ap_vld;
reg[9:0] PixArray_29_out_o;
reg PixArray_29_out_o_ap_vld;
reg[9:0] PixArray_28_out_o;
reg PixArray_28_out_o_ap_vld;
reg[9:0] PixArray_27_out_o;
reg PixArray_27_out_o_ap_vld;
reg[9:0] PixArray_26_out_o;
reg PixArray_26_out_o_ap_vld;
reg[9:0] PixArray_25_out_o;
reg PixArray_25_out_o_ap_vld;
reg[9:0] PixArray_24_out_o;
reg PixArray_24_out_o_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln708_reg_1021;
reg   [0:0] icmp_ln721_reg_1047;
reg    ap_predicate_op141_read_state4;
reg    ap_block_state4_pp0_stage0_iter3;
reg   [0:0] icmp_ln760_reg_1012;
reg   [0:0] icmp_ln760_reg_1012_pp0_iter13_reg;
reg   [0:0] and_ln802_reg_1061;
reg   [0:0] and_ln802_reg_1061_pp0_iter13_reg;
reg    ap_predicate_op188_write_state15;
reg    ap_block_state15_pp0_stage0_iter14;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln698_fu_292_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    stream_upsampled_blk_n;
wire    ap_block_pp0_stage0;
reg    stream_scaled_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [10:0] LoopSize_read_reg_992;
wire   [16:0] zext_ln682_cast_fu_270_p1;
reg   [16:0] zext_ln682_cast_reg_997;
reg   [10:0] x_5_reg_1002;
reg   [10:0] x_5_reg_1002_pp0_iter1_reg;
reg   [0:0] icmp_ln698_reg_1008;
reg   [0:0] icmp_ln698_reg_1008_pp0_iter1_reg;
reg   [0:0] icmp_ln698_reg_1008_pp0_iter2_reg;
reg   [0:0] icmp_ln698_reg_1008_pp0_iter3_reg;
reg   [0:0] icmp_ln698_reg_1008_pp0_iter4_reg;
reg   [0:0] icmp_ln698_reg_1008_pp0_iter5_reg;
reg   [0:0] icmp_ln698_reg_1008_pp0_iter6_reg;
reg   [0:0] icmp_ln698_reg_1008_pp0_iter7_reg;
reg   [0:0] icmp_ln698_reg_1008_pp0_iter8_reg;
reg   [0:0] icmp_ln698_reg_1008_pp0_iter9_reg;
wire   [0:0] icmp_ln760_fu_314_p2;
reg   [0:0] icmp_ln760_reg_1012_pp0_iter1_reg;
reg   [0:0] icmp_ln760_reg_1012_pp0_iter2_reg;
reg   [0:0] icmp_ln760_reg_1012_pp0_iter3_reg;
reg   [0:0] icmp_ln760_reg_1012_pp0_iter4_reg;
reg   [0:0] icmp_ln760_reg_1012_pp0_iter5_reg;
reg   [0:0] icmp_ln760_reg_1012_pp0_iter6_reg;
reg   [0:0] icmp_ln760_reg_1012_pp0_iter7_reg;
reg   [0:0] icmp_ln760_reg_1012_pp0_iter8_reg;
reg   [0:0] icmp_ln760_reg_1012_pp0_iter9_reg;
reg   [0:0] icmp_ln760_reg_1012_pp0_iter10_reg;
reg   [0:0] icmp_ln760_reg_1012_pp0_iter11_reg;
reg   [0:0] icmp_ln760_reg_1012_pp0_iter12_reg;
wire   [0:0] icmp_ln708_fu_348_p2;
wire   [0:0] icmp_fu_363_p2;
reg   [0:0] icmp_reg_1025;
wire   [0:0] icmp_ln721_fu_379_p2;
wire   [5:0] trunc_ln776_fu_384_p1;
reg   [5:0] trunc_ln776_reg_1051;
reg   [5:0] trunc_ln776_reg_1051_pp0_iter3_reg;
wire   [1:0] ArrayLoc_fu_388_p4;
reg   [1:0] ArrayLoc_reg_1056;
reg   [1:0] ArrayLoc_reg_1056_pp0_iter3_reg;
wire   [0:0] and_ln802_fu_434_p2;
reg   [0:0] and_ln802_reg_1061_pp0_iter3_reg;
reg   [0:0] and_ln802_reg_1061_pp0_iter4_reg;
reg   [0:0] and_ln802_reg_1061_pp0_iter5_reg;
reg   [0:0] and_ln802_reg_1061_pp0_iter6_reg;
reg   [0:0] and_ln802_reg_1061_pp0_iter7_reg;
reg   [0:0] and_ln802_reg_1061_pp0_iter8_reg;
reg   [0:0] and_ln802_reg_1061_pp0_iter9_reg;
reg   [0:0] and_ln802_reg_1061_pp0_iter10_reg;
reg   [0:0] and_ln802_reg_1061_pp0_iter11_reg;
reg   [0:0] and_ln802_reg_1061_pp0_iter12_reg;
reg    ap_condition_exit_pp0_iter2_stage0;
wire    grp_hscale_polyphase_fu_228_ap_start;
wire    grp_hscale_polyphase_fu_228_ap_done;
wire    grp_hscale_polyphase_fu_228_ap_idle;
wire    grp_hscale_polyphase_fu_228_ap_ready;
reg    grp_hscale_polyphase_fu_228_ap_ce;
wire   [5:0] grp_hscale_polyphase_fu_228_FiltCoeff_0_address0;
wire    grp_hscale_polyphase_fu_228_FiltCoeff_0_ce0;
wire   [5:0] grp_hscale_polyphase_fu_228_FiltCoeff_1_address0;
wire    grp_hscale_polyphase_fu_228_FiltCoeff_1_ce0;
wire   [5:0] grp_hscale_polyphase_fu_228_FiltCoeff_2_address0;
wire    grp_hscale_polyphase_fu_228_FiltCoeff_2_ce0;
wire   [5:0] grp_hscale_polyphase_fu_228_FiltCoeff_3_address0;
wire    grp_hscale_polyphase_fu_228_FiltCoeff_3_ce0;
wire   [5:0] grp_hscale_polyphase_fu_228_FiltCoeff_4_address0;
wire    grp_hscale_polyphase_fu_228_FiltCoeff_4_ce0;
wire   [5:0] grp_hscale_polyphase_fu_228_FiltCoeff_5_address0;
wire    grp_hscale_polyphase_fu_228_FiltCoeff_5_ce0;
wire   [9:0] grp_hscale_polyphase_fu_228_ap_return_0;
wire   [9:0] grp_hscale_polyphase_fu_228_ap_return_1;
wire   [9:0] grp_hscale_polyphase_fu_228_ap_return_2;
reg    ap_predicate_op173_call_state5;
reg    ap_predicate_op174_call_state6;
reg    ap_predicate_op175_call_state7;
reg    ap_predicate_op176_call_state8;
reg    ap_predicate_op177_call_state9;
reg    ap_predicate_op178_call_state10;
reg    ap_predicate_op179_call_state11;
reg    ap_block_state4_pp0_stage0_iter3_ignore_call34;
reg    ap_block_state15_pp0_stage0_iter14_ignore_call34;
reg    ap_block_pp0_stage0_11001_ignoreCallOp173;
wire   [8:0] grp_reg_ap_uint_9_s_fu_336_ap_return;
reg    grp_reg_ap_uint_9_s_fu_336_ap_ce;
reg    ap_predicate_op53_call_state2;
reg    ap_block_state4_pp0_stage0_iter3_ignore_call28;
reg    ap_block_state15_pp0_stage0_iter14_ignore_call28;
reg    ap_block_pp0_stage0_11001_ignoreCallOp53;
reg    grp_hscale_polyphase_fu_228_ap_start_reg;
reg    ap_predicate_op173_call_state5_state4;
wire   [63:0] zext_ln767_fu_326_p1;
wire   [9:0] PixArray_19_fu_786_p1;
wire   [9:0] PixArray_17_fu_534_p3;
wire   [9:0] PixArray_16_fu_541_p3;
wire   [9:0] PixArray_15_fu_548_p3;
wire   [9:0] PixArray_14_fu_555_p3;
wire   [9:0] PixArray_13_fu_562_p3;
wire   [9:0] PixArray_12_fu_569_p3;
wire   [9:0] PixArray_11_fu_576_p3;
wire   [9:0] PixArray_10_fu_583_p3;
wire   [9:0] PixArray_9_fu_590_p3;
wire   [9:0] PixArray_8_fu_597_p3;
wire   [9:0] PixArray_7_fu_604_p3;
wire   [9:0] PixArray_6_fu_611_p3;
wire   [9:0] PixArray_5_fu_618_p3;
wire   [9:0] PixArray_4_fu_625_p3;
wire   [9:0] PixArray_3_fu_632_p3;
wire   [9:0] PixArray_2_fu_639_p3;
wire   [9:0] PixArray_1_fu_646_p3;
wire   [9:0] PixArray_fu_653_p3;
reg   [10:0] x_fu_172;
wire   [10:0] add_ln698_fu_298_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_x_5;
reg   [15:0] xReadPos_fu_176;
wire   [15:0] xReadPos_5_fu_422_p3;
reg   [31:0] ReadEn_fu_180;
wire   [31:0] zext_ln782_fu_412_p1;
reg    ap_block_pp0_stage0_01001;
wire   [8:0] tmp_23_fu_304_p4;
wire   [10:0] xbySamples_fu_320_p2;
wire   [9:0] tmp_fu_354_p4;
wire   [16:0] zext_ln721_fu_369_p1;
wire   [16:0] add_ln721_fu_373_p2;
wire   [0:0] ReadEn_1_fu_406_p2;
wire   [15:0] xReadPos_4_fu_416_p2;
wire   [0:0] OutputWriteEn_fu_398_p3;
wire   [0:0] icmp_ln802_fu_430_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_969;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 grp_hscale_polyphase_fu_228_ap_start_reg = 1'b0;
#0 x_fu_172 = 11'd0;
#0 xReadPos_fu_176 = 16'd0;
#0 ReadEn_fu_180 = 32'd0;
#0 ap_done_reg = 1'b0;
end

bd_8126_hsc_0_hscale_polyphase grp_hscale_polyphase_fu_228(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_hscale_polyphase_fu_228_ap_start),
    .ap_done(grp_hscale_polyphase_fu_228_ap_done),
    .ap_idle(grp_hscale_polyphase_fu_228_ap_idle),
    .ap_ready(grp_hscale_polyphase_fu_228_ap_ready),
    .ap_ce(grp_hscale_polyphase_fu_228_ap_ce),
    .FiltCoeff_0_address0(grp_hscale_polyphase_fu_228_FiltCoeff_0_address0),
    .FiltCoeff_0_ce0(grp_hscale_polyphase_fu_228_FiltCoeff_0_ce0),
    .FiltCoeff_0_q0(FiltCoeff_q0),
    .FiltCoeff_1_address0(grp_hscale_polyphase_fu_228_FiltCoeff_1_address0),
    .FiltCoeff_1_ce0(grp_hscale_polyphase_fu_228_FiltCoeff_1_ce0),
    .FiltCoeff_1_q0(FiltCoeff_1_q0),
    .FiltCoeff_2_address0(grp_hscale_polyphase_fu_228_FiltCoeff_2_address0),
    .FiltCoeff_2_ce0(grp_hscale_polyphase_fu_228_FiltCoeff_2_ce0),
    .FiltCoeff_2_q0(FiltCoeff_2_q0),
    .FiltCoeff_3_address0(grp_hscale_polyphase_fu_228_FiltCoeff_3_address0),
    .FiltCoeff_3_ce0(grp_hscale_polyphase_fu_228_FiltCoeff_3_ce0),
    .FiltCoeff_3_q0(FiltCoeff_3_q0),
    .FiltCoeff_4_address0(grp_hscale_polyphase_fu_228_FiltCoeff_4_address0),
    .FiltCoeff_4_ce0(grp_hscale_polyphase_fu_228_FiltCoeff_4_ce0),
    .FiltCoeff_4_q0(FiltCoeff_4_q0),
    .FiltCoeff_5_address0(grp_hscale_polyphase_fu_228_FiltCoeff_5_address0),
    .FiltCoeff_5_ce0(grp_hscale_polyphase_fu_228_FiltCoeff_5_ce0),
    .FiltCoeff_5_q0(FiltCoeff_5_q0),
    .PixArray_0_0_val(PixArray_25_out_i),
    .PixArray_0_1_val(PixArray_26_out_i),
    .PixArray_0_2_val(PixArray_27_out_i),
    .PixArray_1_0_val(PixArray_28_out_i),
    .PixArray_1_1_val(PixArray_29_out_i),
    .PixArray_1_2_val(PixArray_30_out_i),
    .PixArray_2_0_val(PixArray_31_out_i),
    .PixArray_2_1_val(PixArray_32_out_i),
    .PixArray_2_2_val(PixArray_33_out_i),
    .PixArray_3_0_val(PixArray_34_out_i),
    .PixArray_3_1_val(PixArray_35_out_i),
    .PixArray_3_2_val(PixArray_36_out_i),
    .PixArray_4_0_val(PixArray_37_out_i),
    .PixArray_4_1_val(PixArray_38_out_i),
    .PixArray_4_2_val(PixArray_39_out_i),
    .PixArray_5_0_val(PixArray_40_out_i),
    .PixArray_5_1_val(PixArray_41_out_i),
    .PixArray_5_2_val(PixArray_42_out_i),
    .PixArray_6_0_val(PixArray_43_out_i),
    .PixArray_6_1_val(PixArray_44_out_i),
    .PixArray_6_2_val(PixArray_45_out_i),
    .PixArray_7_0_val(PixArray_46_out_i),
    .PixArray_7_1_val(PixArray_47_out_i),
    .PixArray_7_2_val(PixArray_24_out_i),
    .PhasesH_0_0_val(trunc_ln776_reg_1051_pp0_iter3_reg),
    .ArrayIdx_val(ArrayLoc_reg_1056_pp0_iter3_reg),
    .ap_return_0(grp_hscale_polyphase_fu_228_ap_return_0),
    .ap_return_1(grp_hscale_polyphase_fu_228_ap_return_1),
    .ap_return_2(grp_hscale_polyphase_fu_228_ap_return_2)
);

bd_8126_hsc_0_reg_ap_uint_9_s grp_reg_ap_uint_9_s_fu_336(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d_val(phasesH_q0),
    .ap_return(grp_reg_ap_uint_9_s_fu_336_ap_return),
    .ap_ce(grp_reg_ap_uint_9_s_fu_336_ap_ce)
);

bd_8126_hsc_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter13_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_hscale_polyphase_fu_228_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op173_call_state5_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            grp_hscale_polyphase_fu_228_ap_start_reg <= 1'b1;
        end else if ((grp_hscale_polyphase_fu_228_ap_ready == 1'b1)) begin
            grp_hscale_polyphase_fu_228_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                        ReadEn_fu_180[0] <= 1'b1;
        end else if ((1'b1 == ap_condition_969)) begin
                        ReadEn_fu_180[0] <= zext_ln782_fu_412_p1[0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            xReadPos_fu_176 <= 16'd0;
        end else if ((1'b1 == ap_condition_969)) begin
            xReadPos_fu_176 <= xReadPos_5_fu_422_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln698_fu_292_p2 == 1'd0))) begin
            x_fu_172 <= add_ln698_fu_298_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_172 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ArrayLoc_reg_1056 <= {{grp_reg_ap_uint_9_s_fu_336_ap_return[7:6]}};
        ArrayLoc_reg_1056_pp0_iter3_reg <= ArrayLoc_reg_1056;
        and_ln802_reg_1061 <= and_ln802_fu_434_p2;
        and_ln802_reg_1061_pp0_iter10_reg <= and_ln802_reg_1061_pp0_iter9_reg;
        and_ln802_reg_1061_pp0_iter11_reg <= and_ln802_reg_1061_pp0_iter10_reg;
        and_ln802_reg_1061_pp0_iter12_reg <= and_ln802_reg_1061_pp0_iter11_reg;
        and_ln802_reg_1061_pp0_iter13_reg <= and_ln802_reg_1061_pp0_iter12_reg;
        and_ln802_reg_1061_pp0_iter3_reg <= and_ln802_reg_1061;
        and_ln802_reg_1061_pp0_iter4_reg <= and_ln802_reg_1061_pp0_iter3_reg;
        and_ln802_reg_1061_pp0_iter5_reg <= and_ln802_reg_1061_pp0_iter4_reg;
        and_ln802_reg_1061_pp0_iter6_reg <= and_ln802_reg_1061_pp0_iter5_reg;
        and_ln802_reg_1061_pp0_iter7_reg <= and_ln802_reg_1061_pp0_iter6_reg;
        and_ln802_reg_1061_pp0_iter8_reg <= and_ln802_reg_1061_pp0_iter7_reg;
        and_ln802_reg_1061_pp0_iter9_reg <= and_ln802_reg_1061_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln698_reg_1008_pp0_iter2_reg <= icmp_ln698_reg_1008_pp0_iter1_reg;
        icmp_ln698_reg_1008_pp0_iter3_reg <= icmp_ln698_reg_1008_pp0_iter2_reg;
        icmp_ln698_reg_1008_pp0_iter4_reg <= icmp_ln698_reg_1008_pp0_iter3_reg;
        icmp_ln698_reg_1008_pp0_iter5_reg <= icmp_ln698_reg_1008_pp0_iter4_reg;
        icmp_ln698_reg_1008_pp0_iter6_reg <= icmp_ln698_reg_1008_pp0_iter5_reg;
        icmp_ln698_reg_1008_pp0_iter7_reg <= icmp_ln698_reg_1008_pp0_iter6_reg;
        icmp_ln698_reg_1008_pp0_iter8_reg <= icmp_ln698_reg_1008_pp0_iter7_reg;
        icmp_ln698_reg_1008_pp0_iter9_reg <= icmp_ln698_reg_1008_pp0_iter8_reg;
        icmp_ln708_reg_1021 <= icmp_ln708_fu_348_p2;
        icmp_ln721_reg_1047 <= icmp_ln721_fu_379_p2;
        icmp_ln760_reg_1012_pp0_iter10_reg <= icmp_ln760_reg_1012_pp0_iter9_reg;
        icmp_ln760_reg_1012_pp0_iter11_reg <= icmp_ln760_reg_1012_pp0_iter10_reg;
        icmp_ln760_reg_1012_pp0_iter12_reg <= icmp_ln760_reg_1012_pp0_iter11_reg;
        icmp_ln760_reg_1012_pp0_iter13_reg <= icmp_ln760_reg_1012_pp0_iter12_reg;
        icmp_ln760_reg_1012_pp0_iter2_reg <= icmp_ln760_reg_1012_pp0_iter1_reg;
        icmp_ln760_reg_1012_pp0_iter3_reg <= icmp_ln760_reg_1012_pp0_iter2_reg;
        icmp_ln760_reg_1012_pp0_iter4_reg <= icmp_ln760_reg_1012_pp0_iter3_reg;
        icmp_ln760_reg_1012_pp0_iter5_reg <= icmp_ln760_reg_1012_pp0_iter4_reg;
        icmp_ln760_reg_1012_pp0_iter6_reg <= icmp_ln760_reg_1012_pp0_iter5_reg;
        icmp_ln760_reg_1012_pp0_iter7_reg <= icmp_ln760_reg_1012_pp0_iter6_reg;
        icmp_ln760_reg_1012_pp0_iter8_reg <= icmp_ln760_reg_1012_pp0_iter7_reg;
        icmp_ln760_reg_1012_pp0_iter9_reg <= icmp_ln760_reg_1012_pp0_iter8_reg;
        icmp_reg_1025 <= icmp_fu_363_p2;
        trunc_ln776_reg_1051 <= trunc_ln776_fu_384_p1;
        trunc_ln776_reg_1051_pp0_iter3_reg <= trunc_ln776_reg_1051;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        LoopSize_read_reg_992 <= LoopSize;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln698_reg_1008 <= icmp_ln698_fu_292_p2;
        icmp_ln698_reg_1008_pp0_iter1_reg <= icmp_ln698_reg_1008;
        icmp_ln760_reg_1012 <= icmp_ln760_fu_314_p2;
        icmp_ln760_reg_1012_pp0_iter1_reg <= icmp_ln760_reg_1012;
        x_5_reg_1002 <= ap_sig_allocacmp_x_5;
        x_5_reg_1002_pp0_iter1_reg <= x_5_reg_1002;
        zext_ln682_cast_reg_997[15 : 0] <= zext_ln682_cast_fu_270_p1[15 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln721_reg_1047 == 1'd1) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_24_out_o = {{stream_upsampled_dout[29:20]}};
    end else begin
        PixArray_24_out_o = PixArray_24_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln721_reg_1047 == 1'd1) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_24_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_24_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_25_out_o = PixArray_fu_653_p3;
    end else begin
        PixArray_25_out_o = PixArray_25_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_25_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_25_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_26_out_o = PixArray_1_fu_646_p3;
    end else begin
        PixArray_26_out_o = PixArray_26_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_26_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_26_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_27_out_o = PixArray_2_fu_639_p3;
    end else begin
        PixArray_27_out_o = PixArray_27_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_27_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_27_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_28_out_o = PixArray_3_fu_632_p3;
    end else begin
        PixArray_28_out_o = PixArray_28_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_28_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_28_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_29_out_o = PixArray_4_fu_625_p3;
    end else begin
        PixArray_29_out_o = PixArray_29_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_29_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_29_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_30_out_o = PixArray_5_fu_618_p3;
    end else begin
        PixArray_30_out_o = PixArray_30_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_30_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_30_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_31_out_o = PixArray_6_fu_611_p3;
    end else begin
        PixArray_31_out_o = PixArray_31_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_31_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_31_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_32_out_o = PixArray_7_fu_604_p3;
    end else begin
        PixArray_32_out_o = PixArray_32_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_32_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_32_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_33_out_o = PixArray_8_fu_597_p3;
    end else begin
        PixArray_33_out_o = PixArray_33_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_33_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_33_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_34_out_o = PixArray_9_fu_590_p3;
    end else begin
        PixArray_34_out_o = PixArray_34_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_34_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_34_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_35_out_o = PixArray_10_fu_583_p3;
    end else begin
        PixArray_35_out_o = PixArray_35_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_35_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_35_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_36_out_o = PixArray_11_fu_576_p3;
    end else begin
        PixArray_36_out_o = PixArray_36_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_36_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_36_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_37_out_o = PixArray_12_fu_569_p3;
    end else begin
        PixArray_37_out_o = PixArray_37_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_37_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_37_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_38_out_o = PixArray_13_fu_562_p3;
    end else begin
        PixArray_38_out_o = PixArray_38_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_38_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_38_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_39_out_o = PixArray_14_fu_555_p3;
    end else begin
        PixArray_39_out_o = PixArray_39_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_39_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_39_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_40_out_o = PixArray_15_fu_548_p3;
    end else begin
        PixArray_40_out_o = PixArray_40_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_40_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_40_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_41_out_o = PixArray_16_fu_541_p3;
    end else begin
        PixArray_41_out_o = PixArray_41_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_41_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_41_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_42_out_o = PixArray_17_fu_534_p3;
    end else begin
        PixArray_42_out_o = PixArray_42_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_42_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_42_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_43_out_o = PixArray_46_out_i;
    end else begin
        PixArray_43_out_o = PixArray_43_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_43_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_43_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_44_out_o = PixArray_47_out_i;
    end else begin
        PixArray_44_out_o = PixArray_44_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_44_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_44_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_45_out_o = PixArray_24_out_i;
    end else begin
        PixArray_45_out_o = PixArray_45_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_45_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_45_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln721_reg_1047 == 1'd1) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_46_out_o = PixArray_19_fu_786_p1;
    end else begin
        PixArray_46_out_o = PixArray_46_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln721_reg_1047 == 1'd1) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_46_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_46_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln721_reg_1047 == 1'd1) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_47_out_o = {{stream_upsampled_dout[19:10]}};
    end else begin
        PixArray_47_out_o = PixArray_47_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln721_reg_1047 == 1'd1) & (icmp_ln708_reg_1021 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        PixArray_47_out_o_ap_vld = 1'b1;
    end else begin
        PixArray_47_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln698_fu_292_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln698_reg_1008_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter13_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_5 = 11'd0;
    end else begin
        ap_sig_allocacmp_x_5 = x_fu_172;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp173) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_hscale_polyphase_fu_228_ap_ce = 1'b1;
    end else begin
        grp_hscale_polyphase_fu_228_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp53) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_reg_ap_uint_9_s_fu_336_ap_ce = 1'b1;
    end else begin
        grp_reg_ap_uint_9_s_fu_336_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        phasesH_ce0 = 1'b1;
    end else begin
        phasesH_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter14 == 1'b1) & (ap_predicate_op188_write_state15 == 1'b1))) begin
        stream_scaled_blk_n = stream_scaled_full_n;
    end else begin
        stream_scaled_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1) & (ap_predicate_op188_write_state15 == 1'b1))) begin
        stream_scaled_write = 1'b1;
    end else begin
        stream_scaled_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op141_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        stream_upsampled_blk_n = stream_upsampled_empty_n;
    end else begin
        stream_upsampled_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op141_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        stream_upsampled_read = 1'b1;
    end else begin
        stream_upsampled_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ArrayLoc_fu_388_p4 = {{grp_reg_ap_uint_9_s_fu_336_ap_return[7:6]}};

assign FiltCoeff_1_address0 = grp_hscale_polyphase_fu_228_FiltCoeff_1_address0;

assign FiltCoeff_1_ce0 = grp_hscale_polyphase_fu_228_FiltCoeff_1_ce0;

assign FiltCoeff_2_address0 = grp_hscale_polyphase_fu_228_FiltCoeff_2_address0;

assign FiltCoeff_2_ce0 = grp_hscale_polyphase_fu_228_FiltCoeff_2_ce0;

assign FiltCoeff_3_address0 = grp_hscale_polyphase_fu_228_FiltCoeff_3_address0;

assign FiltCoeff_3_ce0 = grp_hscale_polyphase_fu_228_FiltCoeff_3_ce0;

assign FiltCoeff_4_address0 = grp_hscale_polyphase_fu_228_FiltCoeff_4_address0;

assign FiltCoeff_4_ce0 = grp_hscale_polyphase_fu_228_FiltCoeff_4_ce0;

assign FiltCoeff_5_address0 = grp_hscale_polyphase_fu_228_FiltCoeff_5_address0;

assign FiltCoeff_5_ce0 = grp_hscale_polyphase_fu_228_FiltCoeff_5_ce0;

assign FiltCoeff_address0 = grp_hscale_polyphase_fu_228_FiltCoeff_0_address0;

assign FiltCoeff_ce0 = grp_hscale_polyphase_fu_228_FiltCoeff_0_ce0;

assign OutputWriteEn_fu_398_p3 = grp_reg_ap_uint_9_s_fu_336_ap_return[32'd8];

assign PixArray_10_fu_583_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_47_out_i : PixArray_38_out_i);

assign PixArray_11_fu_576_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_24_out_i : PixArray_39_out_i);

assign PixArray_12_fu_569_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_46_out_i : PixArray_40_out_i);

assign PixArray_13_fu_562_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_47_out_i : PixArray_41_out_i);

assign PixArray_14_fu_555_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_24_out_i : PixArray_42_out_i);

assign PixArray_15_fu_548_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_46_out_i : PixArray_43_out_i);

assign PixArray_16_fu_541_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_47_out_i : PixArray_44_out_i);

assign PixArray_17_fu_534_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_24_out_i : PixArray_45_out_i);

assign PixArray_19_fu_786_p1 = stream_upsampled_dout[9:0];

assign PixArray_1_fu_646_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_47_out_i : PixArray_29_out_i);

assign PixArray_2_fu_639_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_24_out_i : PixArray_30_out_i);

assign PixArray_3_fu_632_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_46_out_i : PixArray_31_out_i);

assign PixArray_4_fu_625_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_47_out_i : PixArray_32_out_i);

assign PixArray_5_fu_618_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_24_out_i : PixArray_33_out_i);

assign PixArray_6_fu_611_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_46_out_i : PixArray_34_out_i);

assign PixArray_7_fu_604_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_47_out_i : PixArray_35_out_i);

assign PixArray_8_fu_597_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_24_out_i : PixArray_36_out_i);

assign PixArray_9_fu_590_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_46_out_i : PixArray_37_out_i);

assign PixArray_fu_653_p3 = ((icmp_reg_1025[0:0] == 1'b1) ? PixArray_46_out_i : PixArray_28_out_i);

assign ReadEn_1_fu_406_p2 = ((ArrayLoc_fu_388_p4 != 2'd0) ? 1'b1 : 1'b0);

assign add_ln698_fu_298_p2 = (ap_sig_allocacmp_x_5 + 11'd1);

assign add_ln721_fu_373_p2 = (zext_ln721_fu_369_p1 + 17'd4);

assign and_ln802_fu_434_p2 = (icmp_ln802_fu_430_p2 & OutputWriteEn_fu_398_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage0_iter14)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage0_iter14)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp173 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3_ignore_call34)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage0_iter14_ignore_call34)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp53 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3_ignore_call28)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage0_iter14_ignore_call28)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage0_iter14)));
end

always @ (*) begin
    ap_block_state15_pp0_stage0_iter14 = ((stream_scaled_full_n == 1'b0) & (ap_predicate_op188_write_state15 == 1'b1));
end

always @ (*) begin
    ap_block_state15_pp0_stage0_iter14_ignore_call28 = ((stream_scaled_full_n == 1'b0) & (ap_predicate_op188_write_state15 == 1'b1));
end

always @ (*) begin
    ap_block_state15_pp0_stage0_iter14_ignore_call34 = ((stream_scaled_full_n == 1'b0) & (ap_predicate_op188_write_state15 == 1'b1));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((ap_predicate_op141_read_state4 == 1'b1) & (stream_upsampled_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3_ignore_call28 = ((ap_predicate_op141_read_state4 == 1'b1) & (stream_upsampled_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3_ignore_call34 = ((ap_predicate_op141_read_state4 == 1'b1) & (stream_upsampled_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_969 = ((icmp_ln760_reg_1012_pp0_iter1_reg == 1'd0) & (icmp_ln698_reg_1008_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op141_read_state4 = ((icmp_ln721_reg_1047 == 1'd1) & (icmp_ln708_reg_1021 == 1'd0));
end

always @ (*) begin
    ap_predicate_op173_call_state5 = ((icmp_ln760_reg_1012_pp0_iter3_reg == 1'd0) & (icmp_ln698_reg_1008_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op173_call_state5_state4 = ((icmp_ln760_reg_1012_pp0_iter2_reg == 1'd0) & (icmp_ln698_reg_1008_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op174_call_state6 = ((icmp_ln760_reg_1012_pp0_iter4_reg == 1'd0) & (icmp_ln698_reg_1008_pp0_iter4_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op175_call_state7 = ((icmp_ln760_reg_1012_pp0_iter5_reg == 1'd0) & (icmp_ln698_reg_1008_pp0_iter5_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op176_call_state8 = ((icmp_ln760_reg_1012_pp0_iter6_reg == 1'd0) & (icmp_ln698_reg_1008_pp0_iter6_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op177_call_state9 = ((icmp_ln760_reg_1012_pp0_iter7_reg == 1'd0) & (icmp_ln698_reg_1008_pp0_iter7_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op178_call_state10 = ((icmp_ln760_reg_1012_pp0_iter8_reg == 1'd0) & (icmp_ln698_reg_1008_pp0_iter8_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op179_call_state11 = ((icmp_ln760_reg_1012_pp0_iter9_reg == 1'd0) & (icmp_ln698_reg_1008_pp0_iter9_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op188_write_state15 = ((1'd1 == and_ln802_reg_1061_pp0_iter13_reg) & (icmp_ln760_reg_1012_pp0_iter13_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op53_call_state2 = ((icmp_ln760_reg_1012 == 1'd0) & (icmp_ln698_reg_1008 == 1'd0));
end

assign grp_hscale_polyphase_fu_228_ap_start = grp_hscale_polyphase_fu_228_ap_start_reg;

assign icmp_fu_363_p2 = ((tmp_fu_354_p4 == 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln698_fu_292_p2 = ((ap_sig_allocacmp_x_5 == add_ln682) ? 1'b1 : 1'b0);

assign icmp_ln708_fu_348_p2 = ((ReadEn_fu_180 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln721_fu_379_p2 = ((add_ln721_fu_373_p2 < zext_ln682_cast_reg_997) ? 1'b1 : 1'b0);

assign icmp_ln760_fu_314_p2 = ((tmp_23_fu_304_p4 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln802_fu_430_p2 = ((x_5_reg_1002_pp0_iter1_reg < LoopSize_read_reg_992) ? 1'b1 : 1'b0);

assign phasesH_address0 = zext_ln767_fu_326_p1;

assign stream_scaled_din = {{{grp_hscale_polyphase_fu_228_ap_return_2}, {grp_hscale_polyphase_fu_228_ap_return_1}}, {grp_hscale_polyphase_fu_228_ap_return_0}};

assign tmp_23_fu_304_p4 = {{ap_sig_allocacmp_x_5[10:2]}};

assign tmp_fu_354_p4 = {{x_5_reg_1002_pp0_iter1_reg[10:1]}};

assign trunc_ln776_fu_384_p1 = grp_reg_ap_uint_9_s_fu_336_ap_return[5:0];

assign xReadPos_4_fu_416_p2 = (xReadPos_fu_176 + 16'd1);

assign xReadPos_5_fu_422_p3 = ((ReadEn_1_fu_406_p2[0:0] == 1'b1) ? xReadPos_4_fu_416_p2 : xReadPos_fu_176);

assign xbySamples_fu_320_p2 = ($signed(ap_sig_allocacmp_x_5) + $signed(11'd2044));

assign zext_ln682_cast_fu_270_p1 = zext_ln682;

assign zext_ln721_fu_369_p1 = xReadPos_fu_176;

assign zext_ln767_fu_326_p1 = xbySamples_fu_320_p2;

assign zext_ln782_fu_412_p1 = ReadEn_1_fu_406_p2;

always @ (posedge ap_clk) begin
    zext_ln682_cast_reg_997[16] <= 1'b0;
    ReadEn_fu_180[31:1] <= 31'b0000000000000000000000000000000;
end

endmodule //bd_8126_hsc_0_hscale_core_polyphase_Pipeline_loop_width
