set_property SRC_FILE_INFO {cfile:/home/alen/git/AMD-FPGA-Practice/zybo-z7-audio/hw/audio-pipe-hw-v0/audio_pipe_hw.gen/sources_1/bd/audio_pipe_hw/ip/audio_pipe_hw_axi_smc_0/ooc.xdc rfile:../../../../../audio_pipe_hw.gen/sources_1/bd/audio_pipe_hw/ip/audio_pipe_hw_axi_smc_0/ooc.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/git/AMD-FPGA-Practice/zybo-z7-audio/hw/audio-pipe-hw-v0/audio_pipe_hw.runs/audio_pipe_hw_axi_smc_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:3 order:LATE scoped_inst:inst/m00_exit_pipeline/m00_exit/inst/xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:4 order:LATE scoped_inst:inst/m00_nodes/m00_ar_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:5 order:LATE scoped_inst:inst/m00_nodes/m00_ar_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:6 order:LATE scoped_inst:inst/m00_nodes/m00_aw_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:7 order:LATE scoped_inst:inst/m00_nodes/m00_aw_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:8 order:LATE scoped_inst:inst/m00_nodes/m00_b_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:9 order:LATE scoped_inst:inst/m00_nodes/m00_b_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:10 order:LATE scoped_inst:inst/m00_nodes/m00_r_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:11 order:LATE scoped_inst:inst/m00_nodes/m00_r_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:12 order:LATE scoped_inst:inst/m00_nodes/m00_w_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:13 order:LATE scoped_inst:inst/m00_nodes/m00_w_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:14 order:LATE scoped_inst:inst/m01_exit_pipeline/m01_exit/inst/xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:15 order:LATE scoped_inst:inst/m01_nodes/m01_ar_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:16 order:LATE scoped_inst:inst/m01_nodes/m01_ar_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:17 order:LATE scoped_inst:inst/m01_nodes/m01_aw_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:18 order:LATE scoped_inst:inst/m01_nodes/m01_aw_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:19 order:LATE scoped_inst:inst/m01_nodes/m01_b_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:20 order:LATE scoped_inst:inst/m01_nodes/m01_b_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:21 order:LATE scoped_inst:inst/m01_nodes/m01_r_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:22 order:LATE scoped_inst:inst/m01_nodes/m01_r_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:23 order:LATE scoped_inst:inst/m01_nodes/m01_w_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:24 order:LATE scoped_inst:inst/m01_nodes/m01_w_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:25 order:LATE scoped_inst:inst/s00_entry_pipeline/s00_mmu/inst/xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:26 order:LATE scoped_inst:inst/s00_entry_pipeline/s00_si_converter/inst/xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:27 order:LATE scoped_inst:inst/s00_entry_pipeline/s00_transaction_regulator/inst/xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:28 order:LATE scoped_inst:inst/s00_nodes/s00_ar_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:29 order:LATE scoped_inst:inst/s00_nodes/s00_ar_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:30 order:LATE scoped_inst:inst/s00_nodes/s00_aw_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:31 order:LATE scoped_inst:inst/s00_nodes/s00_aw_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:32 order:LATE scoped_inst:inst/s00_nodes/s00_b_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:33 order:LATE scoped_inst:inst/s00_nodes/s00_b_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:34 order:LATE scoped_inst:inst/s00_nodes/s00_r_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:35 order:LATE scoped_inst:inst/s00_nodes/s00_r_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:36 order:LATE scoped_inst:inst/s00_nodes/s00_w_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:37 order:LATE scoped_inst:inst/s00_nodes/s00_w_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:38 order:LATE scoped_inst:inst/switchboards/i_nodes/i_ar_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:39 order:LATE scoped_inst:inst/switchboards/i_nodes/i_ar_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:40 order:LATE scoped_inst:inst/switchboards/i_nodes/i_aw_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:41 order:LATE scoped_inst:inst/switchboards/i_nodes/i_aw_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:42 order:LATE scoped_inst:inst/switchboards/i_nodes/i_b_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:43 order:LATE scoped_inst:inst/switchboards/i_nodes/i_b_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:44 order:LATE scoped_inst:inst/switchboards/i_nodes/i_r_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:45 order:LATE scoped_inst:inst/switchboards/i_nodes/i_r_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:46 order:LATE scoped_inst:inst/switchboards/i_nodes/i_w_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:47 order:LATE scoped_inst:inst/switchboards/i_nodes/i_w_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_single.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_single.tcl id:48 order:LATE scoped_inst:inst/clk_map/psr_aclk/U0/EXT_LPF/ACTIVE_LOW_AUX.ACT_LO_AUX unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alen/AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_single.tcl rfile:../../../../../../../../../../AMD-Xilinx/2025.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_single.tcl id:49 order:LATE scoped_inst:inst/clk_map/psr_aclk/U0/EXT_LPF/ACTIVE_LOW_EXT.ACT_LO_EXT unmanaged:yes} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 20.000 -name aclk [get_ports aclk]
set_property src_info {type:XDC file:2 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m00_exit_pipeline/m00_exit/inst/xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m00_nodes/m00_ar_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m00_nodes/m00_ar_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m00_nodes/m00_aw_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m00_nodes/m00_aw_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m00_nodes/m00_b_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m00_nodes/m00_b_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m00_nodes/m00_r_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:11 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m00_nodes/m00_r_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:12 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m00_nodes/m00_w_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:13 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m00_nodes/m00_w_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:14 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m01_exit_pipeline/m01_exit/inst/xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:15 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m01_nodes/m01_ar_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:16 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m01_nodes/m01_ar_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:17 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m01_nodes/m01_aw_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:18 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m01_nodes/m01_aw_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:19 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m01_nodes/m01_b_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:20 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m01_nodes/m01_b_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:21 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m01_nodes/m01_r_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:22 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m01_nodes/m01_r_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:23 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m01_nodes/m01_w_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:24 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/m01_nodes/m01_w_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:25 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_entry_pipeline/s00_mmu/inst/xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:26 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_entry_pipeline/s00_si_converter/inst/xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:27 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_entry_pipeline/s00_transaction_regulator/inst/xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:28 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_ar_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:29 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_ar_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:30 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_aw_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:31 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_aw_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:32 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_b_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:33 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_b_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:34 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_r_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:35 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_r_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:36 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_w_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:37 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/s00_nodes/s00_w_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:38 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/switchboards/i_nodes/i_ar_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:39 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/switchboards/i_nodes/i_ar_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:40 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/switchboards/i_nodes/i_aw_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:41 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/switchboards/i_nodes/i_aw_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:42 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/switchboards/i_nodes/i_b_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:43 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/switchboards/i_nodes/i_b_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:44 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/switchboards/i_nodes/i_r_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:45 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/switchboards/i_nodes/i_r_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:46 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/switchboards/i_nodes/i_w_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:47 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins inst/switchboards/i_nodes/i_w_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
current_instance inst/clk_map/psr_aclk/U0/EXT_LPF/ACTIVE_LOW_AUX.ACT_LO_AUX
set_property src_info {type:SCOPED_XDC file:48 line:5 export:INPUT save:NONE read:READ} [current_design]
set_false_path -to [get_cells {syncstages_ff_reg[0]}]
current_instance
current_instance inst/clk_map/psr_aclk/U0/EXT_LPF/ACTIVE_LOW_EXT.ACT_LO_EXT
set_property src_info {type:SCOPED_XDC file:49 line:5 export:INPUT save:NONE read:READ} [current_design]
set_false_path -to [get_cells {syncstages_ff_reg[0]}]
