domain_path: /home/alen/git/AMD-FPGA-Practice/zybo-z7-audio/sw/audio-pipe-sw-v0/zybo-z7-audio/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /home/alen/AMD-Xilinx/2025.2/Vitis/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
lang: c
