-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bd_8126_hsc_0_v_csc_core_Pipeline_VITIS_LOOP_2080_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stream_scaled_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    stream_scaled_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_scaled_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_scaled_empty_n : IN STD_LOGIC;
    stream_scaled_read : OUT STD_LOGIC;
    stream_scaled_csc_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    stream_scaled_csc_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_scaled_csc_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_scaled_csc_full_n : IN STD_LOGIC;
    stream_scaled_csc_write : OUT STD_LOGIC;
    empty : IN STD_LOGIC_VECTOR (10 downto 0);
    cmp74 : IN STD_LOGIC_VECTOR (0 downto 0);
    bPassThru_read : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of bd_8126_hsc_0_v_csc_core_Pipeline_VITIS_LOOP_2080_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv17_132 : STD_LOGIC_VECTOR (16 downto 0) := "00000000100110010";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv20_6C5 : STD_LOGIC_VECTOR (19 downto 0) := "00000000011011000101";
    constant ap_const_lv18_253 : STD_LOGIC_VECTOR (17 downto 0) := "000000001001010011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv21_821 : STD_LOGIC_VECTOR (20 downto 0) := "000000000100000100001";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv11_FF : STD_LOGIC_VECTOR (10 downto 0) := "00011111111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv20_382 : STD_LOGIC_VECTOR (19 downto 0) := "00000000001110000010";
    constant ap_const_lv10_FF : STD_LOGIC_VECTOR (9 downto 0) := "0011111111";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv10_80 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_const_lv11_80 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_const_lv9_FF : STD_LOGIC_VECTOR (8 downto 0) := "011111111";
    constant ap_const_lv12_FF : STD_LOGIC_VECTOR (11 downto 0) := "000011111111";
    constant ap_const_lv15_75 : STD_LOGIC_VECTOR (14 downto 0) := "000000001110101";
    constant ap_const_lv18_259 : STD_LOGIC_VECTOR (17 downto 0) := "000000001001011001";
    constant ap_const_lv18_194 : STD_LOGIC_VECTOR (17 downto 0) := "000000000110010100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln2080_fu_162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal stream_scaled_csc_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal stream_scaled_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal r_y_fu_179_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_y_reg_623 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_y_reg_623_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal r_y_reg_623_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal r_y_reg_623_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal r_y_reg_623_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal g_u_reg_632 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_u_reg_632_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_193_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_reg_638 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_reg_638_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_reg_638_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_reg_638_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln2101_fu_213_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln2101_reg_654 : STD_LOGIC_VECTOR (16 downto 0);
    signal Cb_fu_232_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Cb_reg_669 : STD_LOGIC_VECTOR (7 downto 0);
    signal Cb_reg_669_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln_reg_679 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_247_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln2097_1_reg_684 : STD_LOGIC_VECTOR (17 downto 0);
    signal sub_ln2102_fu_310_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln2102_reg_699 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln2103_fu_316_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln2103_reg_705 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln2105_fu_329_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln2105_reg_710 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln2105_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln2105_reg_715 : STD_LOGIC_VECTOR (0 downto 0);
    signal g_fu_358_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal g_reg_720 : STD_LOGIC_VECTOR (9 downto 0);
    signal b_fu_378_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal b_reg_725 : STD_LOGIC_VECTOR (11 downto 0);
    signal b_reg_725_pp0_iter7_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln8_reg_730 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln2105_2_fu_447_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln2105_2_reg_740 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln2105_2_reg_740_pp0_iter7_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln2105_2_reg_740_pp0_iter8_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal v_fu_478_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal v_reg_745 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln2107_fu_490_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln2107_reg_750 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln2107_fu_494_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln2107_reg_755 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln2107_2_fu_519_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln2107_2_reg_760 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln2109_1_fu_551_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln2109_1_reg_765 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln2109_1_fu_557_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln2109_1_reg_770 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_fu_118 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal x_4_fu_168_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_3 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal p_0_fu_567_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln2101_fu_213_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln2101_fu_213_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal Cr_fu_219_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_241_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_247_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_241_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_fu_576_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln2096_fu_278_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln2096_4_fu_275_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_287_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_584_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_2_fu_293_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln2094_fu_266_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln2101_3_fu_306_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln2096_fu_272_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal r_fu_281_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln2101_2_fu_302_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln2105_fu_322_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_593_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln6_fu_345_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln2096_3_fu_342_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln2097_1_fu_354_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_287_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln7_fu_364_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln2098_fu_374_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln2096_2_fu_339_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln_fu_384_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln2102_1_fu_395_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln2102_fu_391_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln2102_1_fu_402_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln2102_1_fu_406_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_425_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln2105_1_fu_431_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln2105_1_fu_437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln2105_1_fu_443_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln2102_2_fu_455_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_425_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal trunc_ln9_fu_464_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln2103_1_fu_474_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal u_fu_458_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln2107_fu_484_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln2107_1_fu_503_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln2107_1_fu_509_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln2107_1_fu_515_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln2103_2_fu_500_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln2109_fu_527_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln2109_fu_537_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln2109_fu_533_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln2109_1_fu_543_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln2109_2_fu_561_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_576_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_576_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_584_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_584_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_584_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_593_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_241_ce : STD_LOGIC;
    signal grp_fu_247_ce : STD_LOGIC;
    signal grp_fu_287_ce : STD_LOGIC;
    signal grp_fu_425_ce : STD_LOGIC;
    signal grp_fu_576_ce : STD_LOGIC;
    signal grp_fu_584_ce : STD_LOGIC;
    signal grp_fu_593_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_576_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_584_p00 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_584_p20 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln2101_fu_213_p00 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_condition_639 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component bd_8126_hsc_0_mul_8ns_10ns_17_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component bd_8126_hsc_0_mul_8s_12ns_20_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (19 downto 0) );
    end component;


    component bd_8126_hsc_0_mul_8s_11ns_18_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component bd_8126_hsc_0_mul_8s_13ns_21_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (20 downto 0) );
    end component;


    component bd_8126_hsc_0_mul_9s_11ns_20_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (19 downto 0) );
    end component;


    component bd_8126_hsc_0_mac_muladd_8ns_7ns_17ns_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component bd_8126_hsc_0_mac_muladd_8ns_10ns_17ns_18_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        din2 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component bd_8126_hsc_0_mac_muladd_8s_9ns_18s_18_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        din2 : IN STD_LOGIC_VECTOR (17 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component bd_8126_hsc_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_8ns_10ns_17_1_1_U222 : component bd_8126_hsc_0_mul_8ns_10ns_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 10,
        dout_WIDTH => 17)
    port map (
        din0 => mul_ln2101_fu_213_p0,
        din1 => mul_ln2101_fu_213_p1,
        dout => mul_ln2101_fu_213_p2);

    mul_8s_12ns_20_2_1_U223 : component bd_8126_hsc_0_mul_8s_12ns_20_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 8,
        din1_WIDTH => 12,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => Cr_fu_219_p2,
        din1 => grp_fu_241_p1,
        ce => grp_fu_241_ce,
        dout => grp_fu_241_p2);

    mul_8s_11ns_18_2_1_U224 : component bd_8126_hsc_0_mul_8s_11ns_18_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 8,
        din1_WIDTH => 11,
        dout_WIDTH => 18)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => Cr_fu_219_p2,
        din1 => grp_fu_247_p1,
        ce => grp_fu_247_ce,
        dout => grp_fu_247_p2);

    mul_8s_13ns_21_2_1_U225 : component bd_8126_hsc_0_mul_8s_13ns_21_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 8,
        din1_WIDTH => 13,
        dout_WIDTH => 21)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => Cb_reg_669_pp0_iter4_reg,
        din1 => grp_fu_287_p1,
        ce => grp_fu_287_ce,
        dout => grp_fu_287_p2);

    mul_9s_11ns_20_2_1_U226 : component bd_8126_hsc_0_mul_9s_11ns_20_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 9,
        din1_WIDTH => 11,
        dout_WIDTH => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sub_ln2103_reg_705,
        din1 => grp_fu_425_p1,
        ce => grp_fu_425_ce,
        dout => grp_fu_425_p2);

    mac_muladd_8ns_7ns_17ns_17_4_1_U227 : component bd_8126_hsc_0_mac_muladd_8ns_7ns_17ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        din2_WIDTH => 17,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_576_p0,
        din1 => grp_fu_576_p1,
        din2 => mul_ln2101_reg_654,
        ce => grp_fu_576_ce,
        dout => grp_fu_576_p3);

    mac_muladd_8ns_10ns_17ns_18_4_1_U228 : component bd_8126_hsc_0_mac_muladd_8ns_10ns_17ns_18_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 10,
        din2_WIDTH => 17,
        dout_WIDTH => 18)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_584_p0,
        din1 => grp_fu_584_p1,
        din2 => grp_fu_584_p2,
        ce => grp_fu_584_ce,
        dout => grp_fu_584_p3);

    mac_muladd_8s_9ns_18s_18_4_1_U229 : component bd_8126_hsc_0_mac_muladd_8s_9ns_18s_18_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 9,
        din2_WIDTH => 18,
        dout_WIDTH => 18)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => Cb_fu_232_p2,
        din1 => grp_fu_593_p1,
        din2 => mul_ln2097_1_reg_684,
        ce => grp_fu_593_ce,
        dout => grp_fu_593_p3);

    flow_control_loop_pipe_sequential_init_U : component bd_8126_hsc_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    x_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln2080_fu_162_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    x_fu_118 <= x_4_fu_168_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_118 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                Cb_reg_669 <= Cb_fu_232_p2;
                Cb_reg_669_pp0_iter4_reg <= Cb_reg_669;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                b_reg_725 <= b_fu_378_p2;
                b_reg_725_pp0_iter7_reg <= b_reg_725;
                g_reg_720 <= g_fu_358_p2;
                g_u_reg_632_pp0_iter2_reg <= g_u_reg_632;
                icmp_ln2105_reg_715 <= icmp_ln2105_fu_333_p2;
                icmp_ln2107_reg_755 <= icmp_ln2107_fu_494_p2;
                icmp_ln2109_1_reg_765 <= icmp_ln2109_1_fu_551_p2;
                mul_ln2097_1_reg_684 <= grp_fu_247_p2;
                mul_ln2101_reg_654 <= mul_ln2101_fu_213_p2;
                r_y_reg_623_pp0_iter2_reg <= r_y_reg_623;
                r_y_reg_623_pp0_iter3_reg <= r_y_reg_623_pp0_iter2_reg;
                r_y_reg_623_pp0_iter4_reg <= r_y_reg_623_pp0_iter3_reg;
                r_y_reg_623_pp0_iter5_reg <= r_y_reg_623_pp0_iter4_reg;
                select_ln2105_2_reg_740 <= select_ln2105_2_fu_447_p3;
                select_ln2105_2_reg_740_pp0_iter7_reg <= select_ln2105_2_reg_740;
                select_ln2105_2_reg_740_pp0_iter8_reg <= select_ln2105_2_reg_740_pp0_iter7_reg;
                select_ln2107_2_reg_760 <= select_ln2107_2_fu_519_p3;
                sub_ln2102_reg_699 <= sub_ln2102_fu_310_p2;
                sub_ln2103_reg_705 <= sub_ln2103_fu_316_p2;
                tmp_reg_638_pp0_iter2_reg <= tmp_reg_638;
                tmp_reg_638_pp0_iter3_reg <= tmp_reg_638_pp0_iter2_reg;
                tmp_reg_638_pp0_iter4_reg <= tmp_reg_638_pp0_iter3_reg;
                trunc_ln2105_reg_710 <= trunc_ln2105_fu_329_p1;
                trunc_ln2107_reg_750 <= trunc_ln2107_fu_490_p1;
                trunc_ln2109_1_reg_770 <= trunc_ln2109_1_fu_557_p1;
                trunc_ln8_reg_730 <= sub_ln2102_1_fu_406_p2(18 downto 10);
                trunc_ln_reg_679 <= grp_fu_241_p2(19 downto 10);
                v_reg_745 <= v_fu_478_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                g_u_reg_632 <= stream_scaled_dout(15 downto 8);
                r_y_reg_623 <= r_y_fu_179_p1;
                tmp_reg_638 <= stream_scaled_dout(23 downto 16);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Cb_fu_232_p2 <= (g_u_reg_632_pp0_iter2_reg xor ap_const_lv8_80);
    Cr_fu_219_p2 <= (tmp_reg_638_pp0_iter2_reg xor ap_const_lv8_80);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, ap_block_state2_pp0_stage0_iter1, ap_block_state10_pp0_stage0_iter9)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, ap_block_state2_pp0_stage0_iter1, ap_block_state10_pp0_stage0_iter9)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, ap_block_state2_pp0_stage0_iter1, ap_block_state10_pp0_stage0_iter9)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_state10_pp0_stage0_iter9_assign_proc : process(stream_scaled_csc_full_n, bPassThru_read)
    begin
                ap_block_state10_pp0_stage0_iter9 <= ((bPassThru_read = ap_const_lv1_0) and (stream_scaled_csc_full_n = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(stream_scaled_empty_n, stream_scaled_csc_full_n, bPassThru_read)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((stream_scaled_empty_n = ap_const_logic_0) or ((bPassThru_read = ap_const_lv1_1) and (stream_scaled_csc_full_n = ap_const_logic_0)));
    end process;


    ap_condition_639_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, bPassThru_read)
    begin
                ap_condition_639 <= ((bPassThru_read = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln2080_fu_162_p2)
    begin
        if (((icmp_ln2080_fu_162_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_x_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, x_fu_118, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_x_3 <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_x_3 <= x_fu_118;
        end if; 
    end process;

    b_fu_378_p2 <= std_logic_vector(signed(sext_ln2098_fu_374_p1) + signed(zext_ln2096_2_fu_339_p1));
    g_fu_358_p2 <= std_logic_vector(unsigned(zext_ln2096_3_fu_342_p1) - unsigned(sext_ln2097_1_fu_354_p1));

    grp_fu_241_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_241_ce <= ap_const_logic_1;
        else 
            grp_fu_241_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_241_p1 <= ap_const_lv20_6C5(12 - 1 downto 0);

    grp_fu_247_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_247_ce <= ap_const_logic_1;
        else 
            grp_fu_247_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_247_p1 <= ap_const_lv18_253(11 - 1 downto 0);

    grp_fu_287_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_287_ce <= ap_const_logic_1;
        else 
            grp_fu_287_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_287_p1 <= ap_const_lv21_821(13 - 1 downto 0);

    grp_fu_425_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_425_ce <= ap_const_logic_1;
        else 
            grp_fu_425_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_425_p1 <= ap_const_lv20_382(11 - 1 downto 0);

    grp_fu_576_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_576_ce <= ap_const_logic_1;
        else 
            grp_fu_576_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_576_p0 <= grp_fu_576_p00(8 - 1 downto 0);
    grp_fu_576_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_193_p4),15));
    grp_fu_576_p1 <= ap_const_lv15_75(7 - 1 downto 0);

    grp_fu_584_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_584_ce <= ap_const_logic_1;
        else 
            grp_fu_584_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_584_p0 <= grp_fu_584_p00(8 - 1 downto 0);
    grp_fu_584_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(g_u_reg_632),18));
    grp_fu_584_p1 <= ap_const_lv18_259(10 - 1 downto 0);
    grp_fu_584_p2 <= grp_fu_584_p20(17 - 1 downto 0);
    grp_fu_584_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_576_p3),18));

    grp_fu_593_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_593_ce <= ap_const_logic_1;
        else 
            grp_fu_593_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_593_p1 <= ap_const_lv18_194(9 - 1 downto 0);
    icmp_ln2080_fu_162_p2 <= "1" when (ap_sig_allocacmp_x_3 = empty) else "0";
    icmp_ln2105_1_fu_437_p2 <= "1" when (signed(select_ln2105_1_fu_431_p3) > signed(ap_const_lv10_0)) else "0";
    icmp_ln2105_fu_333_p2 <= "1" when (signed(select_ln2105_fu_322_p3) < signed(ap_const_lv11_FF)) else "0";
    icmp_ln2107_1_fu_509_p2 <= "1" when (signed(select_ln2107_1_fu_503_p3) > signed(ap_const_lv9_0)) else "0";
    icmp_ln2107_fu_494_p2 <= "1" when (signed(select_ln2107_fu_484_p3) < signed(ap_const_lv10_FF)) else "0";
    icmp_ln2109_1_fu_551_p2 <= "1" when (signed(select_ln2109_1_fu_543_p3) > signed(ap_const_lv11_0)) else "0";
    icmp_ln2109_fu_537_p2 <= "1" when (signed(select_ln2109_fu_527_p3) < signed(ap_const_lv12_FF)) else "0";
    mul_ln2101_fu_213_p0 <= mul_ln2101_fu_213_p00(8 - 1 downto 0);
    mul_ln2101_fu_213_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_y_reg_623),17));
    mul_ln2101_fu_213_p1 <= ap_const_lv17_132(10 - 1 downto 0);
    p_0_fu_567_p4 <= ((select_ln2109_2_fu_561_p3 & select_ln2107_2_reg_760) & select_ln2105_2_reg_740_pp0_iter8_reg);
    r_fu_281_p2 <= std_logic_vector(signed(sext_ln2096_fu_278_p1) + signed(zext_ln2096_4_fu_275_p1));
    r_y_fu_179_p1 <= stream_scaled_dout(8 - 1 downto 0);
    select_ln2105_1_fu_431_p3 <= 
        trunc_ln2105_reg_710 when (icmp_ln2105_reg_715(0) = '1') else 
        ap_const_lv10_FF;
    select_ln2105_2_fu_447_p3 <= 
        trunc_ln2105_1_fu_443_p1 when (icmp_ln2105_1_fu_437_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln2105_fu_322_p3 <= 
        r_fu_281_p2 when (cmp74(0) = '1') else 
        zext_ln2101_2_fu_302_p1;
    select_ln2107_1_fu_503_p3 <= 
        trunc_ln2107_reg_750 when (icmp_ln2107_reg_755(0) = '1') else 
        ap_const_lv9_FF;
    select_ln2107_2_fu_519_p3 <= 
        trunc_ln2107_1_fu_515_p1 when (icmp_ln2107_1_fu_509_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln2107_fu_484_p3 <= 
        g_reg_720 when (cmp74(0) = '1') else 
        u_fu_458_p2;
    select_ln2109_1_fu_543_p3 <= 
        trunc_ln2109_fu_533_p1 when (icmp_ln2109_fu_537_p2(0) = '1') else 
        ap_const_lv11_FF;
    select_ln2109_2_fu_561_p3 <= 
        trunc_ln2109_1_reg_770 when (icmp_ln2109_1_reg_765(0) = '1') else 
        ap_const_lv8_0;
    select_ln2109_fu_527_p3 <= 
        b_reg_725_pp0_iter7_reg when (cmp74(0) = '1') else 
        sext_ln2103_2_fu_500_p1;
        sext_ln2096_fu_278_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_reg_679),11));

        sext_ln2097_1_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln6_fu_345_p4),10));

        sext_ln2098_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln7_fu_364_p4),12));

        sext_ln2102_1_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln2102_1_fu_395_p3),19));

        sext_ln2102_2_fu_455_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln8_reg_730),10));

        sext_ln2102_fu_391_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_384_p3),19));

        sext_ln2103_1_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln9_fu_464_p4),11));

        sext_ln2103_2_fu_500_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(v_reg_745),12));

    shl_ln2102_1_fu_395_p3 <= (sub_ln2102_reg_699 & ap_const_lv3_0);
    shl_ln_fu_384_p3 <= (sub_ln2102_reg_699 & ap_const_lv9_0);

    stream_scaled_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, stream_scaled_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_scaled_blk_n <= stream_scaled_empty_n;
        else 
            stream_scaled_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_scaled_csc_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, stream_scaled_csc_full_n, bPassThru_read, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (bPassThru_read = ap_const_lv1_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (bPassThru_read = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            stream_scaled_csc_blk_n <= stream_scaled_csc_full_n;
        else 
            stream_scaled_csc_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_scaled_csc_din_assign_proc : process(ap_enable_reg_pp0_iter9, stream_scaled_dout, bPassThru_read, ap_block_pp0_stage0_01001, p_0_fu_567_p4, ap_condition_639)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_01001)) then
            if (((bPassThru_read = ap_const_lv1_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
                stream_scaled_csc_din <= p_0_fu_567_p4;
            elsif ((ap_const_boolean_1 = ap_condition_639)) then 
                stream_scaled_csc_din <= stream_scaled_dout;
            else 
                stream_scaled_csc_din <= "XXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            stream_scaled_csc_din <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    stream_scaled_csc_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, bPassThru_read, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (bPassThru_read = ap_const_lv1_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (bPassThru_read = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            stream_scaled_csc_write <= ap_const_logic_1;
        else 
            stream_scaled_csc_write <= ap_const_logic_0;
        end if; 
    end process;


    stream_scaled_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_scaled_read <= ap_const_logic_1;
        else 
            stream_scaled_read <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln2102_1_fu_406_p2 <= std_logic_vector(signed(sext_ln2102_fu_391_p1) - signed(sext_ln2102_1_fu_402_p1));
    sub_ln2102_fu_310_p2 <= std_logic_vector(unsigned(zext_ln2094_fu_266_p1) - unsigned(zext_ln2101_3_fu_306_p1));
    sub_ln2103_fu_316_p2 <= std_logic_vector(unsigned(zext_ln2096_fu_272_p1) - unsigned(zext_ln2101_3_fu_306_p1));
    tmp_2_fu_293_p4 <= grp_fu_584_p3(17 downto 10);
    tmp_fu_193_p4 <= stream_scaled_dout(23 downto 16);
    trunc_ln2105_1_fu_443_p1 <= select_ln2105_1_fu_431_p3(8 - 1 downto 0);
    trunc_ln2105_fu_329_p1 <= select_ln2105_fu_322_p3(10 - 1 downto 0);
    trunc_ln2107_1_fu_515_p1 <= select_ln2107_1_fu_503_p3(8 - 1 downto 0);
    trunc_ln2107_fu_490_p1 <= select_ln2107_fu_484_p3(9 - 1 downto 0);
    trunc_ln2109_1_fu_557_p1 <= select_ln2109_1_fu_543_p3(8 - 1 downto 0);
    trunc_ln2109_fu_533_p1 <= select_ln2109_fu_527_p3(11 - 1 downto 0);
    trunc_ln6_fu_345_p4 <= grp_fu_593_p3(17 downto 10);
    trunc_ln7_fu_364_p4 <= grp_fu_287_p2(20 downto 10);
    trunc_ln9_fu_464_p4 <= grp_fu_425_p2(19 downto 10);
    u_fu_458_p2 <= std_logic_vector(signed(sext_ln2102_2_fu_455_p1) + signed(ap_const_lv10_80));
    v_fu_478_p2 <= std_logic_vector(signed(sext_ln2103_1_fu_474_p1) + signed(ap_const_lv11_80));
    x_4_fu_168_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_x_3) + unsigned(ap_const_lv11_1));
    zext_ln2094_fu_266_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_638_pp0_iter4_reg),9));
    zext_ln2096_2_fu_339_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_y_reg_623_pp0_iter5_reg),12));
    zext_ln2096_3_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_y_reg_623_pp0_iter5_reg),10));
    zext_ln2096_4_fu_275_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_y_reg_623_pp0_iter4_reg),11));
    zext_ln2096_fu_272_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_y_reg_623_pp0_iter4_reg),9));
    zext_ln2101_2_fu_302_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_293_p4),11));
    zext_ln2101_3_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_293_p4),9));
end behav;
