// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module clahe_accel_process_i (
        imgOutput_data_din,
        imgOutput_data_full_n,
        imgOutput_data_write,
        imgInput_data_dout,
        imgInput_data_empty_n,
        imgInput_data_read,
        Tile_0_val3,
        Tile_2_val5,
        Tile_3_val6,
        Tile_4_val7,
        Tile_5_val9,
        Tile_6_val11,
        Tile_8_val14,
        p_lutw_0_address0,
        p_lutw_0_ce0,
        p_lutw_0_d0,
        p_lutw_0_q0,
        p_lutw_0_we0,
        p_lutw_0_address1,
        p_lutw_0_ce1,
        p_lutw_0_d1,
        p_lutw_0_q1,
        p_lutw_0_we1,
        p_lutw_1_address0,
        p_lutw_1_ce0,
        p_lutw_1_d0,
        p_lutw_1_q0,
        p_lutw_1_we0,
        p_lutw_1_address1,
        p_lutw_1_ce1,
        p_lutw_1_d1,
        p_lutw_1_q1,
        p_lutw_1_we1,
        p_lutr_0_address0,
        p_lutr_0_ce0,
        p_lutr_0_d0,
        p_lutr_0_q0,
        p_lutr_0_we0,
        p_lutr_0_address1,
        p_lutr_0_ce1,
        p_lutr_0_d1,
        p_lutr_0_q1,
        p_lutr_0_we1,
        p_lutr_1_address0,
        p_lutr_1_ce0,
        p_lutr_1_d0,
        p_lutr_1_q0,
        p_lutr_1_we0,
        p_lutr_1_address1,
        p_lutr_1_ce1,
        p_lutr_1_d1,
        p_lutr_1_q1,
        p_lutr_1_we1,
        ap_clk,
        ap_rst,
        Tile_0_val3_ap_vld,
        Tile_2_val5_ap_vld,
        Tile_5_val9_ap_vld,
        Tile_6_val11_ap_vld,
        Tile_8_val14_ap_vld,
        ap_start,
        ap_done,
        Tile_3_val6_ap_vld,
        Tile_4_val7_ap_vld,
        ap_ready,
        ap_idle,
        ap_continue
);


output  [7:0] imgOutput_data_din;
input   imgOutput_data_full_n;
output   imgOutput_data_write;
input  [7:0] imgInput_data_dout;
input   imgInput_data_empty_n;
output   imgInput_data_read;
input  [10:0] Tile_0_val3;
input  [10:0] Tile_2_val5;
input  [31:0] Tile_3_val6;
input  [31:0] Tile_4_val7;
input  [12:0] Tile_5_val9;
input  [12:0] Tile_6_val11;
input  [18:0] Tile_8_val14;
output  [13:0] p_lutw_0_address0;
output   p_lutw_0_ce0;
output  [15:0] p_lutw_0_d0;
input  [15:0] p_lutw_0_q0;
output   p_lutw_0_we0;
output  [13:0] p_lutw_0_address1;
output   p_lutw_0_ce1;
output  [15:0] p_lutw_0_d1;
input  [15:0] p_lutw_0_q1;
output   p_lutw_0_we1;
output  [13:0] p_lutw_1_address0;
output   p_lutw_1_ce0;
output  [15:0] p_lutw_1_d0;
input  [15:0] p_lutw_1_q0;
output   p_lutw_1_we0;
output  [13:0] p_lutw_1_address1;
output   p_lutw_1_ce1;
output  [15:0] p_lutw_1_d1;
input  [15:0] p_lutw_1_q1;
output   p_lutw_1_we1;
output  [13:0] p_lutr_0_address0;
output   p_lutr_0_ce0;
output  [15:0] p_lutr_0_d0;
input  [15:0] p_lutr_0_q0;
output   p_lutr_0_we0;
output  [13:0] p_lutr_0_address1;
output   p_lutr_0_ce1;
output  [15:0] p_lutr_0_d1;
input  [15:0] p_lutr_0_q1;
output   p_lutr_0_we1;
output  [13:0] p_lutr_1_address0;
output   p_lutr_1_ce0;
output  [15:0] p_lutr_1_d0;
input  [15:0] p_lutr_1_q0;
output   p_lutr_1_we0;
output  [13:0] p_lutr_1_address1;
output   p_lutr_1_ce1;
output  [15:0] p_lutr_1_d1;
input  [15:0] p_lutr_1_q1;
output   p_lutr_1_we1;
input   ap_clk;
input   ap_rst;
input   Tile_0_val3_ap_vld;
input   Tile_2_val5_ap_vld;
input   Tile_5_val9_ap_vld;
input   Tile_6_val11_ap_vld;
input   Tile_8_val14_ap_vld;
input   ap_start;
output   ap_done;
input   Tile_3_val6_ap_vld;
input   Tile_4_val7_ap_vld;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    populateLut_U0_ap_start;
wire    populateLut_U0_ap_done;
wire    populateLut_U0_ap_continue;
wire    populateLut_U0_ap_idle;
wire    populateLut_U0_ap_ready;
wire    populateLut_U0_imgInput_data_read;
wire   [7:0] populateLut_U0_in_copy_data_din;
wire    populateLut_U0_in_copy_data_write;
wire   [13:0] populateLut_U0_p_lut_0_address0;
wire    populateLut_U0_p_lut_0_ce0;
wire    populateLut_U0_p_lut_0_we0;
wire   [15:0] populateLut_U0_p_lut_0_d0;
wire   [13:0] populateLut_U0_p_lut_0_address1;
wire    populateLut_U0_p_lut_0_ce1;
wire   [13:0] populateLut_U0_p_lut_1_address0;
wire    populateLut_U0_p_lut_1_ce0;
wire    populateLut_U0_p_lut_1_we0;
wire   [15:0] populateLut_U0_p_lut_1_d0;
wire   [13:0] populateLut_U0_p_lut_1_address1;
wire    populateLut_U0_p_lut_1_ce1;
wire    ap_sync_continue;
wire    interpolate_U0_ap_start;
wire    interpolate_U0_ap_done;
wire    interpolate_U0_ap_continue;
wire    interpolate_U0_ap_idle;
wire    interpolate_U0_ap_ready;
wire    interpolate_U0_in_copy_data_read;
wire   [13:0] interpolate_U0_p_lut_0_address0;
wire    interpolate_U0_p_lut_0_ce0;
wire   [13:0] interpolate_U0_p_lut_0_address1;
wire    interpolate_U0_p_lut_0_ce1;
wire   [13:0] interpolate_U0_p_lut_1_address0;
wire    interpolate_U0_p_lut_1_ce0;
wire   [13:0] interpolate_U0_p_lut_1_address1;
wire    interpolate_U0_p_lut_1_ce1;
wire   [7:0] interpolate_U0_imgOutput_data_din;
wire    interpolate_U0_imgOutput_data_write;
wire    in_copy_data_full_n;
wire   [7:0] in_copy_data_dout;
wire   [2:0] in_copy_data_num_data_valid;
wire   [2:0] in_copy_data_fifo_cap;
wire    in_copy_data_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_populateLut_U0_ap_ready;
wire    ap_sync_populateLut_U0_ap_ready;
reg    ap_sync_reg_interpolate_U0_ap_ready;
wire    ap_sync_interpolate_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_populateLut_U0_ap_ready = 1'b0;
#0 ap_sync_reg_interpolate_U0_ap_ready = 1'b0;
end

clahe_accel_populateLut populateLut_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(populateLut_U0_ap_start),
    .ap_done(populateLut_U0_ap_done),
    .ap_continue(populateLut_U0_ap_continue),
    .ap_idle(populateLut_U0_ap_idle),
    .ap_ready(populateLut_U0_ap_ready),
    .imgInput_data_dout(imgInput_data_dout),
    .imgInput_data_num_data_valid(3'd0),
    .imgInput_data_fifo_cap(3'd0),
    .imgInput_data_empty_n(imgInput_data_empty_n),
    .imgInput_data_read(populateLut_U0_imgInput_data_read),
    .Tile_0_val1(Tile_0_val3),
    .Tile_2_val2(Tile_2_val5),
    .Tile_5_val4(Tile_5_val9),
    .Tile_6_val5(Tile_6_val11),
    .Tile_8_val8(Tile_8_val14),
    .in_copy_data_din(populateLut_U0_in_copy_data_din),
    .in_copy_data_num_data_valid(in_copy_data_num_data_valid),
    .in_copy_data_fifo_cap(in_copy_data_fifo_cap),
    .in_copy_data_full_n(in_copy_data_full_n),
    .in_copy_data_write(populateLut_U0_in_copy_data_write),
    .p_lut_0_address0(populateLut_U0_p_lut_0_address0),
    .p_lut_0_ce0(populateLut_U0_p_lut_0_ce0),
    .p_lut_0_we0(populateLut_U0_p_lut_0_we0),
    .p_lut_0_d0(populateLut_U0_p_lut_0_d0),
    .p_lut_0_q0(p_lutw_0_q0),
    .p_lut_0_address1(populateLut_U0_p_lut_0_address1),
    .p_lut_0_ce1(populateLut_U0_p_lut_0_ce1),
    .p_lut_0_q1(p_lutw_0_q1),
    .p_lut_1_address0(populateLut_U0_p_lut_1_address0),
    .p_lut_1_ce0(populateLut_U0_p_lut_1_ce0),
    .p_lut_1_we0(populateLut_U0_p_lut_1_we0),
    .p_lut_1_d0(populateLut_U0_p_lut_1_d0),
    .p_lut_1_q0(p_lutw_1_q0),
    .p_lut_1_address1(populateLut_U0_p_lut_1_address1),
    .p_lut_1_ce1(populateLut_U0_p_lut_1_ce1),
    .p_lut_1_q1(p_lutw_1_q1)
);

clahe_accel_interpolate interpolate_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(interpolate_U0_ap_start),
    .ap_done(interpolate_U0_ap_done),
    .ap_continue(interpolate_U0_ap_continue),
    .ap_idle(interpolate_U0_ap_idle),
    .ap_ready(interpolate_U0_ap_ready),
    .in_copy_data_dout(in_copy_data_dout),
    .in_copy_data_num_data_valid(in_copy_data_num_data_valid),
    .in_copy_data_fifo_cap(in_copy_data_fifo_cap),
    .in_copy_data_empty_n(in_copy_data_empty_n),
    .in_copy_data_read(interpolate_U0_in_copy_data_read),
    .Tile_0_val(Tile_0_val3),
    .Tile_2_val(Tile_2_val5),
    .Tile_3_val(Tile_3_val6),
    .Tile_4_val(Tile_4_val7),
    .Tile_5_val(Tile_5_val9),
    .Tile_6_val(Tile_6_val11),
    .p_lut_0_address0(interpolate_U0_p_lut_0_address0),
    .p_lut_0_ce0(interpolate_U0_p_lut_0_ce0),
    .p_lut_0_q0(p_lutr_0_q0),
    .p_lut_0_address1(interpolate_U0_p_lut_0_address1),
    .p_lut_0_ce1(interpolate_U0_p_lut_0_ce1),
    .p_lut_0_q1(p_lutr_0_q1),
    .p_lut_1_address0(interpolate_U0_p_lut_1_address0),
    .p_lut_1_ce0(interpolate_U0_p_lut_1_ce0),
    .p_lut_1_q0(p_lutr_1_q0),
    .p_lut_1_address1(interpolate_U0_p_lut_1_address1),
    .p_lut_1_ce1(interpolate_U0_p_lut_1_ce1),
    .p_lut_1_q1(p_lutr_1_q1),
    .imgOutput_data_din(interpolate_U0_imgOutput_data_din),
    .imgOutput_data_num_data_valid(3'd0),
    .imgOutput_data_fifo_cap(3'd0),
    .imgOutput_data_full_n(imgOutput_data_full_n),
    .imgOutput_data_write(interpolate_U0_imgOutput_data_write)
);

clahe_accel_fifo_w8_d2_S in_copy_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(populateLut_U0_in_copy_data_din),
    .if_full_n(in_copy_data_full_n),
    .if_write(populateLut_U0_in_copy_data_write),
    .if_dout(in_copy_data_dout),
    .if_num_data_valid(in_copy_data_num_data_valid),
    .if_fifo_cap(in_copy_data_fifo_cap),
    .if_empty_n(in_copy_data_empty_n),
    .if_read(interpolate_U0_in_copy_data_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_interpolate_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_interpolate_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_interpolate_U0_ap_ready <= ap_sync_interpolate_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_populateLut_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_populateLut_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_populateLut_U0_ap_ready <= ap_sync_populateLut_U0_ap_ready;
        end
    end
end

assign ap_done = ap_sync_done;

assign ap_idle = (populateLut_U0_ap_idle & interpolate_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_continue = (ap_sync_done & ap_continue);

assign ap_sync_done = (populateLut_U0_ap_done & interpolate_U0_ap_done);

assign ap_sync_interpolate_U0_ap_ready = (interpolate_U0_ap_ready | ap_sync_reg_interpolate_U0_ap_ready);

assign ap_sync_populateLut_U0_ap_ready = (populateLut_U0_ap_ready | ap_sync_reg_populateLut_U0_ap_ready);

assign ap_sync_ready = (ap_sync_populateLut_U0_ap_ready & ap_sync_interpolate_U0_ap_ready);

assign imgInput_data_read = populateLut_U0_imgInput_data_read;

assign imgOutput_data_din = interpolate_U0_imgOutput_data_din;

assign imgOutput_data_write = interpolate_U0_imgOutput_data_write;

assign interpolate_U0_ap_continue = ap_sync_continue;

assign interpolate_U0_ap_start = ((ap_sync_reg_interpolate_U0_ap_ready ^ 1'b1) & ap_start);

assign p_lutr_0_address0 = interpolate_U0_p_lut_0_address0;

assign p_lutr_0_address1 = interpolate_U0_p_lut_0_address1;

assign p_lutr_0_ce0 = interpolate_U0_p_lut_0_ce0;

assign p_lutr_0_ce1 = interpolate_U0_p_lut_0_ce1;

assign p_lutr_0_d0 = 16'd0;

assign p_lutr_0_d1 = 16'd0;

assign p_lutr_0_we0 = 1'b0;

assign p_lutr_0_we1 = 1'b0;

assign p_lutr_1_address0 = interpolate_U0_p_lut_1_address0;

assign p_lutr_1_address1 = interpolate_U0_p_lut_1_address1;

assign p_lutr_1_ce0 = interpolate_U0_p_lut_1_ce0;

assign p_lutr_1_ce1 = interpolate_U0_p_lut_1_ce1;

assign p_lutr_1_d0 = 16'd0;

assign p_lutr_1_d1 = 16'd0;

assign p_lutr_1_we0 = 1'b0;

assign p_lutr_1_we1 = 1'b0;

assign p_lutw_0_address0 = populateLut_U0_p_lut_0_address0;

assign p_lutw_0_address1 = populateLut_U0_p_lut_0_address1;

assign p_lutw_0_ce0 = populateLut_U0_p_lut_0_ce0;

assign p_lutw_0_ce1 = populateLut_U0_p_lut_0_ce1;

assign p_lutw_0_d0 = populateLut_U0_p_lut_0_d0;

assign p_lutw_0_d1 = 16'd0;

assign p_lutw_0_we0 = populateLut_U0_p_lut_0_we0;

assign p_lutw_0_we1 = 1'b0;

assign p_lutw_1_address0 = populateLut_U0_p_lut_1_address0;

assign p_lutw_1_address1 = populateLut_U0_p_lut_1_address1;

assign p_lutw_1_ce0 = populateLut_U0_p_lut_1_ce0;

assign p_lutw_1_ce1 = populateLut_U0_p_lut_1_ce1;

assign p_lutw_1_d0 = populateLut_U0_p_lut_1_d0;

assign p_lutw_1_d1 = 16'd0;

assign p_lutw_1_we0 = populateLut_U0_p_lut_1_we0;

assign p_lutw_1_we1 = 1'b0;

assign populateLut_U0_ap_continue = ap_sync_continue;

assign populateLut_U0_ap_start = ((ap_sync_reg_populateLut_U0_ap_ready ^ 1'b1) & ap_start);

endmodule //clahe_accel_process_i
