-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tonemapping_accel_processMinMax is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_max_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    in_max_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    in_max_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    in_max_empty_n : IN STD_LOGIC;
    in_max_read : OUT STD_LOGIC;
    Tile_mCols_val1_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    Tile_mCols_val1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    Tile_mCols_val1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    Tile_mCols_val1_empty_n : IN STD_LOGIC;
    Tile_mCols_val1_read : OUT STD_LOGIC;
    Tile_mVBlkCount_val_dout : IN STD_LOGIC_VECTOR (25 downto 0);
    Tile_mVBlkCount_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    Tile_mVBlkCount_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    Tile_mVBlkCount_val_empty_n : IN STD_LOGIC;
    Tile_mVBlkCount_val_read : OUT STD_LOGIC;
    Tile_mVBlkSize_0_val_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    Tile_mVBlkSize_0_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    Tile_mVBlkSize_0_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    Tile_mVBlkSize_0_val_empty_n : IN STD_LOGIC;
    Tile_mVBlkSize_0_val_read : OUT STD_LOGIC;
    Tile_mVBlkSize_1_val_dout : IN STD_LOGIC_VECTOR (30 downto 0);
    Tile_mVBlkSize_1_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    Tile_mVBlkSize_1_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    Tile_mVBlkSize_1_val_empty_n : IN STD_LOGIC;
    Tile_mVBlkSize_1_val_read : OUT STD_LOGIC;
    Tile_mHBlkSize_0_val3_dout : IN STD_LOGIC_VECTOR (13 downto 0);
    Tile_mHBlkSize_0_val3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    Tile_mHBlkSize_0_val3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    Tile_mHBlkSize_0_val3_empty_n : IN STD_LOGIC;
    Tile_mHBlkSize_0_val3_read : OUT STD_LOGIC;
    Tile_mHBlkSize_1_val4_dout : IN STD_LOGIC_VECTOR (10 downto 0);
    Tile_mHBlkSize_1_val4_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    Tile_mHBlkSize_1_val4_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    Tile_mHBlkSize_1_val4_empty_n : IN STD_LOGIC;
    Tile_mHBlkSize_1_val4_read : OUT STD_LOGIC;
    omin_0_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omin_0_0_ce0 : OUT STD_LOGIC;
    omin_0_0_we0 : OUT STD_LOGIC;
    omin_0_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    omin_0_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omin_0_1_ce0 : OUT STD_LOGIC;
    omin_0_1_we0 : OUT STD_LOGIC;
    omin_0_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    omin_1_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omin_1_0_ce0 : OUT STD_LOGIC;
    omin_1_0_we0 : OUT STD_LOGIC;
    omin_1_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    omin_1_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omin_1_1_ce0 : OUT STD_LOGIC;
    omin_1_1_we0 : OUT STD_LOGIC;
    omin_1_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    omax_0_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omax_0_0_ce0 : OUT STD_LOGIC;
    omax_0_0_we0 : OUT STD_LOGIC;
    omax_0_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    omax_0_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omax_0_1_ce0 : OUT STD_LOGIC;
    omax_0_1_we0 : OUT STD_LOGIC;
    omax_0_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    omax_1_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omax_1_0_ce0 : OUT STD_LOGIC;
    omax_1_0_we0 : OUT STD_LOGIC;
    omax_1_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    omax_1_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omax_1_1_ce0 : OUT STD_LOGIC;
    omax_1_1_we0 : OUT STD_LOGIC;
    omax_1_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0) );
end;


architecture behav of tonemapping_accel_processMinMax is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv27_0 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv27_7FFFFFF : STD_LOGIC_VECTOR (26 downto 0) := "111111111111111111111111111";
    constant ap_const_lv27_1 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000001";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal Tile_mCols_val1_blk_n : STD_LOGIC;
    signal Tile_mVBlkCount_val_blk_n : STD_LOGIC;
    signal Tile_mVBlkSize_0_val_blk_n : STD_LOGIC;
    signal Tile_mVBlkSize_1_val_blk_n : STD_LOGIC;
    signal Tile_mHBlkSize_0_val3_blk_n : STD_LOGIC;
    signal Tile_mHBlkSize_1_val4_blk_n : STD_LOGIC;
    signal Tile_mHBlkSize_1_val4_read_reg_328 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal Tile_mHBlkSize_0_val3_read_reg_333 : STD_LOGIC_VECTOR (13 downto 0);
    signal Tile_mVBlkSize_1_val_read_reg_338 : STD_LOGIC_VECTOR (30 downto 0);
    signal Tile_mCols_val1_read_reg_343 : STD_LOGIC_VECTOR (9 downto 0);
    signal Tile_mVBlkCount_val_load_cast_fu_159_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal Tile_mVBlkCount_val_load_cast_reg_348 : STD_LOGIC_VECTOR (26 downto 0);
    signal shr_i_fu_173_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shr_i_reg_354 : STD_LOGIC_VECTOR (31 downto 0);
    signal shr14_i_fu_193_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shr14_i_reg_359 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln405_fu_203_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln405_reg_364 : STD_LOGIC_VECTOR (27 downto 0);
    signal trunc_ln405_fu_230_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln405_reg_373 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal select_ln163_fu_309_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln163_reg_378 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_getMinMax_fu_128_ap_start : STD_LOGIC;
    signal grp_getMinMax_fu_128_ap_done : STD_LOGIC;
    signal grp_getMinMax_fu_128_ap_idle : STD_LOGIC;
    signal grp_getMinMax_fu_128_ap_ready : STD_LOGIC;
    signal grp_getMinMax_fu_128_in_max_read : STD_LOGIC;
    signal grp_getMinMax_fu_128_omin_0_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_getMinMax_fu_128_omin_0_0_ce0 : STD_LOGIC;
    signal grp_getMinMax_fu_128_omin_0_0_we0 : STD_LOGIC;
    signal grp_getMinMax_fu_128_omin_0_0_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_getMinMax_fu_128_omin_0_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_getMinMax_fu_128_omin_0_1_ce0 : STD_LOGIC;
    signal grp_getMinMax_fu_128_omin_0_1_we0 : STD_LOGIC;
    signal grp_getMinMax_fu_128_omin_0_1_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_getMinMax_fu_128_omin_1_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_getMinMax_fu_128_omin_1_0_ce0 : STD_LOGIC;
    signal grp_getMinMax_fu_128_omin_1_0_we0 : STD_LOGIC;
    signal grp_getMinMax_fu_128_omin_1_0_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_getMinMax_fu_128_omin_1_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_getMinMax_fu_128_omin_1_1_ce0 : STD_LOGIC;
    signal grp_getMinMax_fu_128_omin_1_1_we0 : STD_LOGIC;
    signal grp_getMinMax_fu_128_omin_1_1_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_getMinMax_fu_128_omax_0_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_getMinMax_fu_128_omax_0_0_ce0 : STD_LOGIC;
    signal grp_getMinMax_fu_128_omax_0_0_we0 : STD_LOGIC;
    signal grp_getMinMax_fu_128_omax_0_0_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_getMinMax_fu_128_omax_0_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_getMinMax_fu_128_omax_0_1_ce0 : STD_LOGIC;
    signal grp_getMinMax_fu_128_omax_0_1_we0 : STD_LOGIC;
    signal grp_getMinMax_fu_128_omax_0_1_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_getMinMax_fu_128_omax_1_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_getMinMax_fu_128_omax_1_0_ce0 : STD_LOGIC;
    signal grp_getMinMax_fu_128_omax_1_0_we0 : STD_LOGIC;
    signal grp_getMinMax_fu_128_omax_1_0_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_getMinMax_fu_128_omax_1_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_getMinMax_fu_128_omax_1_1_ce0 : STD_LOGIC;
    signal grp_getMinMax_fu_128_omax_1_1_we0 : STD_LOGIC;
    signal grp_getMinMax_fu_128_omax_1_1_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_getMinMax_fu_128_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal index_fu_88 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000000";
    signal i_fu_224_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal icmp_ln405_fu_219_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_cast_fu_163_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal Tile_mVBlkSize_1_val_cast_fu_155_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_i_fu_177_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_cast1_fu_183_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal sub_i_fu_197_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal icmp_ln161_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln162_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln405_fu_215_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal icmp_ln163_fu_251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln164_fu_257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln165_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln165_fu_273_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal or_ln161_fu_245_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln165_fu_280_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln161_1_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln163_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln161_fu_297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln163_fu_303_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln161_fu_284_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component tonemapping_accel_getMinMax IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_max_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        in_max_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        in_max_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        in_max_empty_n : IN STD_LOGIC;
        in_max_read : OUT STD_LOGIC;
        vBlkSize : IN STD_LOGIC_VECTOR (31 downto 0);
        vBlkIndex : IN STD_LOGIC_VECTOR (3 downto 0);
        Tile_mCols_val : IN STD_LOGIC_VECTOR (9 downto 0);
        Tile_mHBlkSize_0_val : IN STD_LOGIC_VECTOR (13 downto 0);
        Tile_mHBlkSize_1_val : IN STD_LOGIC_VECTOR (10 downto 0);
        omin_0_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_0_0_ce0 : OUT STD_LOGIC;
        omin_0_0_we0 : OUT STD_LOGIC;
        omin_0_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_0_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_0_1_ce0 : OUT STD_LOGIC;
        omin_0_1_we0 : OUT STD_LOGIC;
        omin_0_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_1_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_1_0_ce0 : OUT STD_LOGIC;
        omin_1_0_we0 : OUT STD_LOGIC;
        omin_1_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_1_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_1_1_ce0 : OUT STD_LOGIC;
        omin_1_1_we0 : OUT STD_LOGIC;
        omin_1_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_0_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_0_0_ce0 : OUT STD_LOGIC;
        omax_0_0_we0 : OUT STD_LOGIC;
        omax_0_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_0_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_0_1_ce0 : OUT STD_LOGIC;
        omax_0_1_we0 : OUT STD_LOGIC;
        omax_0_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_1_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_1_0_ce0 : OUT STD_LOGIC;
        omax_1_0_we0 : OUT STD_LOGIC;
        omax_1_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_1_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_1_1_ce0 : OUT STD_LOGIC;
        omax_1_1_we0 : OUT STD_LOGIC;
        omax_1_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;



begin
    grp_getMinMax_fu_128 : component tonemapping_accel_getMinMax
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_getMinMax_fu_128_ap_start,
        ap_done => grp_getMinMax_fu_128_ap_done,
        ap_idle => grp_getMinMax_fu_128_ap_idle,
        ap_ready => grp_getMinMax_fu_128_ap_ready,
        in_max_dout => in_max_dout,
        in_max_num_data_valid => ap_const_lv3_0,
        in_max_fifo_cap => ap_const_lv3_0,
        in_max_empty_n => in_max_empty_n,
        in_max_read => grp_getMinMax_fu_128_in_max_read,
        vBlkSize => select_ln163_reg_378,
        vBlkIndex => trunc_ln405_reg_373,
        Tile_mCols_val => Tile_mCols_val1_read_reg_343,
        Tile_mHBlkSize_0_val => Tile_mHBlkSize_0_val3_read_reg_333,
        Tile_mHBlkSize_1_val => Tile_mHBlkSize_1_val4_read_reg_328,
        omin_0_0_address0 => grp_getMinMax_fu_128_omin_0_0_address0,
        omin_0_0_ce0 => grp_getMinMax_fu_128_omin_0_0_ce0,
        omin_0_0_we0 => grp_getMinMax_fu_128_omin_0_0_we0,
        omin_0_0_d0 => grp_getMinMax_fu_128_omin_0_0_d0,
        omin_0_1_address0 => grp_getMinMax_fu_128_omin_0_1_address0,
        omin_0_1_ce0 => grp_getMinMax_fu_128_omin_0_1_ce0,
        omin_0_1_we0 => grp_getMinMax_fu_128_omin_0_1_we0,
        omin_0_1_d0 => grp_getMinMax_fu_128_omin_0_1_d0,
        omin_1_0_address0 => grp_getMinMax_fu_128_omin_1_0_address0,
        omin_1_0_ce0 => grp_getMinMax_fu_128_omin_1_0_ce0,
        omin_1_0_we0 => grp_getMinMax_fu_128_omin_1_0_we0,
        omin_1_0_d0 => grp_getMinMax_fu_128_omin_1_0_d0,
        omin_1_1_address0 => grp_getMinMax_fu_128_omin_1_1_address0,
        omin_1_1_ce0 => grp_getMinMax_fu_128_omin_1_1_ce0,
        omin_1_1_we0 => grp_getMinMax_fu_128_omin_1_1_we0,
        omin_1_1_d0 => grp_getMinMax_fu_128_omin_1_1_d0,
        omax_0_0_address0 => grp_getMinMax_fu_128_omax_0_0_address0,
        omax_0_0_ce0 => grp_getMinMax_fu_128_omax_0_0_ce0,
        omax_0_0_we0 => grp_getMinMax_fu_128_omax_0_0_we0,
        omax_0_0_d0 => grp_getMinMax_fu_128_omax_0_0_d0,
        omax_0_1_address0 => grp_getMinMax_fu_128_omax_0_1_address0,
        omax_0_1_ce0 => grp_getMinMax_fu_128_omax_0_1_ce0,
        omax_0_1_we0 => grp_getMinMax_fu_128_omax_0_1_we0,
        omax_0_1_d0 => grp_getMinMax_fu_128_omax_0_1_d0,
        omax_1_0_address0 => grp_getMinMax_fu_128_omax_1_0_address0,
        omax_1_0_ce0 => grp_getMinMax_fu_128_omax_1_0_ce0,
        omax_1_0_we0 => grp_getMinMax_fu_128_omax_1_0_we0,
        omax_1_0_d0 => grp_getMinMax_fu_128_omax_1_0_d0,
        omax_1_1_address0 => grp_getMinMax_fu_128_omax_1_1_address0,
        omax_1_1_ce0 => grp_getMinMax_fu_128_omax_1_1_ce0,
        omax_1_1_we0 => grp_getMinMax_fu_128_omax_1_1_we0,
        omax_1_1_d0 => grp_getMinMax_fu_128_omax_1_1_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln405_fu_219_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_getMinMax_fu_128_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_getMinMax_fu_128_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_getMinMax_fu_128_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_getMinMax_fu_128_ap_ready = ap_const_logic_1)) then 
                    grp_getMinMax_fu_128_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    index_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                index_fu_88 <= ap_const_lv27_0;
            elsif (((icmp_ln405_fu_219_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                index_fu_88 <= i_fu_224_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                Tile_mCols_val1_read_reg_343 <= Tile_mCols_val1_dout;
                Tile_mHBlkSize_0_val3_read_reg_333 <= Tile_mHBlkSize_0_val3_dout;
                Tile_mHBlkSize_1_val4_read_reg_328 <= Tile_mHBlkSize_1_val4_dout;
                    Tile_mVBlkCount_val_load_cast_reg_348(25 downto 0) <= Tile_mVBlkCount_val_load_cast_fu_159_p1(25 downto 0);
                Tile_mVBlkSize_1_val_read_reg_338 <= Tile_mVBlkSize_1_val_dout;
                sext_ln405_reg_364 <= sext_ln405_fu_203_p1;
                shr14_i_reg_359 <= shr14_i_fu_193_p1;
                shr_i_reg_354 <= shr_i_fu_173_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                select_ln163_reg_378 <= select_ln163_fu_309_p3;
                trunc_ln405_reg_373 <= trunc_ln405_fu_230_p1;
            end if;
        end if;
    end process;
    Tile_mVBlkCount_val_load_cast_reg_348(26) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, grp_getMinMax_fu_128_ap_done, ap_CS_fsm_state4, icmp_ln405_fu_219_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln405_fu_219_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_getMinMax_fu_128_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;

    Tile_mCols_val1_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Tile_mCols_val1_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Tile_mCols_val1_blk_n <= Tile_mCols_val1_empty_n;
        else 
            Tile_mCols_val1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    Tile_mCols_val1_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            Tile_mCols_val1_read <= ap_const_logic_1;
        else 
            Tile_mCols_val1_read <= ap_const_logic_0;
        end if; 
    end process;


    Tile_mHBlkSize_0_val3_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Tile_mHBlkSize_0_val3_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Tile_mHBlkSize_0_val3_blk_n <= Tile_mHBlkSize_0_val3_empty_n;
        else 
            Tile_mHBlkSize_0_val3_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    Tile_mHBlkSize_0_val3_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            Tile_mHBlkSize_0_val3_read <= ap_const_logic_1;
        else 
            Tile_mHBlkSize_0_val3_read <= ap_const_logic_0;
        end if; 
    end process;


    Tile_mHBlkSize_1_val4_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Tile_mHBlkSize_1_val4_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Tile_mHBlkSize_1_val4_blk_n <= Tile_mHBlkSize_1_val4_empty_n;
        else 
            Tile_mHBlkSize_1_val4_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    Tile_mHBlkSize_1_val4_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            Tile_mHBlkSize_1_val4_read <= ap_const_logic_1;
        else 
            Tile_mHBlkSize_1_val4_read <= ap_const_logic_0;
        end if; 
    end process;


    Tile_mVBlkCount_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Tile_mVBlkCount_val_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Tile_mVBlkCount_val_blk_n <= Tile_mVBlkCount_val_empty_n;
        else 
            Tile_mVBlkCount_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    Tile_mVBlkCount_val_load_cast_fu_159_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Tile_mVBlkCount_val_dout),27));

    Tile_mVBlkCount_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            Tile_mVBlkCount_val_read <= ap_const_logic_1;
        else 
            Tile_mVBlkCount_val_read <= ap_const_logic_0;
        end if; 
    end process;


    Tile_mVBlkSize_0_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Tile_mVBlkSize_0_val_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Tile_mVBlkSize_0_val_blk_n <= Tile_mVBlkSize_0_val_empty_n;
        else 
            Tile_mVBlkSize_0_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    Tile_mVBlkSize_0_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            Tile_mVBlkSize_0_val_read <= ap_const_logic_1;
        else 
            Tile_mVBlkSize_0_val_read <= ap_const_logic_0;
        end if; 
    end process;


    Tile_mVBlkSize_1_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Tile_mVBlkSize_1_val_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Tile_mVBlkSize_1_val_blk_n <= Tile_mVBlkSize_1_val_empty_n;
        else 
            Tile_mVBlkSize_1_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    Tile_mVBlkSize_1_val_cast_fu_155_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Tile_mVBlkSize_1_val_dout),32));

    Tile_mVBlkSize_1_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            Tile_mVBlkSize_1_val_read <= ap_const_logic_1;
        else 
            Tile_mVBlkSize_1_val_read <= ap_const_logic_0;
        end if; 
    end process;

    add_i_fu_177_p2 <= std_logic_vector(unsigned(Tile_mVBlkSize_0_val_dout) + unsigned(Tile_mVBlkSize_1_val_cast_fu_155_p1));
    and_ln163_fu_303_p2 <= (xor_ln161_fu_297_p2 and or_ln163_fu_262_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_getMinMax_fu_128_ap_done)
    begin
        if ((grp_getMinMax_fu_128_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, Tile_mCols_val1_empty_n, Tile_mVBlkCount_val_empty_n, Tile_mVBlkSize_0_val_empty_n, Tile_mVBlkSize_1_val_empty_n, Tile_mHBlkSize_0_val3_empty_n, Tile_mHBlkSize_1_val4_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_const_logic_0 = Tile_mHBlkSize_1_val4_empty_n) or (ap_const_logic_0 = Tile_mHBlkSize_0_val3_empty_n) or (ap_const_logic_0 = Tile_mVBlkSize_1_val_empty_n) or (ap_const_logic_0 = Tile_mVBlkSize_0_val_empty_n) or (ap_const_logic_0 = Tile_mVBlkCount_val_empty_n) or (ap_const_logic_0 = Tile_mCols_val1_empty_n) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln405_fu_219_p2)
    begin
        if (((icmp_ln405_fu_219_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln405_fu_219_p2)
    begin
        if (((icmp_ln405_fu_219_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_getMinMax_fu_128_ap_start <= grp_getMinMax_fu_128_ap_start_reg;
    i_fu_224_p2 <= std_logic_vector(unsigned(index_fu_88) + unsigned(ap_const_lv27_1));
    icmp_ln161_fu_234_p2 <= "1" when (index_fu_88 = ap_const_lv27_0) else "0";
    icmp_ln162_fu_240_p2 <= "1" when (index_fu_88 = Tile_mVBlkCount_val_load_cast_reg_348) else "0";
    icmp_ln163_fu_251_p2 <= "1" when (index_fu_88 = ap_const_lv27_1) else "0";
    icmp_ln164_fu_257_p2 <= "1" when (zext_ln405_fu_215_p1 = sext_ln405_reg_364) else "0";
    icmp_ln165_fu_268_p2 <= "1" when (signed(zext_ln405_fu_215_p1) < signed(sext_ln405_reg_364)) else "0";
    icmp_ln405_fu_219_p2 <= "1" when (unsigned(index_fu_88) > unsigned(Tile_mVBlkCount_val_load_cast_reg_348)) else "0";

    in_max_read_assign_proc : process(grp_getMinMax_fu_128_in_max_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            in_max_read <= grp_getMinMax_fu_128_in_max_read;
        else 
            in_max_read <= ap_const_logic_0;
        end if; 
    end process;

    omax_0_0_address0 <= grp_getMinMax_fu_128_omax_0_0_address0;
    omax_0_0_ce0 <= grp_getMinMax_fu_128_omax_0_0_ce0;
    omax_0_0_d0 <= grp_getMinMax_fu_128_omax_0_0_d0;
    omax_0_0_we0 <= grp_getMinMax_fu_128_omax_0_0_we0;
    omax_0_1_address0 <= grp_getMinMax_fu_128_omax_0_1_address0;
    omax_0_1_ce0 <= grp_getMinMax_fu_128_omax_0_1_ce0;
    omax_0_1_d0 <= grp_getMinMax_fu_128_omax_0_1_d0;
    omax_0_1_we0 <= grp_getMinMax_fu_128_omax_0_1_we0;
    omax_1_0_address0 <= grp_getMinMax_fu_128_omax_1_0_address0;
    omax_1_0_ce0 <= grp_getMinMax_fu_128_omax_1_0_ce0;
    omax_1_0_d0 <= grp_getMinMax_fu_128_omax_1_0_d0;
    omax_1_0_we0 <= grp_getMinMax_fu_128_omax_1_0_we0;
    omax_1_1_address0 <= grp_getMinMax_fu_128_omax_1_1_address0;
    omax_1_1_ce0 <= grp_getMinMax_fu_128_omax_1_1_ce0;
    omax_1_1_d0 <= grp_getMinMax_fu_128_omax_1_1_d0;
    omax_1_1_we0 <= grp_getMinMax_fu_128_omax_1_1_we0;
    omin_0_0_address0 <= grp_getMinMax_fu_128_omin_0_0_address0;
    omin_0_0_ce0 <= grp_getMinMax_fu_128_omin_0_0_ce0;
    omin_0_0_d0 <= grp_getMinMax_fu_128_omin_0_0_d0;
    omin_0_0_we0 <= grp_getMinMax_fu_128_omin_0_0_we0;
    omin_0_1_address0 <= grp_getMinMax_fu_128_omin_0_1_address0;
    omin_0_1_ce0 <= grp_getMinMax_fu_128_omin_0_1_ce0;
    omin_0_1_d0 <= grp_getMinMax_fu_128_omin_0_1_d0;
    omin_0_1_we0 <= grp_getMinMax_fu_128_omin_0_1_we0;
    omin_1_0_address0 <= grp_getMinMax_fu_128_omin_1_0_address0;
    omin_1_0_ce0 <= grp_getMinMax_fu_128_omin_1_0_ce0;
    omin_1_0_d0 <= grp_getMinMax_fu_128_omin_1_0_d0;
    omin_1_0_we0 <= grp_getMinMax_fu_128_omin_1_0_we0;
    omin_1_1_address0 <= grp_getMinMax_fu_128_omin_1_1_address0;
    omin_1_1_ce0 <= grp_getMinMax_fu_128_omin_1_1_ce0;
    omin_1_1_d0 <= grp_getMinMax_fu_128_omin_1_1_d0;
    omin_1_1_we0 <= grp_getMinMax_fu_128_omin_1_1_we0;
    or_ln161_1_fu_291_p2 <= (icmp_ln162_fu_240_p2 or icmp_ln161_fu_234_p2);
    or_ln161_fu_245_p2 <= (icmp_ln162_fu_240_p2 or icmp_ln161_fu_234_p2);
    or_ln163_fu_262_p2 <= (icmp_ln164_fu_257_p2 or icmp_ln163_fu_251_p2);
    p_cast1_fu_183_p4 <= add_i_fu_177_p2(31 downto 1);
    p_cast_fu_163_p4 <= Tile_mVBlkSize_0_val_dout(31 downto 1);
    select_ln161_fu_284_p3 <= 
        shr_i_reg_354 when (or_ln161_fu_245_p2(0) = '1') else 
        zext_ln165_fu_280_p1;
    select_ln163_fu_309_p3 <= 
        shr14_i_reg_359 when (and_ln163_fu_303_p2(0) = '1') else 
        select_ln161_fu_284_p3;
    select_ln165_fu_273_p3 <= 
        Tile_mVBlkSize_1_val_read_reg_338 when (icmp_ln165_fu_268_p2(0) = '1') else 
        ap_const_lv31_0;
        sext_ln405_fu_203_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_i_fu_197_p2),28));

        shr14_i_fu_193_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_cast1_fu_183_p4),32));

        shr_i_fu_173_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_cast_fu_163_p4),32));

    sub_i_fu_197_p2 <= std_logic_vector(unsigned(Tile_mVBlkCount_val_load_cast_fu_159_p1) + unsigned(ap_const_lv27_7FFFFFF));
    trunc_ln405_fu_230_p1 <= index_fu_88(4 - 1 downto 0);
    xor_ln161_fu_297_p2 <= (or_ln161_1_fu_291_p2 xor ap_const_lv1_1);
    zext_ln165_fu_280_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln165_fu_273_p3),32));
    zext_ln405_fu_215_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(index_fu_88),28));
end behav;
