-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tonemapping_accel_process_r is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_rows_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    in_rows_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    in_rows_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    in_rows_empty_n : IN STD_LOGIC;
    in_rows_read : OUT STD_LOGIC;
    in_cols_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    in_cols_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    in_cols_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    in_cols_empty_n : IN STD_LOGIC;
    in_cols_read : OUT STD_LOGIC;
    imgInput_data_dout : IN STD_LOGIC_VECTOR (29 downto 0);
    imgInput_data_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    imgInput_data_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    imgInput_data_empty_n : IN STD_LOGIC;
    imgInput_data_read : OUT STD_LOGIC;
    block_rows : IN STD_LOGIC_VECTOR (30 downto 0);
    block_cols : IN STD_LOGIC_VECTOR (30 downto 0);
    omin_r_0_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omin_r_0_0_ce0 : OUT STD_LOGIC;
    omin_r_0_0_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
    omin_r_0_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omin_r_0_1_ce0 : OUT STD_LOGIC;
    omin_r_0_1_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
    omin_r_1_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omin_r_1_0_ce0 : OUT STD_LOGIC;
    omin_r_1_0_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
    omin_r_1_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omin_r_1_1_ce0 : OUT STD_LOGIC;
    omin_r_1_1_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
    omax_r_0_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omax_r_0_0_ce0 : OUT STD_LOGIC;
    omax_r_0_0_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
    omax_r_0_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omax_r_0_1_ce0 : OUT STD_LOGIC;
    omax_r_0_1_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
    omax_r_1_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omax_r_1_0_ce0 : OUT STD_LOGIC;
    omax_r_1_0_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
    omax_r_1_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omax_r_1_1_ce0 : OUT STD_LOGIC;
    omax_r_1_1_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
    omin_w_0_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omin_w_0_0_ce0 : OUT STD_LOGIC;
    omin_w_0_0_we0 : OUT STD_LOGIC;
    omin_w_0_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    omin_w_0_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omin_w_0_1_ce0 : OUT STD_LOGIC;
    omin_w_0_1_we0 : OUT STD_LOGIC;
    omin_w_0_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    omin_w_1_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omin_w_1_0_ce0 : OUT STD_LOGIC;
    omin_w_1_0_we0 : OUT STD_LOGIC;
    omin_w_1_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    omin_w_1_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omin_w_1_1_ce0 : OUT STD_LOGIC;
    omin_w_1_1_we0 : OUT STD_LOGIC;
    omin_w_1_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    omax_w_0_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omax_w_0_0_ce0 : OUT STD_LOGIC;
    omax_w_0_0_we0 : OUT STD_LOGIC;
    omax_w_0_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    omax_w_0_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omax_w_0_1_ce0 : OUT STD_LOGIC;
    omax_w_0_1_we0 : OUT STD_LOGIC;
    omax_w_0_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    omax_w_1_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omax_w_1_0_ce0 : OUT STD_LOGIC;
    omax_w_1_0_we0 : OUT STD_LOGIC;
    omax_w_1_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    omax_w_1_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    omax_w_1_1_ce0 : OUT STD_LOGIC;
    omax_w_1_1_we0 : OUT STD_LOGIC;
    omax_w_1_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    imgOutput_data_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    imgOutput_data_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    imgOutput_data_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    imgOutput_data_full_n : IN STD_LOGIC;
    imgOutput_data_write : OUT STD_LOGIC );
end;


architecture behav of tonemapping_accel_process_r is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv31_7FFFFFFF : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111111111111111111";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv26_1 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal in_rows_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal in_cols_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal c_reg_455 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_done : STD_LOGIC;
    signal grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_done : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal r_reg_463 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln105_fu_185_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln105_reg_471 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal targetBlock_reg_476 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal targetBlock2_reg_481 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln617_fu_190_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln617_reg_486 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal select_ln113_fu_202_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln113_reg_491 : STD_LOGIC_VECTOR (3 downto 0);
    signal Tile_mBlkColsNPCAligned_fu_213_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal Tile_mBlkColsNPCAligned_reg_498 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln121_fu_219_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln121_reg_505 : STD_LOGIC_VECTOR (10 downto 0);
    signal lshr_ln126_fu_225_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal lshr_ln126_reg_510 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln132_fu_234_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln132_reg_515 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln139_fu_241_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln139_reg_521 : STD_LOGIC_VECTOR (31 downto 0);
    signal Tile_mVBlkCount_fu_251_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal Tile_mVBlkCount_reg_526 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln617_fu_257_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln617_reg_531 : STD_LOGIC_VECTOR (25 downto 0);
    signal Tile_mHBlkCount_fu_279_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal Tile_mHBlkCount_reg_537 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln142_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln142_reg_542 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln144_fu_310_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln144_reg_548 : STD_LOGIC_VECTOR (13 downto 0);
    signal Tile_mHBlkSize_2_fu_381_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal Tile_mHBlkSize_2_reg_553 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal Tile_mVBlkCount_2_fu_417_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal Tile_mVBlkCount_2_reg_558 : STD_LOGIC_VECTOR (25 downto 0);
    signal Tile_mVBlkSize_fu_423_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal Tile_mVBlkSize_reg_563 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_start : STD_LOGIC;
    signal grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_idle : STD_LOGIC;
    signal grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_ready : STD_LOGIC;
    signal grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_blkColsLog2_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_blkColsLog2_out_ap_vld : STD_LOGIC;
    signal grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_start : STD_LOGIC;
    signal grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_idle : STD_LOGIC;
    signal grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_ready : STD_LOGIC;
    signal grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_blkRowsLog2_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_blkRowsLog2_out_ap_vld : STD_LOGIC;
    signal grp_process_i_fu_138_imgInput_data_read : STD_LOGIC;
    signal grp_process_i_fu_138_omin_r_0_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omin_r_0_0_ce0 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_r_0_0_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omin_r_0_0_we0 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_r_0_0_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omin_r_0_0_ce1 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_r_0_0_d1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omin_r_0_0_we1 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_r_0_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omin_r_0_1_ce0 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_r_0_1_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omin_r_0_1_we0 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_r_0_1_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omin_r_0_1_ce1 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_r_0_1_d1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omin_r_0_1_we1 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_r_1_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omin_r_1_0_ce0 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_r_1_0_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omin_r_1_0_we0 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_r_1_0_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omin_r_1_0_ce1 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_r_1_0_d1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omin_r_1_0_we1 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_r_1_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omin_r_1_1_ce0 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_r_1_1_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omin_r_1_1_we0 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_r_1_1_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omin_r_1_1_ce1 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_r_1_1_d1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omin_r_1_1_we1 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_r_0_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omax_r_0_0_ce0 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_r_0_0_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omax_r_0_0_we0 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_r_0_0_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omax_r_0_0_ce1 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_r_0_0_d1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omax_r_0_0_we1 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_r_0_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omax_r_0_1_ce0 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_r_0_1_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omax_r_0_1_we0 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_r_0_1_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omax_r_0_1_ce1 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_r_0_1_d1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omax_r_0_1_we1 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_r_1_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omax_r_1_0_ce0 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_r_1_0_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omax_r_1_0_we0 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_r_1_0_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omax_r_1_0_ce1 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_r_1_0_d1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omax_r_1_0_we1 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_r_1_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omax_r_1_1_ce0 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_r_1_1_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omax_r_1_1_we0 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_r_1_1_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omax_r_1_1_ce1 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_r_1_1_d1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omax_r_1_1_we1 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_w_0_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omin_w_0_0_ce0 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_w_0_0_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omin_w_0_0_we0 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_w_0_0_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omin_w_0_0_ce1 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_w_0_0_d1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omin_w_0_0_we1 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_w_0_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omin_w_0_1_ce0 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_w_0_1_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omin_w_0_1_we0 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_w_0_1_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omin_w_0_1_ce1 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_w_0_1_d1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omin_w_0_1_we1 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_w_1_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omin_w_1_0_ce0 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_w_1_0_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omin_w_1_0_we0 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_w_1_0_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omin_w_1_0_ce1 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_w_1_0_d1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omin_w_1_0_we1 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_w_1_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omin_w_1_1_ce0 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_w_1_1_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omin_w_1_1_we0 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_w_1_1_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omin_w_1_1_ce1 : STD_LOGIC;
    signal grp_process_i_fu_138_omin_w_1_1_d1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omin_w_1_1_we1 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_w_0_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omax_w_0_0_ce0 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_w_0_0_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omax_w_0_0_we0 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_w_0_0_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omax_w_0_0_ce1 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_w_0_0_d1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omax_w_0_0_we1 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_w_0_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omax_w_0_1_ce0 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_w_0_1_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omax_w_0_1_we0 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_w_0_1_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omax_w_0_1_ce1 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_w_0_1_d1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omax_w_0_1_we1 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_w_1_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omax_w_1_0_ce0 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_w_1_0_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omax_w_1_0_we0 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_w_1_0_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omax_w_1_0_ce1 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_w_1_0_d1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omax_w_1_0_we1 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_w_1_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omax_w_1_1_ce0 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_w_1_1_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omax_w_1_1_we0 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_w_1_1_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_process_i_fu_138_omax_w_1_1_ce1 : STD_LOGIC;
    signal grp_process_i_fu_138_omax_w_1_1_d1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_process_i_fu_138_omax_w_1_1_we1 : STD_LOGIC;
    signal grp_process_i_fu_138_imgOutput_data_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_process_i_fu_138_imgOutput_data_write : STD_LOGIC;
    signal grp_process_i_fu_138_ap_start : STD_LOGIC;
    signal grp_process_i_fu_138_ap_done : STD_LOGIC;
    signal grp_process_i_fu_138_ap_ready : STD_LOGIC;
    signal grp_process_i_fu_138_ap_idle : STD_LOGIC;
    signal grp_process_i_fu_138_ap_continue : STD_LOGIC;
    signal grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call19 : BOOLEAN;
    signal blkColsLog2_loc_fu_96 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call43 : BOOLEAN;
    signal blkRowsLog2_loc_fu_92 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_process_i_fu_138_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_sync_grp_process_i_fu_138_ap_ready : STD_LOGIC;
    signal ap_sync_grp_process_i_fu_138_ap_done : STD_LOGIC;
    signal ap_block_state7_on_subcall_done : BOOLEAN;
    signal ap_sync_reg_grp_process_i_fu_138_ap_ready : STD_LOGIC := '0';
    signal ap_sync_reg_grp_process_i_fu_138_ap_done : STD_LOGIC := '0';
    signal zext_ln119_3_fu_209_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln96_1_fu_193_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln617_3_fu_196_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln139_fu_245_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln121_fu_270_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln617_5_fu_267_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln121_1_fu_273_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln119_2_fu_264_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tv_fu_291_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln617_2_fu_261_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln139_2_fu_288_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal lshr_ln144_fu_300_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln144_fu_306_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln139_1_fu_285_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln617_fu_337_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln119_1_fu_331_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln96_2_fu_325_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal th_fu_340_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln126_fu_352_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln119_fu_328_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln126_fu_355_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln96_fu_322_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln126_1_fu_361_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal t_fu_365_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln124_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Tile_mHBlkSize_1_fu_371_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln617_4_fu_334_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln617_1_fu_319_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln144_1_fu_389_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal t_1_fu_392_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln3_fu_398_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal Tile_mVBlkCount_1_fu_412_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln145_fu_408_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_rows_cast_fu_316_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component tonemapping_accel_process_Pipeline_VITIS_LOOP_113_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        block_cols : IN STD_LOGIC_VECTOR (30 downto 0);
        blkColsLog2_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        blkColsLog2_out_ap_vld : OUT STD_LOGIC;
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component tonemapping_accel_process_Pipeline_VITIS_LOOP_132_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        block_rows : IN STD_LOGIC_VECTOR (30 downto 0);
        blkRowsLog2_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        blkRowsLog2_out_ap_vld : OUT STD_LOGIC;
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component tonemapping_accel_process_i IS
    port (
        imgInput_data_dout : IN STD_LOGIC_VECTOR (29 downto 0);
        imgInput_data_empty_n : IN STD_LOGIC;
        imgInput_data_read : OUT STD_LOGIC;
        Tile_mRows_val2 : IN STD_LOGIC_VECTOR (9 downto 0);
        Tile_mCols_val5 : IN STD_LOGIC_VECTOR (9 downto 0);
        Tile_mVBlkCount_val14 : IN STD_LOGIC_VECTOR (25 downto 0);
        Tile_mVBlkSize_0_val17 : IN STD_LOGIC_VECTOR (31 downto 0);
        Tile_mVBlkSize_1_val20 : IN STD_LOGIC_VECTOR (30 downto 0);
        Tile_mHBlkSize_0_val23 : IN STD_LOGIC_VECTOR (13 downto 0);
        Tile_mHBlkSize_1_val26 : IN STD_LOGIC_VECTOR (10 downto 0);
        omin_r_0_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_r_0_0_ce0 : OUT STD_LOGIC;
        omin_r_0_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_r_0_0_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        omin_r_0_0_we0 : OUT STD_LOGIC;
        omin_r_0_0_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_r_0_0_ce1 : OUT STD_LOGIC;
        omin_r_0_0_d1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_r_0_0_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        omin_r_0_0_we1 : OUT STD_LOGIC;
        omin_r_0_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_r_0_1_ce0 : OUT STD_LOGIC;
        omin_r_0_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_r_0_1_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        omin_r_0_1_we0 : OUT STD_LOGIC;
        omin_r_0_1_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_r_0_1_ce1 : OUT STD_LOGIC;
        omin_r_0_1_d1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_r_0_1_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        omin_r_0_1_we1 : OUT STD_LOGIC;
        omin_r_1_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_r_1_0_ce0 : OUT STD_LOGIC;
        omin_r_1_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_r_1_0_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        omin_r_1_0_we0 : OUT STD_LOGIC;
        omin_r_1_0_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_r_1_0_ce1 : OUT STD_LOGIC;
        omin_r_1_0_d1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_r_1_0_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        omin_r_1_0_we1 : OUT STD_LOGIC;
        omin_r_1_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_r_1_1_ce0 : OUT STD_LOGIC;
        omin_r_1_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_r_1_1_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        omin_r_1_1_we0 : OUT STD_LOGIC;
        omin_r_1_1_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_r_1_1_ce1 : OUT STD_LOGIC;
        omin_r_1_1_d1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_r_1_1_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        omin_r_1_1_we1 : OUT STD_LOGIC;
        omax_r_0_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_r_0_0_ce0 : OUT STD_LOGIC;
        omax_r_0_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_r_0_0_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        omax_r_0_0_we0 : OUT STD_LOGIC;
        omax_r_0_0_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_r_0_0_ce1 : OUT STD_LOGIC;
        omax_r_0_0_d1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_r_0_0_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        omax_r_0_0_we1 : OUT STD_LOGIC;
        omax_r_0_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_r_0_1_ce0 : OUT STD_LOGIC;
        omax_r_0_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_r_0_1_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        omax_r_0_1_we0 : OUT STD_LOGIC;
        omax_r_0_1_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_r_0_1_ce1 : OUT STD_LOGIC;
        omax_r_0_1_d1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_r_0_1_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        omax_r_0_1_we1 : OUT STD_LOGIC;
        omax_r_1_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_r_1_0_ce0 : OUT STD_LOGIC;
        omax_r_1_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_r_1_0_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        omax_r_1_0_we0 : OUT STD_LOGIC;
        omax_r_1_0_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_r_1_0_ce1 : OUT STD_LOGIC;
        omax_r_1_0_d1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_r_1_0_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        omax_r_1_0_we1 : OUT STD_LOGIC;
        omax_r_1_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_r_1_1_ce0 : OUT STD_LOGIC;
        omax_r_1_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_r_1_1_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        omax_r_1_1_we0 : OUT STD_LOGIC;
        omax_r_1_1_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_r_1_1_ce1 : OUT STD_LOGIC;
        omax_r_1_1_d1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_r_1_1_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        omax_r_1_1_we1 : OUT STD_LOGIC;
        omin_w_0_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_w_0_0_ce0 : OUT STD_LOGIC;
        omin_w_0_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_w_0_0_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        omin_w_0_0_we0 : OUT STD_LOGIC;
        omin_w_0_0_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_w_0_0_ce1 : OUT STD_LOGIC;
        omin_w_0_0_d1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_w_0_0_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        omin_w_0_0_we1 : OUT STD_LOGIC;
        omin_w_0_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_w_0_1_ce0 : OUT STD_LOGIC;
        omin_w_0_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_w_0_1_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        omin_w_0_1_we0 : OUT STD_LOGIC;
        omin_w_0_1_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_w_0_1_ce1 : OUT STD_LOGIC;
        omin_w_0_1_d1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_w_0_1_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        omin_w_0_1_we1 : OUT STD_LOGIC;
        omin_w_1_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_w_1_0_ce0 : OUT STD_LOGIC;
        omin_w_1_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_w_1_0_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        omin_w_1_0_we0 : OUT STD_LOGIC;
        omin_w_1_0_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_w_1_0_ce1 : OUT STD_LOGIC;
        omin_w_1_0_d1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_w_1_0_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        omin_w_1_0_we1 : OUT STD_LOGIC;
        omin_w_1_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_w_1_1_ce0 : OUT STD_LOGIC;
        omin_w_1_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_w_1_1_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        omin_w_1_1_we0 : OUT STD_LOGIC;
        omin_w_1_1_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omin_w_1_1_ce1 : OUT STD_LOGIC;
        omin_w_1_1_d1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omin_w_1_1_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        omin_w_1_1_we1 : OUT STD_LOGIC;
        omax_w_0_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_w_0_0_ce0 : OUT STD_LOGIC;
        omax_w_0_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_w_0_0_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        omax_w_0_0_we0 : OUT STD_LOGIC;
        omax_w_0_0_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_w_0_0_ce1 : OUT STD_LOGIC;
        omax_w_0_0_d1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_w_0_0_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        omax_w_0_0_we1 : OUT STD_LOGIC;
        omax_w_0_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_w_0_1_ce0 : OUT STD_LOGIC;
        omax_w_0_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_w_0_1_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        omax_w_0_1_we0 : OUT STD_LOGIC;
        omax_w_0_1_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_w_0_1_ce1 : OUT STD_LOGIC;
        omax_w_0_1_d1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_w_0_1_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        omax_w_0_1_we1 : OUT STD_LOGIC;
        omax_w_1_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_w_1_0_ce0 : OUT STD_LOGIC;
        omax_w_1_0_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_w_1_0_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        omax_w_1_0_we0 : OUT STD_LOGIC;
        omax_w_1_0_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_w_1_0_ce1 : OUT STD_LOGIC;
        omax_w_1_0_d1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_w_1_0_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        omax_w_1_0_we1 : OUT STD_LOGIC;
        omax_w_1_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_w_1_1_ce0 : OUT STD_LOGIC;
        omax_w_1_1_d0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_w_1_1_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        omax_w_1_1_we0 : OUT STD_LOGIC;
        omax_w_1_1_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        omax_w_1_1_ce1 : OUT STD_LOGIC;
        omax_w_1_1_d1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        omax_w_1_1_q1 : IN STD_LOGIC_VECTOR (9 downto 0);
        omax_w_1_1_we1 : OUT STD_LOGIC;
        imgOutput_data_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        imgOutput_data_full_n : IN STD_LOGIC;
        imgOutput_data_write : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        Tile_mVBlkCount_val14_ap_vld : IN STD_LOGIC;
        Tile_mVBlkSize_0_val17_ap_vld : IN STD_LOGIC;
        Tile_mVBlkSize_1_val20_ap_vld : IN STD_LOGIC;
        Tile_mHBlkSize_0_val23_ap_vld : IN STD_LOGIC;
        Tile_mHBlkSize_1_val26_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        Tile_mRows_val2_ap_vld : IN STD_LOGIC;
        Tile_mCols_val5_ap_vld : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    grp_process_Pipeline_VITIS_LOOP_113_1_fu_124 : component tonemapping_accel_process_Pipeline_VITIS_LOOP_113_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_start,
        ap_done => grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_done,
        ap_idle => grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_idle,
        ap_ready => grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_ready,
        block_cols => block_cols,
        blkColsLog2_out => grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_blkColsLog2_out,
        blkColsLog2_out_ap_vld => grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_blkColsLog2_out_ap_vld,
        ap_return => grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_return);

    grp_process_Pipeline_VITIS_LOOP_132_2_fu_131 : component tonemapping_accel_process_Pipeline_VITIS_LOOP_132_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_start,
        ap_done => grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_done,
        ap_idle => grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_idle,
        ap_ready => grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_ready,
        block_rows => block_rows,
        blkRowsLog2_out => grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_blkRowsLog2_out,
        blkRowsLog2_out_ap_vld => grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_blkRowsLog2_out_ap_vld,
        ap_return => grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_return);

    grp_process_i_fu_138 : component tonemapping_accel_process_i
    port map (
        imgInput_data_dout => imgInput_data_dout,
        imgInput_data_empty_n => imgInput_data_empty_n,
        imgInput_data_read => grp_process_i_fu_138_imgInput_data_read,
        Tile_mRows_val2 => r_reg_463,
        Tile_mCols_val5 => c_reg_455,
        Tile_mVBlkCount_val14 => Tile_mVBlkCount_2_reg_558,
        Tile_mVBlkSize_0_val17 => Tile_mVBlkSize_reg_563,
        Tile_mVBlkSize_1_val20 => block_rows,
        Tile_mHBlkSize_0_val23 => Tile_mHBlkSize_2_reg_553,
        Tile_mHBlkSize_1_val26 => Tile_mBlkColsNPCAligned_reg_498,
        omin_r_0_0_address0 => grp_process_i_fu_138_omin_r_0_0_address0,
        omin_r_0_0_ce0 => grp_process_i_fu_138_omin_r_0_0_ce0,
        omin_r_0_0_d0 => grp_process_i_fu_138_omin_r_0_0_d0,
        omin_r_0_0_q0 => omin_r_0_0_q0,
        omin_r_0_0_we0 => grp_process_i_fu_138_omin_r_0_0_we0,
        omin_r_0_0_address1 => grp_process_i_fu_138_omin_r_0_0_address1,
        omin_r_0_0_ce1 => grp_process_i_fu_138_omin_r_0_0_ce1,
        omin_r_0_0_d1 => grp_process_i_fu_138_omin_r_0_0_d1,
        omin_r_0_0_q1 => ap_const_lv10_0,
        omin_r_0_0_we1 => grp_process_i_fu_138_omin_r_0_0_we1,
        omin_r_0_1_address0 => grp_process_i_fu_138_omin_r_0_1_address0,
        omin_r_0_1_ce0 => grp_process_i_fu_138_omin_r_0_1_ce0,
        omin_r_0_1_d0 => grp_process_i_fu_138_omin_r_0_1_d0,
        omin_r_0_1_q0 => omin_r_0_1_q0,
        omin_r_0_1_we0 => grp_process_i_fu_138_omin_r_0_1_we0,
        omin_r_0_1_address1 => grp_process_i_fu_138_omin_r_0_1_address1,
        omin_r_0_1_ce1 => grp_process_i_fu_138_omin_r_0_1_ce1,
        omin_r_0_1_d1 => grp_process_i_fu_138_omin_r_0_1_d1,
        omin_r_0_1_q1 => ap_const_lv10_0,
        omin_r_0_1_we1 => grp_process_i_fu_138_omin_r_0_1_we1,
        omin_r_1_0_address0 => grp_process_i_fu_138_omin_r_1_0_address0,
        omin_r_1_0_ce0 => grp_process_i_fu_138_omin_r_1_0_ce0,
        omin_r_1_0_d0 => grp_process_i_fu_138_omin_r_1_0_d0,
        omin_r_1_0_q0 => omin_r_1_0_q0,
        omin_r_1_0_we0 => grp_process_i_fu_138_omin_r_1_0_we0,
        omin_r_1_0_address1 => grp_process_i_fu_138_omin_r_1_0_address1,
        omin_r_1_0_ce1 => grp_process_i_fu_138_omin_r_1_0_ce1,
        omin_r_1_0_d1 => grp_process_i_fu_138_omin_r_1_0_d1,
        omin_r_1_0_q1 => ap_const_lv10_0,
        omin_r_1_0_we1 => grp_process_i_fu_138_omin_r_1_0_we1,
        omin_r_1_1_address0 => grp_process_i_fu_138_omin_r_1_1_address0,
        omin_r_1_1_ce0 => grp_process_i_fu_138_omin_r_1_1_ce0,
        omin_r_1_1_d0 => grp_process_i_fu_138_omin_r_1_1_d0,
        omin_r_1_1_q0 => omin_r_1_1_q0,
        omin_r_1_1_we0 => grp_process_i_fu_138_omin_r_1_1_we0,
        omin_r_1_1_address1 => grp_process_i_fu_138_omin_r_1_1_address1,
        omin_r_1_1_ce1 => grp_process_i_fu_138_omin_r_1_1_ce1,
        omin_r_1_1_d1 => grp_process_i_fu_138_omin_r_1_1_d1,
        omin_r_1_1_q1 => ap_const_lv10_0,
        omin_r_1_1_we1 => grp_process_i_fu_138_omin_r_1_1_we1,
        omax_r_0_0_address0 => grp_process_i_fu_138_omax_r_0_0_address0,
        omax_r_0_0_ce0 => grp_process_i_fu_138_omax_r_0_0_ce0,
        omax_r_0_0_d0 => grp_process_i_fu_138_omax_r_0_0_d0,
        omax_r_0_0_q0 => omax_r_0_0_q0,
        omax_r_0_0_we0 => grp_process_i_fu_138_omax_r_0_0_we0,
        omax_r_0_0_address1 => grp_process_i_fu_138_omax_r_0_0_address1,
        omax_r_0_0_ce1 => grp_process_i_fu_138_omax_r_0_0_ce1,
        omax_r_0_0_d1 => grp_process_i_fu_138_omax_r_0_0_d1,
        omax_r_0_0_q1 => ap_const_lv10_0,
        omax_r_0_0_we1 => grp_process_i_fu_138_omax_r_0_0_we1,
        omax_r_0_1_address0 => grp_process_i_fu_138_omax_r_0_1_address0,
        omax_r_0_1_ce0 => grp_process_i_fu_138_omax_r_0_1_ce0,
        omax_r_0_1_d0 => grp_process_i_fu_138_omax_r_0_1_d0,
        omax_r_0_1_q0 => omax_r_0_1_q0,
        omax_r_0_1_we0 => grp_process_i_fu_138_omax_r_0_1_we0,
        omax_r_0_1_address1 => grp_process_i_fu_138_omax_r_0_1_address1,
        omax_r_0_1_ce1 => grp_process_i_fu_138_omax_r_0_1_ce1,
        omax_r_0_1_d1 => grp_process_i_fu_138_omax_r_0_1_d1,
        omax_r_0_1_q1 => ap_const_lv10_0,
        omax_r_0_1_we1 => grp_process_i_fu_138_omax_r_0_1_we1,
        omax_r_1_0_address0 => grp_process_i_fu_138_omax_r_1_0_address0,
        omax_r_1_0_ce0 => grp_process_i_fu_138_omax_r_1_0_ce0,
        omax_r_1_0_d0 => grp_process_i_fu_138_omax_r_1_0_d0,
        omax_r_1_0_q0 => omax_r_1_0_q0,
        omax_r_1_0_we0 => grp_process_i_fu_138_omax_r_1_0_we0,
        omax_r_1_0_address1 => grp_process_i_fu_138_omax_r_1_0_address1,
        omax_r_1_0_ce1 => grp_process_i_fu_138_omax_r_1_0_ce1,
        omax_r_1_0_d1 => grp_process_i_fu_138_omax_r_1_0_d1,
        omax_r_1_0_q1 => ap_const_lv10_0,
        omax_r_1_0_we1 => grp_process_i_fu_138_omax_r_1_0_we1,
        omax_r_1_1_address0 => grp_process_i_fu_138_omax_r_1_1_address0,
        omax_r_1_1_ce0 => grp_process_i_fu_138_omax_r_1_1_ce0,
        omax_r_1_1_d0 => grp_process_i_fu_138_omax_r_1_1_d0,
        omax_r_1_1_q0 => omax_r_1_1_q0,
        omax_r_1_1_we0 => grp_process_i_fu_138_omax_r_1_1_we0,
        omax_r_1_1_address1 => grp_process_i_fu_138_omax_r_1_1_address1,
        omax_r_1_1_ce1 => grp_process_i_fu_138_omax_r_1_1_ce1,
        omax_r_1_1_d1 => grp_process_i_fu_138_omax_r_1_1_d1,
        omax_r_1_1_q1 => ap_const_lv10_0,
        omax_r_1_1_we1 => grp_process_i_fu_138_omax_r_1_1_we1,
        omin_w_0_0_address0 => grp_process_i_fu_138_omin_w_0_0_address0,
        omin_w_0_0_ce0 => grp_process_i_fu_138_omin_w_0_0_ce0,
        omin_w_0_0_d0 => grp_process_i_fu_138_omin_w_0_0_d0,
        omin_w_0_0_q0 => ap_const_lv10_0,
        omin_w_0_0_we0 => grp_process_i_fu_138_omin_w_0_0_we0,
        omin_w_0_0_address1 => grp_process_i_fu_138_omin_w_0_0_address1,
        omin_w_0_0_ce1 => grp_process_i_fu_138_omin_w_0_0_ce1,
        omin_w_0_0_d1 => grp_process_i_fu_138_omin_w_0_0_d1,
        omin_w_0_0_q1 => ap_const_lv10_0,
        omin_w_0_0_we1 => grp_process_i_fu_138_omin_w_0_0_we1,
        omin_w_0_1_address0 => grp_process_i_fu_138_omin_w_0_1_address0,
        omin_w_0_1_ce0 => grp_process_i_fu_138_omin_w_0_1_ce0,
        omin_w_0_1_d0 => grp_process_i_fu_138_omin_w_0_1_d0,
        omin_w_0_1_q0 => ap_const_lv10_0,
        omin_w_0_1_we0 => grp_process_i_fu_138_omin_w_0_1_we0,
        omin_w_0_1_address1 => grp_process_i_fu_138_omin_w_0_1_address1,
        omin_w_0_1_ce1 => grp_process_i_fu_138_omin_w_0_1_ce1,
        omin_w_0_1_d1 => grp_process_i_fu_138_omin_w_0_1_d1,
        omin_w_0_1_q1 => ap_const_lv10_0,
        omin_w_0_1_we1 => grp_process_i_fu_138_omin_w_0_1_we1,
        omin_w_1_0_address0 => grp_process_i_fu_138_omin_w_1_0_address0,
        omin_w_1_0_ce0 => grp_process_i_fu_138_omin_w_1_0_ce0,
        omin_w_1_0_d0 => grp_process_i_fu_138_omin_w_1_0_d0,
        omin_w_1_0_q0 => ap_const_lv10_0,
        omin_w_1_0_we0 => grp_process_i_fu_138_omin_w_1_0_we0,
        omin_w_1_0_address1 => grp_process_i_fu_138_omin_w_1_0_address1,
        omin_w_1_0_ce1 => grp_process_i_fu_138_omin_w_1_0_ce1,
        omin_w_1_0_d1 => grp_process_i_fu_138_omin_w_1_0_d1,
        omin_w_1_0_q1 => ap_const_lv10_0,
        omin_w_1_0_we1 => grp_process_i_fu_138_omin_w_1_0_we1,
        omin_w_1_1_address0 => grp_process_i_fu_138_omin_w_1_1_address0,
        omin_w_1_1_ce0 => grp_process_i_fu_138_omin_w_1_1_ce0,
        omin_w_1_1_d0 => grp_process_i_fu_138_omin_w_1_1_d0,
        omin_w_1_1_q0 => ap_const_lv10_0,
        omin_w_1_1_we0 => grp_process_i_fu_138_omin_w_1_1_we0,
        omin_w_1_1_address1 => grp_process_i_fu_138_omin_w_1_1_address1,
        omin_w_1_1_ce1 => grp_process_i_fu_138_omin_w_1_1_ce1,
        omin_w_1_1_d1 => grp_process_i_fu_138_omin_w_1_1_d1,
        omin_w_1_1_q1 => ap_const_lv10_0,
        omin_w_1_1_we1 => grp_process_i_fu_138_omin_w_1_1_we1,
        omax_w_0_0_address0 => grp_process_i_fu_138_omax_w_0_0_address0,
        omax_w_0_0_ce0 => grp_process_i_fu_138_omax_w_0_0_ce0,
        omax_w_0_0_d0 => grp_process_i_fu_138_omax_w_0_0_d0,
        omax_w_0_0_q0 => ap_const_lv10_0,
        omax_w_0_0_we0 => grp_process_i_fu_138_omax_w_0_0_we0,
        omax_w_0_0_address1 => grp_process_i_fu_138_omax_w_0_0_address1,
        omax_w_0_0_ce1 => grp_process_i_fu_138_omax_w_0_0_ce1,
        omax_w_0_0_d1 => grp_process_i_fu_138_omax_w_0_0_d1,
        omax_w_0_0_q1 => ap_const_lv10_0,
        omax_w_0_0_we1 => grp_process_i_fu_138_omax_w_0_0_we1,
        omax_w_0_1_address0 => grp_process_i_fu_138_omax_w_0_1_address0,
        omax_w_0_1_ce0 => grp_process_i_fu_138_omax_w_0_1_ce0,
        omax_w_0_1_d0 => grp_process_i_fu_138_omax_w_0_1_d0,
        omax_w_0_1_q0 => ap_const_lv10_0,
        omax_w_0_1_we0 => grp_process_i_fu_138_omax_w_0_1_we0,
        omax_w_0_1_address1 => grp_process_i_fu_138_omax_w_0_1_address1,
        omax_w_0_1_ce1 => grp_process_i_fu_138_omax_w_0_1_ce1,
        omax_w_0_1_d1 => grp_process_i_fu_138_omax_w_0_1_d1,
        omax_w_0_1_q1 => ap_const_lv10_0,
        omax_w_0_1_we1 => grp_process_i_fu_138_omax_w_0_1_we1,
        omax_w_1_0_address0 => grp_process_i_fu_138_omax_w_1_0_address0,
        omax_w_1_0_ce0 => grp_process_i_fu_138_omax_w_1_0_ce0,
        omax_w_1_0_d0 => grp_process_i_fu_138_omax_w_1_0_d0,
        omax_w_1_0_q0 => ap_const_lv10_0,
        omax_w_1_0_we0 => grp_process_i_fu_138_omax_w_1_0_we0,
        omax_w_1_0_address1 => grp_process_i_fu_138_omax_w_1_0_address1,
        omax_w_1_0_ce1 => grp_process_i_fu_138_omax_w_1_0_ce1,
        omax_w_1_0_d1 => grp_process_i_fu_138_omax_w_1_0_d1,
        omax_w_1_0_q1 => ap_const_lv10_0,
        omax_w_1_0_we1 => grp_process_i_fu_138_omax_w_1_0_we1,
        omax_w_1_1_address0 => grp_process_i_fu_138_omax_w_1_1_address0,
        omax_w_1_1_ce0 => grp_process_i_fu_138_omax_w_1_1_ce0,
        omax_w_1_1_d0 => grp_process_i_fu_138_omax_w_1_1_d0,
        omax_w_1_1_q0 => ap_const_lv10_0,
        omax_w_1_1_we0 => grp_process_i_fu_138_omax_w_1_1_we0,
        omax_w_1_1_address1 => grp_process_i_fu_138_omax_w_1_1_address1,
        omax_w_1_1_ce1 => grp_process_i_fu_138_omax_w_1_1_ce1,
        omax_w_1_1_d1 => grp_process_i_fu_138_omax_w_1_1_d1,
        omax_w_1_1_q1 => ap_const_lv10_0,
        omax_w_1_1_we1 => grp_process_i_fu_138_omax_w_1_1_we1,
        imgOutput_data_din => grp_process_i_fu_138_imgOutput_data_din,
        imgOutput_data_full_n => imgOutput_data_full_n,
        imgOutput_data_write => grp_process_i_fu_138_imgOutput_data_write,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        Tile_mVBlkCount_val14_ap_vld => ap_const_logic_1,
        Tile_mVBlkSize_0_val17_ap_vld => ap_const_logic_1,
        Tile_mVBlkSize_1_val20_ap_vld => ap_const_logic_1,
        Tile_mHBlkSize_0_val23_ap_vld => ap_const_logic_1,
        Tile_mHBlkSize_1_val26_ap_vld => ap_const_logic_1,
        ap_start => grp_process_i_fu_138_ap_start,
        Tile_mRows_val2_ap_vld => ap_const_logic_1,
        Tile_mCols_val5_ap_vld => ap_const_logic_1,
        ap_done => grp_process_i_fu_138_ap_done,
        ap_ready => grp_process_i_fu_138_ap_ready,
        ap_idle => grp_process_i_fu_138_ap_idle,
        ap_continue => grp_process_i_fu_138_ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_boolean_0 = ap_block_state7_on_subcall_done))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_process_i_fu_138_ap_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_process_i_fu_138_ap_done <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_boolean_0 = ap_block_state7_on_subcall_done))) then 
                    ap_sync_reg_grp_process_i_fu_138_ap_done <= ap_const_logic_0;
                elsif ((grp_process_i_fu_138_ap_done = ap_const_logic_1)) then 
                    ap_sync_reg_grp_process_i_fu_138_ap_done <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_process_i_fu_138_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_process_i_fu_138_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_boolean_0 = ap_block_state7_on_subcall_done))) then 
                    ap_sync_reg_grp_process_i_fu_138_ap_ready <= ap_const_logic_0;
                elsif ((grp_process_i_fu_138_ap_ready = ap_const_logic_1)) then 
                    ap_sync_reg_grp_process_i_fu_138_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1_ignore_call19))) then 
                    grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_ready = ap_const_logic_1)) then 
                    grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1_ignore_call43))) then 
                    grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_ready = ap_const_logic_1)) then 
                    grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_process_i_fu_138_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_process_i_fu_138_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_sync_grp_process_i_fu_138_ap_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
                    grp_process_i_fu_138_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_process_i_fu_138_ap_ready = ap_const_logic_1)) then 
                    grp_process_i_fu_138_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                Tile_mBlkColsNPCAligned_reg_498 <= Tile_mBlkColsNPCAligned_fu_213_p2;
                Tile_mVBlkCount_reg_526 <= Tile_mVBlkCount_fu_251_p2;
                add_ln121_reg_505 <= add_ln121_fu_219_p2;
                lshr_ln126_reg_510 <= lshr_ln126_fu_225_p2;
                select_ln113_reg_491 <= select_ln113_fu_202_p3;
                select_ln132_reg_515 <= select_ln132_fu_234_p3;
                trunc_ln617_reg_531 <= trunc_ln617_fu_257_p1;
                    zext_ln139_reg_521(3 downto 0) <= zext_ln139_fu_241_p1(3 downto 0);
                    zext_ln617_reg_486(9 downto 0) <= zext_ln617_fu_190_p1(9 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                Tile_mHBlkCount_reg_537 <= Tile_mHBlkCount_fu_279_p2;
                icmp_ln142_reg_542 <= icmp_ln142_fu_295_p2;
                shl_ln144_reg_548 <= shl_ln144_fu_310_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                Tile_mHBlkSize_2_reg_553 <= Tile_mHBlkSize_2_fu_381_p3;
                Tile_mVBlkCount_2_reg_558 <= Tile_mVBlkCount_2_fu_417_p3;
                Tile_mVBlkSize_reg_563 <= Tile_mVBlkSize_fu_423_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state2_on_subcall_done) or (ap_const_boolean_1 = ap_block_state2))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                add_ln105_reg_471 <= add_ln105_fu_185_p2;
                c_reg_455 <= in_cols_dout;
                r_reg_463 <= in_rows_dout;
                targetBlock2_reg_481 <= grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_return;
                targetBlock_reg_476 <= grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_blkColsLog2_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                blkColsLog2_loc_fu_96 <= grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_blkColsLog2_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_blkRowsLog2_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                blkRowsLog2_loc_fu_92 <= grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_blkRowsLog2_out;
            end if;
        end if;
    end process;
    zext_ln617_reg_486(31 downto 10) <= "0000000000000000000000";
    zext_ln139_reg_521(31 downto 4) <= "0000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state1, ap_block_state2, ap_block_state2_on_subcall_done, ap_CS_fsm_state7, ap_block_state7_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((ap_const_boolean_1 = ap_block_state2_on_subcall_done) or (ap_const_boolean_1 = ap_block_state2))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_boolean_0 = ap_block_state7_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    Tile_mBlkColsNPCAligned_fu_213_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv11_1),to_integer(unsigned('0' & zext_ln119_3_fu_209_p1(11-1 downto 0)))));
    Tile_mHBlkCount_fu_279_p2 <= std_logic_vector(shift_right(signed(add_ln121_1_fu_273_p2),to_integer(unsigned('0' & zext_ln119_2_fu_264_p1(13-1 downto 0)))));
    Tile_mHBlkSize_1_fu_371_p4 <= t_fu_365_p2(14 downto 1);
    Tile_mHBlkSize_2_fu_381_p3 <= 
        Tile_mHBlkSize_1_fu_371_p4 when (icmp_ln124_fu_346_p2(0) = '1') else 
        zext_ln617_4_fu_334_p1;
    Tile_mVBlkCount_1_fu_412_p2 <= std_logic_vector(unsigned(trunc_ln617_reg_531) + unsigned(ap_const_lv26_1));
    Tile_mVBlkCount_2_fu_417_p3 <= 
        Tile_mVBlkCount_1_fu_412_p2 when (icmp_ln142_reg_542(0) = '1') else 
        trunc_ln617_reg_531;
    Tile_mVBlkCount_fu_251_p2 <= std_logic_vector(shift_right(unsigned(add_ln139_fu_245_p2),to_integer(unsigned('0' & zext_ln139_fu_241_p1(31-1 downto 0)))));
    Tile_mVBlkSize_fu_423_p3 <= 
        sext_ln145_fu_408_p1 when (icmp_ln142_reg_542(0) = '1') else 
        block_rows_cast_fu_316_p1;
    add_ln105_fu_185_p2 <= std_logic_vector(unsigned(block_rows) + unsigned(ap_const_lv31_7FFFFFFF));
    add_ln121_1_fu_273_p2 <= std_logic_vector(signed(sext_ln121_fu_270_p1) + signed(zext_ln617_5_fu_267_p1));
    add_ln121_fu_219_p2 <= std_logic_vector(unsigned(zext_ln96_1_fu_193_p1) + unsigned(ap_const_lv11_7FF));
    add_ln139_fu_245_p2 <= std_logic_vector(unsigned(zext_ln617_3_fu_196_p1) + unsigned(zext_ln617_fu_190_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_1 = ap_block_state2_on_subcall_done) or (ap_const_boolean_1 = ap_block_state2))) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(ap_block_state7_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state7_on_subcall_done)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call19_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call19 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call43_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call43 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state2_assign_proc : process(in_rows_empty_n, in_cols_empty_n)
    begin
                ap_block_state2 <= ((in_cols_empty_n = ap_const_logic_0) or (in_rows_empty_n = ap_const_logic_0));
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_done, grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_done = ap_const_logic_0) or (grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_done = ap_const_logic_0));
    end process;


    ap_block_state7_on_subcall_done_assign_proc : process(ap_sync_grp_process_i_fu_138_ap_ready, ap_sync_grp_process_i_fu_138_ap_done)
    begin
                ap_block_state7_on_subcall_done <= ((ap_sync_grp_process_i_fu_138_ap_ready and ap_sync_grp_process_i_fu_138_ap_done) = ap_const_logic_0);
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state7, ap_block_state7_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_boolean_0 = ap_block_state7_on_subcall_done))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7, ap_block_state7_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_boolean_0 = ap_block_state7_on_subcall_done))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_sync_grp_process_i_fu_138_ap_done <= (grp_process_i_fu_138_ap_done or ap_sync_reg_grp_process_i_fu_138_ap_done);
    ap_sync_grp_process_i_fu_138_ap_ready <= (grp_process_i_fu_138_ap_ready or ap_sync_reg_grp_process_i_fu_138_ap_ready);
    block_rows_cast_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(block_rows),32));
    grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_start <= grp_process_Pipeline_VITIS_LOOP_113_1_fu_124_ap_start_reg;
    grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_start <= grp_process_Pipeline_VITIS_LOOP_132_2_fu_131_ap_start_reg;

    grp_process_i_fu_138_ap_continue_assign_proc : process(ap_CS_fsm_state7, ap_block_state7_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_boolean_0 = ap_block_state7_on_subcall_done))) then 
            grp_process_i_fu_138_ap_continue <= ap_const_logic_1;
        else 
            grp_process_i_fu_138_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    grp_process_i_fu_138_ap_start <= grp_process_i_fu_138_ap_start_reg;
    icmp_ln124_fu_346_p2 <= "1" when (signed(zext_ln96_2_fu_325_p1) < signed(th_fu_340_p2)) else "0";
    icmp_ln142_fu_295_p2 <= "1" when (signed(zext_ln617_reg_486) < signed(tv_fu_291_p2)) else "0";

    imgInput_data_read_assign_proc : process(grp_process_i_fu_138_imgInput_data_read, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            imgInput_data_read <= grp_process_i_fu_138_imgInput_data_read;
        else 
            imgInput_data_read <= ap_const_logic_0;
        end if; 
    end process;

    imgOutput_data_din <= grp_process_i_fu_138_imgOutput_data_din;

    imgOutput_data_write_assign_proc : process(grp_process_i_fu_138_imgOutput_data_write, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            imgOutput_data_write <= grp_process_i_fu_138_imgOutput_data_write;
        else 
            imgOutput_data_write <= ap_const_logic_0;
        end if; 
    end process;


    in_cols_blk_n_assign_proc : process(in_cols_empty_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            in_cols_blk_n <= in_cols_empty_n;
        else 
            in_cols_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_cols_read_assign_proc : process(ap_CS_fsm_state2, ap_block_state2, ap_block_state2_on_subcall_done)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_on_subcall_done) or (ap_const_boolean_1 = ap_block_state2))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            in_cols_read <= ap_const_logic_1;
        else 
            in_cols_read <= ap_const_logic_0;
        end if; 
    end process;


    in_rows_blk_n_assign_proc : process(in_rows_empty_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            in_rows_blk_n <= in_rows_empty_n;
        else 
            in_rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_rows_read_assign_proc : process(ap_CS_fsm_state2, ap_block_state2, ap_block_state2_on_subcall_done)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_on_subcall_done) or (ap_const_boolean_1 = ap_block_state2))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            in_rows_read <= ap_const_logic_1;
        else 
            in_rows_read <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln126_fu_225_p2 <= std_logic_vector(shift_right(unsigned(zext_ln96_1_fu_193_p1),to_integer(unsigned('0' & zext_ln119_3_fu_209_p1(11-1 downto 0)))));
    lshr_ln144_fu_300_p2 <= std_logic_vector(shift_right(unsigned(zext_ln617_2_fu_261_p1),to_integer(unsigned('0' & zext_ln139_2_fu_288_p1(11-1 downto 0)))));
    omax_r_0_0_address0 <= grp_process_i_fu_138_omax_r_0_0_address0;
    omax_r_0_0_ce0 <= grp_process_i_fu_138_omax_r_0_0_ce0;
    omax_r_0_1_address0 <= grp_process_i_fu_138_omax_r_0_1_address0;
    omax_r_0_1_ce0 <= grp_process_i_fu_138_omax_r_0_1_ce0;
    omax_r_1_0_address0 <= grp_process_i_fu_138_omax_r_1_0_address0;
    omax_r_1_0_ce0 <= grp_process_i_fu_138_omax_r_1_0_ce0;
    omax_r_1_1_address0 <= grp_process_i_fu_138_omax_r_1_1_address0;
    omax_r_1_1_ce0 <= grp_process_i_fu_138_omax_r_1_1_ce0;
    omax_w_0_0_address0 <= grp_process_i_fu_138_omax_w_0_0_address0;
    omax_w_0_0_ce0 <= grp_process_i_fu_138_omax_w_0_0_ce0;
    omax_w_0_0_d0 <= grp_process_i_fu_138_omax_w_0_0_d0;
    omax_w_0_0_we0 <= grp_process_i_fu_138_omax_w_0_0_we0;
    omax_w_0_1_address0 <= grp_process_i_fu_138_omax_w_0_1_address0;
    omax_w_0_1_ce0 <= grp_process_i_fu_138_omax_w_0_1_ce0;
    omax_w_0_1_d0 <= grp_process_i_fu_138_omax_w_0_1_d0;
    omax_w_0_1_we0 <= grp_process_i_fu_138_omax_w_0_1_we0;
    omax_w_1_0_address0 <= grp_process_i_fu_138_omax_w_1_0_address0;
    omax_w_1_0_ce0 <= grp_process_i_fu_138_omax_w_1_0_ce0;
    omax_w_1_0_d0 <= grp_process_i_fu_138_omax_w_1_0_d0;
    omax_w_1_0_we0 <= grp_process_i_fu_138_omax_w_1_0_we0;
    omax_w_1_1_address0 <= grp_process_i_fu_138_omax_w_1_1_address0;
    omax_w_1_1_ce0 <= grp_process_i_fu_138_omax_w_1_1_ce0;
    omax_w_1_1_d0 <= grp_process_i_fu_138_omax_w_1_1_d0;
    omax_w_1_1_we0 <= grp_process_i_fu_138_omax_w_1_1_we0;
    omin_r_0_0_address0 <= grp_process_i_fu_138_omin_r_0_0_address0;
    omin_r_0_0_ce0 <= grp_process_i_fu_138_omin_r_0_0_ce0;
    omin_r_0_1_address0 <= grp_process_i_fu_138_omin_r_0_1_address0;
    omin_r_0_1_ce0 <= grp_process_i_fu_138_omin_r_0_1_ce0;
    omin_r_1_0_address0 <= grp_process_i_fu_138_omin_r_1_0_address0;
    omin_r_1_0_ce0 <= grp_process_i_fu_138_omin_r_1_0_ce0;
    omin_r_1_1_address0 <= grp_process_i_fu_138_omin_r_1_1_address0;
    omin_r_1_1_ce0 <= grp_process_i_fu_138_omin_r_1_1_ce0;
    omin_w_0_0_address0 <= grp_process_i_fu_138_omin_w_0_0_address0;
    omin_w_0_0_ce0 <= grp_process_i_fu_138_omin_w_0_0_ce0;
    omin_w_0_0_d0 <= grp_process_i_fu_138_omin_w_0_0_d0;
    omin_w_0_0_we0 <= grp_process_i_fu_138_omin_w_0_0_we0;
    omin_w_0_1_address0 <= grp_process_i_fu_138_omin_w_0_1_address0;
    omin_w_0_1_ce0 <= grp_process_i_fu_138_omin_w_0_1_ce0;
    omin_w_0_1_d0 <= grp_process_i_fu_138_omin_w_0_1_d0;
    omin_w_0_1_we0 <= grp_process_i_fu_138_omin_w_0_1_we0;
    omin_w_1_0_address0 <= grp_process_i_fu_138_omin_w_1_0_address0;
    omin_w_1_0_ce0 <= grp_process_i_fu_138_omin_w_1_0_ce0;
    omin_w_1_0_d0 <= grp_process_i_fu_138_omin_w_1_0_d0;
    omin_w_1_0_we0 <= grp_process_i_fu_138_omin_w_1_0_we0;
    omin_w_1_1_address0 <= grp_process_i_fu_138_omin_w_1_1_address0;
    omin_w_1_1_ce0 <= grp_process_i_fu_138_omin_w_1_1_ce0;
    omin_w_1_1_d0 <= grp_process_i_fu_138_omin_w_1_1_d0;
    omin_w_1_1_we0 <= grp_process_i_fu_138_omin_w_1_1_we0;
    select_ln113_fu_202_p3 <= 
        ap_const_lv4_A when (targetBlock_reg_476(0) = '1') else 
        blkColsLog2_loc_fu_96;
    select_ln132_fu_234_p3 <= 
        ap_const_lv4_A when (targetBlock2_reg_481(0) = '1') else 
        blkRowsLog2_loc_fu_92;
        sext_ln121_fu_270_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln121_reg_505),13));

        sext_ln145_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln3_fu_398_p4),32));

        sext_ln617_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Tile_mHBlkCount_reg_537),17));

    shl_ln126_fu_355_p2 <= std_logic_vector(shift_left(unsigned(zext_ln126_fu_352_p1),to_integer(unsigned('0' & zext_ln119_fu_328_p1(14-1 downto 0)))));
    shl_ln144_fu_310_p2 <= std_logic_vector(shift_left(unsigned(zext_ln144_fu_306_p1),to_integer(unsigned('0' & zext_ln139_1_fu_285_p1(14-1 downto 0)))));
    t_1_fu_392_p2 <= std_logic_vector(unsigned(zext_ln617_1_fu_319_p1) - unsigned(zext_ln144_1_fu_389_p1));
    t_fu_365_p2 <= std_logic_vector(unsigned(zext_ln96_fu_322_p1) - unsigned(zext_ln126_1_fu_361_p1));
    th_fu_340_p2 <= std_logic_vector(shift_left(unsigned(sext_ln617_fu_337_p1),to_integer(unsigned('0' & zext_ln119_1_fu_331_p1(17-1 downto 0)))));
    trunc_ln3_fu_398_p4 <= t_1_fu_392_p2(14 downto 1);
    trunc_ln617_fu_257_p1 <= Tile_mVBlkCount_fu_251_p2(26 - 1 downto 0);
    tv_fu_291_p2 <= std_logic_vector(shift_left(unsigned(Tile_mVBlkCount_reg_526),to_integer(unsigned('0' & zext_ln139_reg_521(31-1 downto 0)))));
    zext_ln119_1_fu_331_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln113_reg_491),17));
    zext_ln119_2_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln113_reg_491),13));
    zext_ln119_3_fu_209_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln113_fu_202_p3),11));
    zext_ln119_fu_328_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln113_reg_491),14));
    zext_ln126_1_fu_361_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln126_fu_355_p2),15));
    zext_ln126_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln126_reg_510),14));
    zext_ln139_1_fu_285_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln132_reg_515),14));
    zext_ln139_2_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln132_reg_515),11));
    zext_ln139_fu_241_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln132_fu_234_p3),32));
    zext_ln144_1_fu_389_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln144_reg_548),15));
    zext_ln144_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln144_fu_300_p2),14));
    zext_ln617_1_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_reg_463),15));
    zext_ln617_2_fu_261_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_reg_463),11));
    zext_ln617_3_fu_196_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln105_reg_471),32));
    zext_ln617_4_fu_334_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Tile_mBlkColsNPCAligned_reg_498),14));
    zext_ln617_5_fu_267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Tile_mBlkColsNPCAligned_reg_498),13));
    zext_ln617_fu_190_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_reg_463),32));
    zext_ln96_1_fu_193_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_reg_455),11));
    zext_ln96_2_fu_325_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_reg_455),17));
    zext_ln96_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_reg_455),15));
end behav;
