domain_path: /home/alen/git/AMD-FPGA-Practice/zybo-z7-audio/sw/audio-pipe-sw-v0/zybo-z7-audio/export/zybo-z7-audio/sw/standalone_ps7_cortexa9_0
app_src_dir: /home/alen/AMD-Xilinx/2025.2/Vitis/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
