[hls]
relative_roots=/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.runs/video_pipe_hw_v_demosaic_0_0_synth_1
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=zipperremoval/anonymous 
syn.directive.pipeline=zipperremoval/anonymous 
syn.directive.pipeline=zipperremoval/anonymous 
syn.directive.pipeline=zipperremoval/anonymous 


