<AutoPilot:project xmlns:AutoPilot="com.autoesl.autopilot.project" projectType="C/C++" top="v_demosaic" name="prj" ideType="classic">
    <solutions>
        <solution name="sol" status=""/>
    </solutions>
    <files>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls/hls_video_undistort.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls/hls_video_types.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls/hls_video_stereobm.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls/hls_video_mem.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls/hls_video_io.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls/hls_video_imgproc.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls/hls_video_imgbase.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls/hls_video_hough.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls/hls_video_histogram.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls/hls_video_harris.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls/hls_video_haar.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls/hls_video_fast.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls/hls_video_core.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls/hls_video_arithm.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls/hls_axi_io.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls_opencv.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls_video.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/v_demosaic.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/v_demosaic.cpp" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/v_demosaic_config.h" sc="0" tb="false" cflags="-I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src/hls -I/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/hw/video-pipe-hw-v1/video_pipe_hw.gen/sources_1/bd/video_pipe_hw/ip/video_pipe_hw_v_demosaic_0_0/src" csimflags="" blackbox="false"/>
    </files>
</AutoPilot:project>
