// -------------------------------------------------------------
// 
// File Name: d:\soc_prj\hdlcoder\CLAHE\hdlsrc\CLAHEAlgorithm_fpga\clahe_ip_src_histResetBuffer.v
// Created: 2023-12-22 10:28:14
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: clahe_ip_src_histResetBuffer
// Source Path: CLAHEAlgorithm_fpga/CLAHE/CLAHEHDLAlgorithm/tileGeneration/histResetBuffer
// Hierarchy Level: 3
// Model version: 424
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module clahe_ip_src_histResetBuffer
          (clk,
           reset,
           enb,
           pixelIn,
           busIn_vStart,
           busIn_valid,
           pixelOut,
           busOut_hStart,
           busOut_hEnd,
           busOut_vStart,
           busOut_vEnd,
           busOut_valid,
           reset_1);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] pixelIn;  // uint8
  input   busIn_vStart;
  input   busIn_valid;
  output  [7:0] pixelOut;  // uint8
  output  busOut_hStart;
  output  busOut_hEnd;
  output  busOut_vStart;
  output  busOut_vEnd;
  output  busOut_valid;
  output  reset_1;


  reg [7:0] Delay_out1;  // uint8
  reg [7:0] Delay3_regin;  // uint8
  reg [7:0] Delay3_waddr;  // ufix8
  wire Delay3_wrenb;  // ufix1
  reg [7:0] Delay3_raddr;  // ufix8
  wire [7:0] Delay3_regout;  // uint8
  reg [7:0] Delay3_out1;  // uint8
  wire vStart;
  wire valid;
  reg  Delay1_out1;
  reg  [255:0] Delay4_reg;  // ufix1 [256]
  wire Delay4_out1;
  wire pixelBusGenerator_out1_hStart;
  wire pixelBusGenerator_out1_hEnd;
  wire pixelBusGenerator_out1_vStart;
  wire pixelBusGenerator_out1_vEnd;
  wire pixelBusGenerator_out1_valid;


  always @(posedge clk)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= pixelIn;
        end
      end
    end



  // Input register for RAM-based shift register Delay3
  always @(posedge clk)
    begin : Delay3_reginc_process
      if (reset == 1'b1) begin
        Delay3_regin <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay3_regin <= Delay_out1;
        end
      end
    end



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 253
  // Write address counter for RAM-based shift register Delay3
  always @(posedge clk)
    begin : Delay3_wr_process
      if (reset == 1'b1) begin
        Delay3_waddr <= 8'b00000000;
      end
      else begin
        if (enb) begin
          if (Delay3_waddr >= 8'b11111101) begin
            Delay3_waddr <= 8'b00000000;
          end
          else begin
            Delay3_waddr <= Delay3_waddr + 8'b00000001;
          end
        end
      end
    end



  assign Delay3_wrenb = 1'b1;



  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 253
  // Read address counter for RAM-based shift register Delay3
  always @(posedge clk)
    begin : Delay3_rd_process
      if (reset == 1'b1) begin
        Delay3_raddr <= 8'b00000001;
      end
      else begin
        if (enb) begin
          if (Delay3_raddr >= 8'b11111101) begin
            Delay3_raddr <= 8'b00000000;
          end
          else begin
            Delay3_raddr <= Delay3_raddr + 8'b00000001;
          end
        end
      end
    end



  clahe_ip_src_SimpleDualPortRAM_generic #(.AddrWidth(8),
                                           .DataWidth(8)
                                           )
                                         u_ShiftRegisterRAM (.clk(clk),
                                                             .enb(enb),
                                                             .wr_din(Delay3_regin),
                                                             .wr_addr(Delay3_waddr),
                                                             .wr_en(Delay3_wrenb),  // ufix1
                                                             .rd_addr(Delay3_raddr),
                                                             .dout(Delay3_regout)
                                                             );

  // Output register for RAM-based shift register Delay3
  always @(posedge clk)
    begin : Delay3_regoutc_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= Delay3_regout;
        end
      end
    end



  assign pixelOut = Delay3_out1;

  assign vStart = busIn_vStart;

  assign valid = busIn_valid;

  always @(posedge clk)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= valid;
        end
      end
    end



  always @(posedge clk)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_reg <= {256{1'b0}};
      end
      else begin
        if (enb) begin
          Delay4_reg[0] <= Delay1_out1;
          Delay4_reg[32'sd255:32'sd1] <= Delay4_reg[32'sd254:32'sd0];
        end
      end
    end

  assign Delay4_out1 = Delay4_reg[255];



  clahe_ip_src_pixelBusGenerator_block1 u_pixelBusGenerator (.clk(clk),
                                                             .reset(reset),
                                                             .enb(enb),
                                                             .reset_1(vStart),
                                                             .validIn(Delay4_out1),
                                                             .busOut_hStart(pixelBusGenerator_out1_hStart),
                                                             .busOut_hEnd(pixelBusGenerator_out1_hEnd),
                                                             .busOut_vStart(pixelBusGenerator_out1_vStart),
                                                             .busOut_vEnd(pixelBusGenerator_out1_vEnd),
                                                             .busOut_valid(pixelBusGenerator_out1_valid)
                                                             );

  assign busOut_hStart = pixelBusGenerator_out1_hStart;

  assign busOut_hEnd = pixelBusGenerator_out1_hEnd;

  assign busOut_vStart = pixelBusGenerator_out1_vStart;

  assign busOut_vEnd = pixelBusGenerator_out1_vEnd;

  assign busOut_valid = pixelBusGenerator_out1_valid;

  assign reset_1 = busIn_vStart;

endmodule  // clahe_ip_src_histResetBuffer

