[hls]
relative_roots=/home/alen/git/AMD-FPGA-Practice/kv260-imx219-video/sw/video-pipe-sw-v4/awb-hls-L1
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=xf::cv::awbchannelgainkernel<20, 20, 2160, 3840, 1, 2, 2, 3, 23, 23, 13, 13, 3840>/VITIS_LOOP_216_3 


