// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module autowhitebalance_accel_p_hls_fptosi_float_i32_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        return_r,
        x
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [31:0] return_r;
input  [31:0] x;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] return_r;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] x_read_reg_187;
reg    ap_block_state1;
wire   [31:0] result_2_fu_178_p3;
reg   [31:0] return_r_preg;
wire    ap_CS_fsm_state2;
wire   [31:0] data_fu_51_p1;
wire   [22:0] trunc_ln342_fu_70_p1;
wire   [24:0] mantissa_fu_74_p4;
wire   [7:0] xs_exp_fu_62_p3;
wire   [8:0] zext_ln317_fu_88_p1;
wire   [8:0] add_ln317_fu_92_p2;
wire   [7:0] sub_ln18_fu_106_p2;
wire   [0:0] tmp_fu_98_p3;
wire  signed [8:0] sext_ln18_fu_112_p1;
wire   [8:0] select_ln18_fu_116_p3;
wire  signed [31:0] sext_ln18_1_fu_124_p1;
wire   [78:0] zext_ln15_fu_84_p1;
wire   [78:0] zext_ln18_fu_128_p1;
wire   [78:0] lshr_ln18_fu_132_p2;
wire   [78:0] shl_ln18_fu_138_p2;
wire   [31:0] tmp_1_fu_144_p4;
wire   [31:0] tmp_2_fu_154_p4;
wire   [31:0] val_fu_164_p3;
wire   [0:0] xs_sign_fu_54_p3;
wire   [31:0] result_1_fu_172_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 return_r_preg = 32'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        return_r_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            return_r_preg <= result_2_fu_178_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        x_read_reg_187 <= x;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        return_r = result_2_fu_178_p3;
    end else begin
        return_r = return_r_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln317_fu_92_p2 = ($signed(zext_ln317_fu_88_p1) + $signed(9'd385));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign data_fu_51_p1 = x_read_reg_187;

assign lshr_ln18_fu_132_p2 = zext_ln15_fu_84_p1 >> zext_ln18_fu_128_p1;

assign mantissa_fu_74_p4 = {{{{1'd1}, {trunc_ln342_fu_70_p1}}}, {1'd0}};

assign result_1_fu_172_p2 = (32'd0 - val_fu_164_p3);

assign result_2_fu_178_p3 = ((xs_sign_fu_54_p3[0:0] == 1'b1) ? result_1_fu_172_p2 : val_fu_164_p3);

assign select_ln18_fu_116_p3 = ((tmp_fu_98_p3[0:0] == 1'b1) ? sext_ln18_fu_112_p1 : add_ln317_fu_92_p2);

assign sext_ln18_1_fu_124_p1 = $signed(select_ln18_fu_116_p3);

assign sext_ln18_fu_112_p1 = $signed(sub_ln18_fu_106_p2);

assign shl_ln18_fu_138_p2 = zext_ln15_fu_84_p1 << zext_ln18_fu_128_p1;

assign sub_ln18_fu_106_p2 = (8'd127 - xs_exp_fu_62_p3);

assign tmp_1_fu_144_p4 = {{lshr_ln18_fu_132_p2[55:24]}};

assign tmp_2_fu_154_p4 = {{shl_ln18_fu_138_p2[55:24]}};

assign tmp_fu_98_p3 = add_ln317_fu_92_p2[32'd8];

assign trunc_ln342_fu_70_p1 = data_fu_51_p1[22:0];

assign val_fu_164_p3 = ((tmp_fu_98_p3[0:0] == 1'b1) ? tmp_1_fu_144_p4 : tmp_2_fu_154_p4);

assign xs_exp_fu_62_p3 = {{data_fu_51_p1[30:23]}};

assign xs_sign_fu_54_p3 = data_fu_51_p1[32'd31];

assign zext_ln15_fu_84_p1 = mantissa_fu_74_p4;

assign zext_ln18_fu_128_p1 = $unsigned(sext_ln18_1_fu_124_p1);

assign zext_ln317_fu_88_p1 = xs_exp_fu_62_p3;

endmodule //autowhitebalance_accel_p_hls_fptosi_float_i32_2
